In [8]:
import geopandas as gpd
import pandas as pd
import numpy as np

In [2]:
crop_excel = r"D:\imWEBs\STC\STC-Landuse-Data\STC-landmanagement-2001-2010\STCLanduse_1991_to_2004.xls"

In [11]:
crops = pd.read_excel(crop_excel)

crops

In [12]:
shp_path = r"D:\imWEBs\STC\STC-Landuse-Data\STC-landmanagement-2001-2010"
out_path = r"D:\imWEBs\STC\STC-Landuse-Data\STC-landmanagement-2001-2010\add_crop"

In [13]:
years = np.arange(start = 2001, stop = 2011, step = 1)
years

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010])

In [14]:
shp = gpd.read_file(f"{shp_path}/land2001_by_land_id.shp")

In [15]:
shp.columns

Index(['LAND_ID', 'LAND_LOC', 'Acres', 'Shape_Leng', 'Shape_Area', 'geometry'], dtype='object')

In [16]:
crops.columns

Index(['Land_id', 'Year', 'Prdc_ID', 'Count', 'Ftilimp1', 'Ftilimp1_Type',
       'Ftilimp1CropRes', 'Ftilpas1', 'Ftilpas1Year', 'Crop1',
       ...
       'Stilpas2', 'Seedimp', 'Seedimp_Type', 'ForSeedImp', 'CROP_NAME',
       'YearForage', 'ForageLength', 'Acres', 'Calculated_Acres', 'Hectares'],
      dtype='object', length=154)

In [27]:
crops = crops[['Land_id','Year','Crop1']]

In [28]:
crops = crops.rename(columns={"Land_id":"LAND_ID", "Crop1": "CROP"})
crops

      LAND_ID  Year  CROP
0           1  1991     1
1           1  1992    23
2           1  1993     1
3           1  1994    23
4           1  1995     1
...       ...   ...   ...
4853      351  2000   302
4854      351  2001   302
4855      351  2002   302
4856      351  2003   302
4857      351  2004   300

[4858 rows x 3 columns]

In [41]:
crops['CROP'] = crops['CROP'].astype(int)
crops.columns

Index(['LAND_ID', 'Year', 'CROP'], dtype='object')

In [36]:
merged = shp.merge(crops_2001, how='left', on='LAND_ID')
merged

,LAND_ID,LAND_LOC,Acres,Shape_Leng,Shape_Area,geometry,Year,CROP
0,1,NE 24-5-8,31.170027,1686.980681,1.261406e+05,"POLYGON ((542918.312 5472838.000, 542873.812 5...",2001.0,5.0
1,3,EH 13-5-8,9.820786,823.618457,3.974331e+04,"POLYGON ((542666.312 5471895.000, 542671.812 5...",2001.0,302.0
2,4,NE 13-5-8,8.467166,1273.229128,3.426541e+04,"POLYGON ((541595.625 5471294.000, 541608.500 5...",2001.0,302.0
3,5,EH 13-5-8,53.384368,2538.138220,2.160389e+05,"POLYGON ((542691.625 5471838.000, 542736.312 5...",2001.0,302.0
4,6,EH 13-5-9,24.962373,1516.230933,1.010191e+05,"POLYGON ((542927.188 5471753.000, 542925.812 5...",2001.0,16.0
...,...,...,...,...,...,...,...,...
335,700,None,3385.701302,268389.157690,1.370145e+07,"MULTIPOLYGON (((549513.125 5461533.000, 549518...",NaN,NaN
336,750,None,7.505741,1835.691319,3.037466e+04,"MULTIPOLYGON (((544591.125 5465102.000, 544586...",NaN,NaN
337,800,None,90.681505,25109.063883,3.669750e+05,"MULTIPOLYGON (((549488.500 5460985.000, 549476...",NaN,NaN
338,850,None,116.032710,19982.426125,4.695677e+05,"MULTIPOLYGON (((547707.812 5461712.000, 547613...",NaN,NaN
339,860,None,618.124930,162939.334549,2.501463e+06,"MULTIPOLYGON (((553918.875 5469420.000, 553918...",NaN,NaN

In [44]:
for year in years:
    shp = gpd.read_file(f"{shp_path}/land{year}_by_land_id.shp")    
    shp = shp.merge(crops[crops['Year'] == year], how='left', on='LAND_ID')    
    shp.drop(columns = 'Year')
    shp.to_file(f"{out_path}/land{year}_by_land_id.shp")