In [8]:
from whitebox_workflows import WbEnvironment
import os
import numpy as np
import pandas as pd
import math

In [ ]:
import string

# Loop through the alphabet

In [12]:
from imWEBs.database.database_base import DatabaseBase
import string

os.chdir(r"C:\Work\imWEBs\Tutorial\data\reservoir")
db = DatabaseBase(r"C:\Work\imWEBs\Tutorial\model\tutorial\database\BMP.db3")
for letter in string.ascii_uppercase:
    db.read_table(f"Fig11{letter}").to_csv(f"Fig11{letter}.csv", index=False)

In [5]:
cols = ["1","2"]
str = ", ".join(cols)
print(str)

1, 2

In [ ]:
type = int
print(type is float)

False

In [4]:
from sqlalchemy import Column, INT, TEXT, REAL

class table:
    Colume1 = Column(INT)

In [5]:
table

__main__.table

In [3]:
import pandas as pd
from sqlalchemy import create_engine, INT, TEXT, REAL

# Sample DataFrame
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35],
    'score': [88.5, 92.3, 85.7]
}
df = pd.DataFrame(data)

# Create a SQLite engine
engine = create_engine('sqlite:///example.db3')

# Specify column types
dtype = {
    'name': TEXT,
    'age': INT,
    'score': REAL
}

# Save DataFrame to SQL with specified column types
df.to_sql('people', engine, if_exists='replace', index=False, dtype=dtype)

3

In [11]:
reach_parameter_df = pd.read_csv(r"C:\Work\imWEBs\test\test_tutorial_all\watershed\output\reach_parameter.csv")

with open(r"C:\Work\imWEBs\test\test_tutorial_all\awesome\reachParameter.txt",'w') as f:
    f.writelines(f"{len(reach_parameter_df)}\n{len(reach_parameter_df.columns)}\n#")

    reach_parameter_df.to_csv(r"C:\Work\imWEBs\test\test_tutorial_all\awesome\reachParameter_temp.txt", sep = "\t", index=False)
    with open(r"C:\Work\imWEBs\test\test_tutorial_all\awesome\reachParameter_temp.txt",'r') as f_temp:
        f.write(f_temp.read())

    #df_string = ' '.join(df_string.split())
    #f.writelines(df_string)

In [7]:
id_subbasin_dict = {1:1,2:2}
df_field_subbasin_lookup = pd.DataFrame(list(id_subbasin_dict.items()),columns=["Location","SourceID"])
df_field_subbasin_lookup

   Location  SourceID
0         1         1
1         2         2

In [6]:
id_subbasin_dict

{1: 1, 2: 2}

In [2]:
for y in range(10,12+1):
    print(y)

10
11
12

In [3]:
df = pd.DataFrame(index=range(1, 101))
df['order'] = 1
df.head()

   order
1      1
2      1
3      1
4      1
5      1

In [8]:
flag2D = np.zeros((2, 2), dtype=bool)
flag2D

array([[False, False],
       [False, False]])

In [10]:
math.log(2)

0.6931471805599453

In [6]:
class bmp_base:
    def __init__(self):
        self.ID = -1       
        self.BMP = ""

class BMP_scenarios(bmp_base):
    def __init__(self):
        super().__init__()
        self.DISTRIBUTION = ""
        self.PARAMETER = ""
        self.NAME = "scenario"

bmps = [BMP_scenarios() for type in ["",""]]
df = pd.DataFrame([vars(rb) for rb in bmps])
df.head(5)

   ID BMP DISTRIBUTION PARAMETER      NAME
0  -1                             scenario
1  -1                             scenario

In [2]:
wbe = WbEnvironment()

In [2]:
ln_of_2 = np.log(2)
ln_of_2

0.6931471805599453

In [4]:
list1 = [1,2]
list2 = [1,2, 3]

print(np.array_equal(list1, list2))

False

In [8]:
import pandas as pd

# Create a dictionary with some data
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [9]:
df[df.columns[-1]].to_list()

['New York', 'Los Angeles', 'Chicago']

In [7]:
os.chdir(r"C:\Work\imWEBs\Tutorial\data")

dem_raster = wbe.read_raster("dem.tif")
wetland_polygon_vector = wbe.read_vector("wetlands.shp")
wetland_point_vector = wbe.read_vector("WetlandsVertices.shp")

wetland_polygon_raster = wbe.vector_polygons_to_raster(input = wetland_polygon_vector, field_name="ID", base_raster=dem_raster)
wbe.write_raster(wetland_polygon_raster, "wetlands_polygon.tif")

wetland_point_raster = wbe.vector_points_to_raster(input = wetland_point_vector, field_name="ID", base_raster=dem_raster)
wbe.write_raster(wetland_polygon_raster, "wetlands_point.tif")

In [5]:
wbe = WbEnvironment()

os.chdir(r"C:\Work\imWEBs\test\test_tutoriral_whitebox\Project\watershed\Output")
wbe = WbEnvironment()
flow_dir_whitebox_raster = wbe.read_raster("flow_dir.tif")
flow_dir_python_raster = wbe.read_raster(r"C:\Work\imWEBs\test\test_tutoriral_whitebox\backup\test\flow_dir_test.tif")

rows = flow_dir_whitebox_raster.configs.rows
cols = flow_dir_whitebox_raster.configs.columns
equal_count = 0
not_eualt_coult = 0
for row in range(rows):
    for col in range(cols):
        white_box = flow_dir_whitebox_raster[row, col]
        python = flow_dir_python_raster[row,col]

        if white_box == python:
            equal_count = equal_count + 1
        else:
            print(f"Row: {row}, Col: {col}, Whitebox: {white_box}, Pytho: {python}")
            not_eualt_coult = not_eualt_coult + 1

print(f'Equal Count = {equal_count}')
print(not_eualt_coult)

Row: 26, Col: 58, Whitebox: 2.0, Pytho: 4.0
Row: 29, Col: 77, Whitebox: 1.0, Pytho: 128.0
Row: 31, Col: 78, Whitebox: 1.0, Pytho: 4.0
Row: 34, Col: 79, Whitebox: 1.0, Pytho: 128.0
Row: 34, Col: 80, Whitebox: 128.0, Pytho: 64.0
Row: 35, Col: 128, Whitebox: 128.0, Pytho: 2.0
Row: 46, Col: 89, Whitebox: 2.0, Pytho: 4.0
Row: 52, Col: 87, Whitebox: 64.0, Pytho: 2.0
Row: 71, Col: 126, Whitebox: 64.0, Pytho: 8.0
Row: 74, Col: 59, Whitebox: 32.0, Pytho: 64.0
Row: 74, Col: 67, Whitebox: 1.0, Pytho: 2.0
Row: 74, Col: 150, Whitebox: 4.0, Pytho: 1.0
Row: 79, Col: 19, Whitebox: 4.0, Pytho: 2.0
Row: 80, Col: 19, Whitebox: 2.0, Pytho: 1.0
Row: 80, Col: 22, Whitebox: 2.0, Pytho: 4.0
Row: 80, Col: 160, Whitebox: 4.0, Pytho: 2.0
Row: 81, Col: 22, Whitebox: 1.0, Pytho: 2.0
Row: 84, Col: 56, Whitebox: 64.0, Pytho: 32.0
Row: 85, Col: 55, Whitebox: 64.0, Pytho: 128.0
Row: 85, Col: 125, Whitebox: 32.0, Pytho: 16.0
Row: 101, Col: 161, Whitebox: 1.0, Pytho: 4.0
Row: 103, Col: 188, Whitebox: 64.0, Pytho: 32.0
Row: 105, Col: 146, Whitebox: 8.0, Pytho: 4.0
Row: 105, Col: 147, Whitebox: 16.0, Pytho: 8.0
Row: 106, Col: 111, Whitebox: 1.0, Pytho: 128.0
Row: 108, Col: 104, Whitebox: 64.0, Pytho: 1.0
Row: 114, Col: 190, Whitebox: 32.0, Pytho: 16.0
Row: 115, Col: 190, Whitebox: 64.0, Pytho: 32.0
Row: 116, Col: 150, Whitebox: 64.0, Pytho: 32.0
Row: 117, Col: 176, Whitebox: 1.0, Pytho: 128.0
Row: 120, Col: 70, Whitebox: 64.0, Pytho: 2.0
Row: 123, Col: 163, Whitebox: 4.0, Pytho: 2.0
Row: 126, Col: 123, Whitebox: 1.0, Pytho: 128.0
Row: 126, Col: 124, Whitebox: 128.0, Pytho: 64.0
Row: 126, Col: 158, Whitebox: 16.0, Pytho: 32.0
Row: 127, Col: 158, Whitebox: 32.0, Pytho: 64.0
Row: 127, Col: 175, Whitebox: 4.0, Pytho: 2.0
Row: 129, Col: 11, Whitebox: 64.0, Pytho: 2.0
Row: 129, Col: 77, Whitebox: 4.0, Pytho: 8.0
Row: 129, Col: 78, Whitebox: 8.0, Pytho: 16.0
Row: 136, Col: 78, Whitebox: 16.0, Pytho: 4.0
Row: 137, Col: 124, Whitebox: 4.0, Pytho: 2.0
Row: 138, Col: 124, Whitebox: 2.0, Pytho: 1.0
Row: 138, Col: 136, Whitebox: 2.0, Pytho: 128.0
Row: 140, Col: 71, Whitebox: 1.0, Pytho: 4.0
Row: 140, Col: 399, Whitebox: 4.0, Pytho: 8.0
Row: 140, Col: 400, Whitebox: 8.0, Pytho: 16.0
Row: 142, Col: 109, Whitebox: 16.0, Pytho: 32.0
Row: 143, Col: 387, Whitebox: 4.0, Pytho: 2.0
Row: 144, Col: 89, Whitebox: 2.0, Pytho: 32.0
Row: 144, Col: 387, Whitebox: 2.0, Pytho: 1.0
Row: 145, Col: 126, Whitebox: 1.0, Pytho: 2.0
Row: 147, Col: 363, Whitebox: 4.0, Pytho: 2.0
Row: 148, Col: 363, Whitebox: 2.0, Pytho: 1.0
Row: 149, Col: 363, Whitebox: 1.0, Pytho: 4.0
Row: 149, Col: 438, Whitebox: 4.0, Pytho: 1.0
Row: 150, Col: 332, Whitebox: 2.0, Pytho: 1.0
Row: 153, Col: 322, Whitebox: 1.0, Pytho: 2.0
Row: 153, Col: 391, Whitebox: 128.0, Pytho: 4.0
Row: 155, Col: 325, Whitebox: 2.0, Pytho: 128.0
Row: 156, Col: 357, Whitebox: 2.0, Pytho: 1.0
Row: 159, Col: 38, Whitebox: 1.0, Pytho: 4.0
Row: 160, Col: 44, Whitebox: 4.0, Pytho: 1.0
Row: 160, Col: 179, Whitebox: 2.0, Pytho: 1.0
Row: 161, Col: 349, Whitebox: 4.0, Pytho: 1.0
Row: 161, Col: 407, Whitebox: 4.0, Pytho: 1.0
Row: 162, Col: 79, Whitebox: 1.0, Pytho: 4.0
Row: 162, Col: 400, Whitebox: 2.0, Pytho: 1.0
Row: 163, Col: 327, Whitebox: 1.0, Pytho: 2.0
Row: 164, Col: 258, Whitebox: 2.0, Pytho: 4.0
Row: 164, Col: 326, Whitebox: 1.0, Pytho: 2.0
Row: 165, Col: 258, Whitebox: 1.0, Pytho: 2.0
Row: 165, Col: 361, Whitebox: 1.0, Pytho: 4.0
Row: 166, Col: 347, Whitebox: 1.0, Pytho: 4.0
Row: 173, Col: 232, Whitebox: 64.0, Pytho: 1.0
Row: 173, Col: 335, Whitebox: 2.0, Pytho: 4.0
Row: 174, Col: 319, Whitebox: 4.0, Pytho: 2.0
Row: 175, Col: 319, Whitebox: 2.0, Pytho: 1.0
Row: 177, Col: 392, Whitebox: 4.0, Pytho: 2.0
Row: 178, Col: 319, Whitebox: 1.0, Pytho: 4.0
Row: 178, Col: 327, Whitebox: 2.0, Pytho: 4.0
Row: 179, Col: 97, Whitebox: 2.0, Pytho: 4.0
Row: 179, Col: 319, Whitebox: 1.0, Pytho: 2.0
Row: 179, Col: 327, Whitebox: 1.0, Pytho: 2.0
Row: 180, Col: 97, Whitebox: 1.0, Pytho: 2.0
Row: 181, Col: 389, Whitebox: 16.0, Pytho: 4.0
Row: 181, Col: 422, Whitebox: 2.0, Pytho: 1.0
Row: 182, Col: 393, Whitebox: 1.0, Pytho: 4.0
Row: 184, Col: 399, Whitebox: 4.0, Pytho: 2.0
Row: 185, Col: 399, Whitebox: 2.0, Pytho: 1.0
Row: 189, Col: 175, Whitebox: 1.0, Pytho: 128.0
Row: 189, Col: 311, Whitebox: 1.0, Pytho: 4.0
Row: 196, Col: 295, Whitebox: 4.0, Pytho: 2.0
Row: 201, Col: 294, Whitebox: 4.0, Pytho: 2.0
Row: 204, Col: 340, Whitebox: 2.0, Pytho: 4.0
Row: 204, Col: 391, Whitebox: 1.0, Pytho: 4.0
Row: 205, Col: 311, Whitebox: 1.0, Pytho: 2.0
Row: 205, Col: 340, Whitebox: 1.0, Pytho: 2.0
Row: 208, Col: 105, Whitebox: 1.0, Pytho: 2.0
Row: 210, Col: 213, Whitebox: 128.0, Pytho: 1.0
Row: 210, Col: 398, Whitebox: 2.0, Pytho: 1.0
Row: 212, Col: 323, Whitebox: 4.0, Pytho: 2.0
Row: 216, Col: 139, Whitebox: 2.0, Pytho: 4.0
Row: 222, Col: 321, Whitebox: 1.0, Pytho: 2.0
Row: 223, Col: 91, Whitebox: 128.0, Pytho: 1.0
Row: 223, Col: 92, Whitebox: 64.0, Pytho: 128.0
Row: 225, Col: 145, Whitebox: 1.0, Pytho: 128.0
Row: 225, Col: 146, Whitebox: 128.0, Pytho: 64.0
Row: 241, Col: 199, Whitebox: 32.0, Pytho: 16.0
Row: 257, Col: 106, Whitebox: 4.0, Pytho: 1.0
Row: 259, Col: 147, Whitebox: 64.0, Pytho: 1.0
Row: 263, Col: 193, Whitebox: 2.0, Pytho: 4.0
Row: 264, Col: 193, Whitebox: 1.0, Pytho: 2.0
Row: 268, Col: 224, Whitebox: 8.0, Pytho: 4.0
Row: 268, Col: 225, Whitebox: 16.0, Pytho: 8.0
Row: 269, Col: 224, Whitebox: 16.0, Pytho: 4.0
Row: 269, Col: 225, Whitebox: 4.0, Pytho: 8.0
Row: 270, Col: 225, Whitebox: 4.0, Pytho: 8.0
Row: 270, Col: 226, Whitebox: 4.0, Pytho: 16.0
Row: 270, Col: 227, Whitebox: 8.0, Pytho: 16.0
Row: 271, Col: 176, Whitebox: 4.0, Pytho: 1.0
Row: 271, Col: 224, Whitebox: 8.0, Pytho: 4.0
Row: 271, Col: 225, Whitebox: 16.0, Pytho: 8.0
Row: 272, Col: 220, Whitebox: 4.0, Pytho: 2.0
Row: 272, Col: 222, Whitebox: 4.0, Pytho: 2.0
Row: 272, Col: 223, Whitebox: 2.0, Pytho: 4.0
Row: 272, Col: 225, Whitebox: 8.0, Pytho: 4.0
Row: 272, Col: 226, Whitebox: 4.0, Pytho: 8.0
Row: 272, Col: 227, Whitebox: 8.0, Pytho: 16.0
Row: 273, Col: 220, Whitebox: 2.0, Pytho: 1.0
Row: 273, Col: 221, Whitebox: 4.0, Pytho: 1.0
Row: 273, Col: 222, Whitebox: 4.0, Pytho: 1.0
Row: 273, Col: 223, Whitebox: 1.0, Pytho: 4.0
Row: 274, Col: 221, Whitebox: 2.0, Pytho: 4.0
Row: 274, Col: 222, Whitebox: 2.0, Pytho: 4.0
Row: 274, Col: 223, Whitebox: 1.0, Pytho: 4.0
Row: 275, Col: 221, Whitebox: 1.0, Pytho: 4.0
Row: 275, Col: 223, Whitebox: 1.0, Pytho: 4.0
Row: 276, Col: 220, Whitebox: 4.0, Pytho: 2.0
Row: 276, Col: 221, Whitebox: 1.0, Pytho: 2.0
Row: 276, Col: 222, Whitebox: 2.0, Pytho: 4.0
Row: 276, Col: 223, Whitebox: 1.0, Pytho: 4.0
Row: 277, Col: 220, Whitebox: 2.0, Pytho: 1.0
Row: 277, Col: 221, Whitebox: 2.0, Pytho: 1.0
Row: 277, Col: 222, Whitebox: 1.0, Pytho: 2.0
Row: 278, Col: 220, Whitebox: 1.0, Pytho: 4.0
Row: 278, Col: 221, Whitebox: 4.0, Pytho: 1.0
Row: 278, Col: 223, Whitebox: 4.0, Pytho: 2.0
Row: 279, Col: 217, Whitebox: 4.0, Pytho: 2.0
Row: 279, Col: 219, Whitebox: 4.0, Pytho: 2.0
Row: 279, Col: 220, Whitebox: 4.0, Pytho: 2.0
Row: 279, Col: 221, Whitebox: 2.0, Pytho: 4.0
Row: 279, Col: 223, Whitebox: 4.0, Pytho: 1.0
Row: 280, Col: 218, Whitebox: 4.0, Pytho: 2.0
Row: 280, Col: 219, Whitebox: 2.0, Pytho: 4.0
Row: 280, Col: 220, Whitebox: 4.0, Pytho: 1.0
Row: 280, Col: 221, Whitebox: 4.0, Pytho: 2.0
Row: 280, Col: 222, Whitebox: 4.0, Pytho: 2.0
Row: 280, Col: 223, Whitebox: 2.0, Pytho: 1.0
Row: 281, Col: 217, Whitebox: 2.0, Pytho: 4.0
Row: 281, Col: 219, Whitebox: 1.0, Pytho: 4.0
Row: 281, Col: 220, Whitebox: 2.0, Pytho: 4.0
Row: 281, Col: 221, Whitebox: 4.0, Pytho: 1.0
Row: 281, Col: 222, Whitebox: 2.0, Pytho: 1.0
Row: 281, Col: 225, Whitebox: 128.0, Pytho: 1.0
Row: 281, Col: 226, Whitebox: 64.0, Pytho: 128.0
Row: 281, Col: 227, Whitebox: 128.0, Pytho: 64.0
Row: 282, Col: 217, Whitebox: 1.0, Pytho: 2.0
Row: 282, Col: 220, Whitebox: 1.0, Pytho: 2.0
Row: 282, Col: 221, Whitebox: 2.0, Pytho: 1.0
Row: 282, Col: 224, Whitebox: 128.0, Pytho: 1.0
Row: 282, Col: 225, Whitebox: 64.0, Pytho: 1.0
Row: 282, Col: 226, Whitebox: 128.0, Pytho: 1.0
Row: 282, Col: 227, Whitebox: 64.0, Pytho: 128.0
Row: 283, Col: 220, Whitebox: 2.0, Pytho: 1.0
Row: 283, Col: 222, Whitebox: 128.0, Pytho: 1.0
Row: 283, Col: 223, Whitebox: 64.0, Pytho: 128.0
Row: 284, Col: 218, Whitebox: 2.0, Pytho: 4.0
Row: 284, Col: 224, Whitebox: 128.0, Pytho: 1.0
Row: 284, Col: 225, Whitebox: 64.0, Pytho: 128.0
Row: 284, Col: 226, Whitebox: 1.0, Pytho: 64.0
Row: 285, Col: 218, Whitebox: 1.0, Pytho: 2.0
Row: 285, Col: 221, Whitebox: 1.0, Pytho: 64.0
Row: 285, Col: 222, Whitebox: 128.0, Pytho: 1.0
Row: 285, Col: 223, Whitebox: 2.0, Pytho: 4.0
Row: 286, Col: 220, Whitebox: 1.0, Pytho: 128.0
Row: 286, Col: 221, Whitebox: 128.0, Pytho: 64.0
Row: 286, Col: 222, Whitebox: 64.0, Pytho: 2.0
Row: 286, Col: 223, Whitebox: 1.0, Pytho: 4.0
Row: 286, Col: 226, Whitebox: 8.0, Pytho: 4.0
Row: 286, Col: 227, Whitebox: 16.0, Pytho: 8.0
Row: 287, Col: 221, Whitebox: 4.0, Pytho: 2.0
Row: 287, Col: 222, Whitebox: 4.0, Pytho: 1.0
Row: 287, Col: 223, Whitebox: 4.0, Pytho: 2.0
Row: 287, Col: 224, Whitebox: 2.0, Pytho: 4.0
Row: 288, Col: 221, Whitebox: 2.0, Pytho: 1.0
Row: 288, Col: 223, Whitebox: 2.0, Pytho: 1.0
Row: 289, Col: 223, Whitebox: 1.0, Pytho: 4.0
Row: 289, Col: 224, Whitebox: 2.0, Pytho: 4.0
Row: 290, Col: 224, Whitebox: 1.0, Pytho: 4.0
Row: 290, Col: 226, Whitebox: 2.0, Pytho: 4.0
Row: 291, Col: 225, Whitebox: 2.0, Pytho: 4.0
Row: 291, Col: 226, Whitebox: 4.0, Pytho: 2.0
Row: 292, Col: 225, Whitebox: 1.0, Pytho: 2.0
Row: 292, Col: 226, Whitebox: 2.0, Pytho: 1.0
Row: 293, Col: 225, Whitebox: 2.0, Pytho: 1.0
Row: 295, Col: 90, Whitebox: 2.0, Pytho: 1.0
Row: 296, Col: 205, Whitebox: 2.0, Pytho: 4.0
Row: 313, Col: 157, Whitebox: 4.0, Pytho: 1.0
Row: 320, Col: 278, Whitebox: 32.0, Pytho: 64.0
Row: 323, Col: 179, Whitebox: 4.0, Pytho: 2.0
Row: 324, Col: 179, Whitebox: 2.0, Pytho: 1.0
Row: 324, Col: 271, Whitebox: 64.0, Pytho: 1.0
Row: 326, Col: 210, Whitebox: 128.0, Pytho: 4.0
Row: 326, Col: 211, Whitebox: 64.0, Pytho: 8.0
Row: 329, Col: 168, Whitebox: 2.0, Pytho: 1.0
Row: 336, Col: 202, Whitebox: 4.0, Pytho: 2.0
Row: 337, Col: 202, Whitebox: 2.0, Pytho: 1.0
Row: 337, Col: 240, Whitebox: 4.0, Pytho: 2.0
Row: 337, Col: 264, Whitebox: 8.0, Pytho: 4.0
Row: 337, Col: 265, Whitebox: 16.0, Pytho: 8.0
Row: 338, Col: 109, Whitebox: 1.0, Pytho: 128.0
Row: 338, Col: 181, Whitebox: 8.0, Pytho: 2.0
Row: 338, Col: 219, Whitebox: 4.0, Pytho: 1.0
Row: 342, Col: 258, Whitebox: 128.0, Pytho: 1.0
Row: 342, Col: 259, Whitebox: 64.0, Pytho: 128.0
Row: 346, Col: 230, Whitebox: 1.0, Pytho: 64.0
Row: 347, Col: 204, Whitebox: 32.0, Pytho: 16.0
Row: 348, Col: 204, Whitebox: 64.0, Pytho: 32.0
Row: 351, Col: 271, Whitebox: 1.0, Pytho: 128.0
Row: 351, Col: 272, Whitebox: 128.0, Pytho: 64.0
Row: 355, Col: 233, Whitebox: 1.0, Pytho: 2.0
Row: 355, Col: 254, Whitebox: 16.0, Pytho: 4.0
Row: 361, Col: 289, Whitebox: 4.0, Pytho: 2.0
Row: 362, Col: 289, Whitebox: 2.0, Pytho: 1.0
Row: 371, Col: 236, Whitebox: 1.0, Pytho: 2.0
Row: 372, Col: 233, Whitebox: 8.0, Pytho: 4.0
Row: 373, Col: 260, Whitebox: 1.0, Pytho: 128.0
Row: 373, Col: 261, Whitebox: 128.0, Pytho: 64.0
Row: 374, Col: 194, Whitebox: 4.0, Pytho: 8.0
Row: 374, Col: 195, Whitebox: 8.0, Pytho: 16.0
Row: 374, Col: 239, Whitebox: 2.0, Pytho: 1.0
Row: 375, Col: 202, Whitebox: 2.0, Pytho: 1.0
Row: 375, Col: 297, Whitebox: 128.0, Pytho: 64.0
Row: 384, Col: 161, Whitebox: 1.0, Pytho: 2.0
Row: 386, Col: 293, Whitebox: 16.0, Pytho: 1.0
Row: 389, Col: 248, Whitebox: 1.0, Pytho: 2.0
Row: 390, Col: 231, Whitebox: 64.0, Pytho: 128.0
Row: 391, Col: 256, Whitebox: 1.0, Pytho: 128.0
Row: 393, Col: 179, Whitebox: 2.0, Pytho: 1.0
Row: 395, Col: 215, Whitebox: 64.0, Pytho: 32.0
Row: 397, Col: 208, Whitebox: 128.0, Pytho: 1.0
Row: 397, Col: 215, Whitebox: 2.0, Pytho: 128.0
Row: 401, Col: 205, Whitebox: 1.0, Pytho: 128.0
Row: 420, Col: 272, Whitebox: 32.0, Pytho: 16.0
Row: 432, Col: 289, Whitebox: 4.0, Pytho: 2.0
Row: 433, Col: 289, Whitebox: 2.0, Pytho: 1.0
Equal Count = 196843
257

In [4]:
wbe = WbEnvironment()
flow_direction_raster = wbe.read_raster(r"C:\Work\imWEBs\test\test_tutorial_feedlot\watershed\output\flow_dir.tif")
stream_outlets_pour_points_vector = wbe.read_vector(r"C:\Work\imWEBs\test\test_tutorial_feedlot\watershed\input\outlet.shp")

raster = wbe.watershed(
                d8_pointer=flow_direction_raster, 
                pour_points=stream_outlets_pour_points_vector)
wbe.write_raster(raster, r"C:\Work\imWEBs\test\test_tutorial_feedlot\watershed\output\subbasin.tif")

In [4]:
wbe = WbEnvironment()
structure_polygon_vector = wbe.read_vector(r"C:\Work\imWEBs\test\test_tutorial\watershed\input\wetland.shp")
for index in range(structure_polygon_vector.num_records):
    points = structure_polygon_vector[index].points
    partData = structure_polygon_vector[index].parts
    print("*"*5)
    print("Points")
    for p in points:
        print(f"x = {p.x}, y={p.y}")
    print("*"*5)
    print("Parts")
    print(partData)

*****
Points
x = 545636.0, y=5471639.0
x = 545632.0, y=5471641.5
x = 545630.0, y=5471642.5
x = 545631.0, y=5471648.5
x = 545635.5, y=5471663.0
x = 545644.5, y=5471683.5
x = 545658.0, y=5471729.0
x = 545659.5, y=5471745.0
x = 545656.0, y=5471752.5
x = 545638.0, y=5471769.5
x = 545632.0, y=5471782.0
x = 545635.0, y=5471796.0
x = 545638.5, y=5471801.0
x = 545650.0, y=5471808.5
x = 545658.0, y=5471821.0
x = 545663.5, y=5471836.5
x = 545672.0, y=5471848.5
x = 545684.0, y=5471870.5
x = 545695.0, y=5471877.5
x = 545709.0, y=5471884.5
x = 545716.0, y=5471887.0
x = 545729.0, y=5471889.5
x = 545737.5, y=5471884.0
x = 545744.5, y=5471872.0
x = 545746.5, y=5471867.0
x = 545748.0, y=5471858.0
x = 545745.5, y=5471856.5
x = 545735.0, y=5471855.0
x = 545729.5, y=5471853.0
x = 545717.5, y=5471847.5
x = 545712.5, y=5471843.5
x = 545703.0, y=5471833.0
x = 545696.5, y=5471821.5
x = 545681.0, y=5471799.5
x = 545677.5, y=5471792.0
x = 545673.5, y=5471780.0
x = 545673.5, y=5471764.0
x = 545677.0, y=5471751.0
x = 545676.5, y=5471746.5
x = 545668.0, y=5471724.0
x = 545662.5, y=5471712.5
x = 545659.0, y=5471697.0
x = 545655.5, y=5471691.5
x = 545636.0, y=5471639.0
*****
Parts
[0]
*****
Points
x = 544485.0, y=5471555.5
x = 544480.5, y=5471561.0
x = 544477.5, y=5471567.5
x = 544477.5, y=5471572.0
x = 544478.5, y=5471576.0
x = 544483.5, y=5471584.0
x = 544488.0, y=5471588.5
x = 544494.5, y=5471589.0
x = 544499.0, y=5471586.0
x = 544503.0, y=5471581.0
x = 544505.5, y=5471572.5
x = 544503.5, y=5471566.5
x = 544499.5, y=5471561.0
x = 544494.5, y=5471556.5
x = 544485.0, y=5471555.5
*****
Parts
[0]
*****
Points
x = 544335.0, y=5471462.0
x = 544328.0, y=5471462.5
x = 544320.5, y=5471466.5
x = 544315.5, y=5471473.5
x = 544314.5, y=5471481.0
x = 544325.0, y=5471495.5
x = 544327.5, y=5471496.5
x = 544331.0, y=5471494.5
x = 544332.0, y=5471482.5
x = 544335.5, y=5471473.5
x = 544337.0, y=5471468.5
x = 544337.0, y=5471463.0
x = 544335.0, y=5471462.0
*****
Parts
[0]
*****
Points
x = 544223.0, y=5471373.5
x = 544210.0, y=5471377.0
x = 544194.0, y=5471382.5
x = 544182.0, y=5471390.5
x = 544181.0, y=5471403.0
x = 544183.5, y=5471426.5
x = 544190.0, y=5471450.5
x = 544194.0, y=5471458.0
x = 544197.0, y=5471460.5
x = 544208.5, y=5471467.0
x = 544215.5, y=5471466.0
x = 544221.5, y=5471460.0
x = 544224.5, y=5471453.5
x = 544228.5, y=5471447.5
x = 544233.0, y=5471438.0
x = 544237.0, y=5471428.0
x = 544237.0, y=5471423.0
x = 544231.5, y=5471415.0
x = 544225.5, y=5471404.0
x = 544225.5, y=5471396.0
x = 544227.5, y=5471375.5
x = 544223.0, y=5471373.5
*****
Parts
[0]
*****
Points
x = 542673.5, y=5470944.0
x = 542669.5, y=5470945.5
x = 542663.0, y=5470949.0
x = 542655.5, y=5470954.5
x = 542635.0, y=5470966.0
x = 542612.0, y=5470982.5
x = 542601.5, y=5470992.5
x = 542582.5, y=5471014.0
x = 542572.0, y=5471034.5
x = 542574.5, y=5471049.5
x = 542580.5, y=5471053.0
x = 542596.5, y=5471056.5
x = 542598.5, y=5471061.0
x = 542591.0, y=5471064.5
x = 542571.5, y=5471069.0
x = 542571.5, y=5471087.0
x = 542573.0, y=5471099.0
x = 542574.0, y=5471125.0
x = 542574.0, y=5471152.0
x = 542569.0, y=5471176.5
x = 542567.0, y=5471200.0
x = 542567.0, y=5471211.5
x = 542572.0, y=5471235.0
x = 542565.5, y=5471253.5
x = 542567.5, y=5471263.0
x = 542579.5, y=5471295.0
x = 542592.5, y=5471311.0
x = 542604.5, y=5471316.0
x = 542611.0, y=5471316.0
x = 542614.0, y=5471315.0
x = 542634.0, y=5471304.0
x = 542639.5, y=5471304.0
x = 542659.0, y=5471294.5
x = 542663.5, y=5471290.5
x = 542674.0, y=5471284.0
x = 542672.5, y=5471270.5
x = 542669.0, y=5471261.0
x = 542662.5, y=5471238.5
x = 542657.5, y=5471214.5
x = 542651.5, y=5471191.0
x = 542643.5, y=5471168.5
x = 542633.0, y=5471148.5
x = 542628.0, y=5471127.0
x = 542630.0, y=5471115.5
x = 542636.5, y=5471094.0
x = 542647.0, y=5471073.5
x = 542650.5, y=5471063.0
x = 542656.5, y=5471030.5
x = 542675.0, y=5470997.0
x = 542685.0, y=5470975.0
x = 542684.0, y=5470955.5
x = 542673.5, y=5470944.0
*****
Parts
[0]
*****
Points
x = 544196.0, y=5471200.0
x = 544188.5, y=5471200.0
x = 544185.0, y=5471204.5
x = 544185.0, y=5471224.5
x = 544186.5, y=5471237.0
x = 544188.0, y=5471240.5
x = 544193.5, y=5471243.5
x = 544200.5, y=5471244.0
x = 544203.5, y=5471242.0
x = 544203.5, y=5471223.0
x = 544202.0, y=5471220.0
x = 544202.0, y=5471202.5
x = 544196.0, y=5471200.0
*****
Parts
[0]
*****
Points
x = 544678.0, y=5471061.0
x = 544671.5, y=5471065.5
x = 544676.0, y=5471076.5
x = 544673.0, y=5471099.0
x = 544679.5, y=5471112.5
x = 544682.5, y=5471126.0
x = 544671.0, y=5471138.5
x = 544665.0, y=5471149.5
x = 544663.5, y=5471165.0
x = 544657.0, y=5471175.0
x = 544666.5, y=5471179.5
x = 544670.0, y=5471177.5
x = 544678.5, y=5471171.5
x = 544689.0, y=5471151.0
x = 544708.5, y=5471121.0
x = 544715.5, y=5471105.0
x = 544715.0, y=5471090.0
x = 544709.0, y=5471076.0
x = 544698.0, y=5471067.5
x = 544687.5, y=5471065.0
x = 544688.5, y=5471063.5
x = 544686.0, y=5471062.5
x = 544678.0, y=5471061.0
*****
Parts
[0]
*****
Points
x = 542310.5, y=5471014.0
x = 542302.5, y=5471016.0
x = 542304.0, y=5471025.0
x = 542313.0, y=5471032.5
x = 542326.5, y=5471039.0
x = 542330.0, y=5471038.5
x = 542333.5, y=5471033.0
x = 542332.0, y=5471030.0
x = 542328.5, y=5471026.0
x = 542322.5, y=5471020.5
x = 542315.0, y=5471014.5
x = 542310.5, y=5471014.0
*****
Parts
[0]
*****
Points
x = 542792.5, y=5470681.0
x = 542789.5, y=5470681.0
x = 542783.5, y=5470684.5
x = 542777.5, y=5470690.0
x = 542789.0, y=5470709.0
x = 542798.5, y=5470725.0
x = 542799.5, y=5470725.5
x = 542804.5, y=5470725.5
x = 542817.0, y=5470718.5
x = 542818.0, y=5470714.0
x = 542817.5, y=5470712.0
x = 542811.5, y=5470709.0
x = 542805.0, y=5470700.5
x = 542795.0, y=5470682.5
x = 542792.5, y=5470681.0
*****
Parts
[0]
*****
Points
x = 542953.0, y=5470537.5
x = 542950.0, y=5470538.0
x = 542949.5, y=5470539.0
x = 542949.5, y=5470573.5
x = 542949.5, y=5470592.0
x = 542951.0, y=5470594.0
x = 542953.0, y=5470595.0
x = 542963.5, y=5470594.5
x = 542966.5, y=5470593.0
x = 542967.0, y=5470547.5
x = 542966.0, y=5470538.0
x = 542953.0, y=5470537.5
*****
Parts
[0]
*****
Points
x = 542334.5, y=5470544.5
x = 542329.5, y=5470545.0
x = 542309.0, y=5470550.0
x = 542308.0, y=5470556.5
x = 542307.5, y=5470578.0
x = 542317.5, y=5470579.0
x = 542323.0, y=5470582.0
x = 542328.0, y=5470585.0
x = 542345.5, y=5470588.5
x = 542354.0, y=5470583.0
x = 542362.0, y=5470573.0
x = 542366.0, y=5470565.0
x = 542366.5, y=5470557.5
x = 542365.5, y=5470555.5
x = 542361.5, y=5470553.5
x = 542354.5, y=5470548.0
x = 542350.0, y=5470546.5
x = 542345.5, y=5470546.5
x = 542334.5, y=5470544.5
*****
Parts
[0]
*****
Points
x = 541805.5, y=5470479.0
x = 541804.5, y=5470483.0
x = 541796.0, y=5470492.5
x = 541808.5, y=5470498.5
x = 541812.5, y=5470502.5
x = 541813.5, y=5470502.5
x = 541821.0, y=5470494.0
x = 541824.0, y=5470488.0
x = 541816.5, y=5470483.0
x = 541805.5, y=5470479.0
*****
Parts
[0]
*****
Points
x = 546462.0, y=5470426.0
x = 546449.5, y=5470426.5
x = 546447.0, y=5470431.0
x = 546444.5, y=5470433.5
x = 546445.0, y=5470437.0
x = 546453.0, y=5470449.5
x = 546456.0, y=5470449.0
x = 546466.5, y=5470442.5
x = 546472.0, y=5470443.5
x = 546471.5, y=5470456.5
x = 546464.5, y=5470471.5
x = 546471.5, y=5470471.5
x = 546473.5, y=5470470.0
x = 546478.0, y=5470461.0
x = 546478.5, y=5470457.5
x = 546477.0, y=5470446.0
x = 546483.5, y=5470436.0
x = 546486.5, y=5470428.0
x = 546467.0, y=5470428.5
x = 546462.0, y=5470426.0
*****
Parts
[0]
*****
Points
x = 546496.0, y=5470301.5
x = 546494.0, y=5470303.0
x = 546494.0, y=5470311.5
x = 546492.5, y=5470323.0
x = 546486.5, y=5470324.0
x = 546463.5, y=5470325.0
x = 546444.5, y=5470325.0
x = 546444.5, y=5470341.5
x = 546476.0, y=5470341.5
x = 546487.5, y=5470343.0
x = 546493.5, y=5470342.5
x = 546494.5, y=5470336.5
x = 546497.5, y=5470330.5
x = 546506.0, y=5470320.0
x = 546511.0, y=5470315.5
x = 546511.0, y=5470312.5
x = 546502.0, y=5470305.0
x = 546496.0, y=5470301.5
*****
Parts
[0]
*****
Points
x = 543058.5, y=5469883.0
x = 543037.0, y=5469883.0
x = 543017.0, y=5469889.5
x = 543012.5, y=5469893.0
x = 543011.0, y=5469896.0
x = 543006.0, y=5469900.0
x = 543006.0, y=5469909.0
x = 543007.0, y=5469911.5
x = 543007.5, y=5469918.0
x = 543008.5, y=5469919.5
x = 543016.5, y=5469920.0
x = 543019.5, y=5469918.5
x = 543031.5, y=5469919.0
x = 543038.5, y=5469917.0
x = 543051.5, y=5469916.0
x = 543060.5, y=5469913.0
x = 543064.0, y=5469911.0
x = 543066.5, y=5469907.0
x = 543066.5, y=5469891.0
x = 543065.0, y=5469887.5
x = 543063.5, y=5469886.0
x = 543058.5, y=5469883.0
*****
Parts
[0]
*****
Points
x = 541922.0, y=5469713.0
x = 541916.5, y=5469713.0
x = 541906.0, y=5469716.5
x = 541900.5, y=5469717.0
x = 541897.5, y=5469719.0
x = 541894.5, y=5469724.0
x = 541894.0, y=5469731.5
x = 541896.5, y=5469736.0
x = 541898.0, y=5469737.0
x = 541902.5, y=5469737.0
x = 541910.5, y=5469739.0
x = 541919.5, y=5469740.0
x = 541929.5, y=5469737.0
x = 541933.5, y=5469732.0
x = 541934.0, y=5469727.5
x = 541932.5, y=5469722.5
x = 541932.5, y=5469719.0
x = 541931.0, y=5469716.5
x = 541926.5, y=5469714.0
x = 541922.0, y=5469713.0
*****
Parts
[0]
*****
Points
x = 543584.5, y=5469620.0
x = 543581.5, y=5469628.5
x = 543578.5, y=5469629.0
x = 543578.5, y=5469630.5
x = 543588.0, y=5469647.0
x = 543590.5, y=5469674.0
x = 543591.5, y=5469694.5
x = 543607.0, y=5469706.5
x = 543615.0, y=5469716.0
x = 543618.0, y=5469724.5
x = 543628.0, y=5469721.5
x = 543632.0, y=5469719.5
x = 543646.0, y=5469710.0
x = 543667.5, y=5469698.0
x = 543681.0, y=5469691.5
x = 543685.0, y=5469686.5
x = 543685.5, y=5469681.5
x = 543684.5, y=5469667.5
x = 543675.5, y=5469658.0
x = 543653.5, y=5469642.5
x = 543601.5, y=5469622.5
x = 543584.5, y=5469620.0
*****
Parts
[0]
*****
Points
x = 543903.0, y=5469209.5
x = 543897.5, y=5469211.0
x = 543893.5, y=5469215.5
x = 543881.0, y=5469235.5
x = 543879.0, y=5469253.0
x = 543874.0, y=5469264.5
x = 543855.5, y=5469291.0
x = 543843.0, y=5469307.0
x = 543831.5, y=5469318.5
x = 543811.0, y=5469337.0
x = 543805.0, y=5469341.5
x = 543791.0, y=5469350.0
x = 543778.0, y=5469354.0
x = 543767.0, y=5469359.5
x = 543754.5, y=5469361.0
x = 543742.5, y=5469361.0
x = 543736.5, y=5469363.0
x = 543734.0, y=5469377.0
x = 543725.5, y=5469389.0
x = 543721.0, y=5469397.5
x = 543722.0, y=5469413.5
x = 543722.0, y=5469450.0
x = 543720.5, y=5469463.0
x = 543718.0, y=5469466.5
x = 543714.5, y=5469475.0
x = 543717.5, y=5469482.0
x = 543727.5, y=5469488.0
x = 543728.0, y=5469498.0
x = 543718.5, y=5469500.5
x = 543712.0, y=5469501.0
x = 543702.0, y=5469503.5
x = 543700.0, y=5469505.0
x = 543699.0, y=5469515.5
x = 543699.0, y=5469547.5
x = 543695.0, y=5469551.5
x = 543663.5, y=5469551.5
x = 543631.5, y=5469551.0
x = 543626.5, y=5469551.0
x = 543620.5, y=5469554.0
x = 543607.0, y=5469572.5
x = 543600.0, y=5469580.0
x = 543593.0, y=5469590.0
x = 543590.5, y=5469599.5
x = 543592.0, y=5469601.5
x = 543602.0, y=5469603.5
x = 543619.5, y=5469612.0
x = 543642.0, y=5469620.5
x = 543654.5, y=5469627.5
x = 543677.5, y=5469632.5
x = 543685.0, y=5469636.5
x = 543687.5, y=5469635.0
x = 543692.5, y=5469625.5
x = 543706.5, y=5469604.5
x = 543710.0, y=5469595.0
x = 543718.5, y=5469582.5
x = 543723.0, y=5469566.5
x = 543730.5, y=5469549.5
x = 543730.5, y=5469514.5
x = 543736.5, y=5469513.0
x = 543740.5, y=5469517.5
x = 543740.5, y=5469528.0
x = 543742.0, y=5469536.0
x = 543752.0, y=5469534.5
x = 543768.0, y=5469523.0
x = 543779.5, y=5469512.0
x = 543786.5, y=5469503.5
x = 543796.0, y=5469489.5
x = 543807.0, y=5469478.5
x = 543819.5, y=5469464.0
x = 543832.0, y=5469443.0
x = 543845.5, y=5469424.5
x = 543857.5, y=5469404.5
x = 543872.0, y=5469373.0
x = 543881.5, y=5469350.0
x = 543909.0, y=5469311.0
x = 543913.0, y=5469302.5
x = 543918.5, y=5469277.5
x = 543917.5, y=5469251.5
x = 543921.5, y=5469241.0
x = 543921.0, y=5469232.0
x = 543920.0, y=5469229.0
x = 543911.0, y=5469214.0
x = 543909.0, y=5469212.0
x = 543903.0, y=5469209.5
*****
Parts
[0]
*****
Points
x = 542230.0, y=5469444.0
x = 542226.5, y=5469446.0
x = 542225.0, y=5469449.0
x = 542222.0, y=5469461.0
x = 542222.5, y=5469478.0
x = 542225.5, y=5469500.5
x = 542223.5, y=5469507.0
x = 542219.0, y=5469509.0
x = 542220.0, y=5469519.5
x = 542227.0, y=5469527.0
x = 542234.0, y=5469530.0
x = 542241.5, y=5469530.0
x = 542244.0, y=5469530.0
x = 542251.0, y=5469528.5
x = 542257.5, y=5469523.5
x = 542257.5, y=5469517.0
x = 542253.5, y=5469492.0
x = 542241.5, y=5469469.5
x = 542234.5, y=5469448.0
x = 542232.0, y=5469444.5
x = 542230.0, y=5469444.0
*****
Parts
[0]
*****
Points
x = 543285.0, y=5469375.0
x = 543282.5, y=5469376.5
x = 543277.0, y=5469384.5
x = 543274.0, y=5469390.0
x = 543273.5, y=5469393.5
x = 543290.0, y=5469401.0
x = 543296.0, y=5469402.5
x = 543305.0, y=5469406.5
x = 543315.0, y=5469412.5
x = 543322.5, y=5469416.0
x = 543330.0, y=5469417.5
x = 543334.5, y=5469416.0
x = 543336.5, y=5469410.0
x = 543341.5, y=5469400.0
x = 543340.5, y=5469396.0
x = 543327.5, y=5469392.0
x = 543314.0, y=5469386.0
x = 543290.0, y=5469377.5
x = 543285.0, y=5469375.0
*****
Parts
[0]
*****
Points
x = 545539.0, y=5469299.5
x = 545539.0, y=5469309.5
x = 545540.0, y=5469310.5
x = 545543.5, y=5469321.0
x = 545548.5, y=5469329.5
x = 545557.0, y=5469338.0
x = 545565.0, y=5469349.0
x = 545581.0, y=5469367.0
x = 545586.5, y=5469358.0
x = 545588.0, y=5469352.5
x = 545584.0, y=5469347.5
x = 545571.5, y=5469338.0
x = 545559.5, y=5469323.0
x = 545539.0, y=5469299.5
*****
Parts
[0]
*****
Points
x = 544159.5, y=5469259.0
x = 544150.5, y=5469259.0
x = 544143.5, y=5469266.0
x = 544130.5, y=5469284.5
x = 544127.5, y=5469287.5
x = 544128.5, y=5469291.0
x = 544139.0, y=5469300.0
x = 544143.5, y=5469301.0
x = 544147.5, y=5469298.5
x = 544156.0, y=5469290.0
x = 544158.0, y=5469286.5
x = 544163.5, y=5469280.5
x = 544167.0, y=5469272.0
x = 544167.0, y=5469266.5
x = 544159.5, y=5469259.0
*****
Parts
[0]
*****
Points
x = 544168.0, y=5468789.5
x = 544163.5, y=5468789.5
x = 544149.5, y=5468794.0
x = 544141.5, y=5468798.5
x = 544134.5, y=5468807.0
x = 544118.5, y=5468817.0
x = 544109.5, y=5468826.0
x = 544090.0, y=5468850.0
x = 544077.0, y=5468860.5
x = 544061.5, y=5468874.5
x = 544060.5, y=5468887.0
x = 544077.0, y=5468904.0
x = 544093.5, y=5468913.5
x = 544094.5, y=5468912.0
x = 544096.0, y=5468888.0
x = 544104.0, y=5468880.0
x = 544113.5, y=5468888.0
x = 544119.5, y=5468901.0
x = 544137.0, y=5468899.0
x = 544149.0, y=5468885.0
x = 544151.0, y=5468868.5
x = 544134.0, y=5468852.5
x = 544135.5, y=5468845.5
x = 544160.0, y=5468835.0
x = 544165.5, y=5468834.0
x = 544181.5, y=5468837.0
x = 544189.5, y=5468843.0
x = 544202.0, y=5468855.0
x = 544210.0, y=5468876.0
x = 544210.5, y=5468892.5
x = 544202.0, y=5468913.0
x = 544196.0, y=5468921.5
x = 544194.0, y=5468973.5
x = 544198.0, y=5468979.5
x = 544201.5, y=5468979.0
x = 544214.5, y=5468972.0
x = 544228.5, y=5468973.0
x = 544236.5, y=5468981.0
x = 544239.5, y=5468990.0
x = 544234.5, y=5468996.5
x = 544217.0, y=5469001.5
x = 544196.5, y=5469012.5
x = 544190.0, y=5469028.0
x = 544188.5, y=5469042.5
x = 544189.0, y=5469051.5
x = 544187.0, y=5469068.0
x = 544173.5, y=5469078.0
x = 544161.0, y=5469091.5
x = 544161.0, y=5469105.0
x = 544167.0, y=5469113.0
x = 544170.0, y=5469122.0
x = 544170.5, y=5469131.0
x = 544166.0, y=5469130.5
x = 544159.0, y=5469126.0
x = 544154.0, y=5469121.0
x = 544154.0, y=5469142.5
x = 544142.0, y=5469162.0
x = 544145.0, y=5469171.5
x = 544157.5, y=5469182.5
x = 544180.5, y=5469200.5
x = 544192.5, y=5469199.0
x = 544195.0, y=5469175.0
x = 544172.0, y=5469174.5
x = 544156.0, y=5469165.5
x = 544154.0, y=5469161.0
x = 544163.0, y=5469149.0
x = 544172.5, y=5469147.0
x = 544177.0, y=5469140.5
x = 544190.5, y=5469138.5
x = 544198.0, y=5469133.5
x = 544199.0, y=5469113.5
x = 544224.0, y=5469096.5
x = 544227.0, y=5469090.5
x = 544232.5, y=5469082.5
x = 544250.0, y=5469049.5
x = 544252.0, y=5469042.0
x = 544254.5, y=5469023.0
x = 544252.0, y=5469007.5
x = 544262.0, y=5469000.0
x = 544261.5, y=5468991.0
x = 544259.5, y=5468981.5
x = 544259.0, y=5468972.0
x = 544257.5, y=5468963.5
x = 544253.5, y=5468958.5
x = 544238.0, y=5468932.0
x = 544228.0, y=5468923.0
x = 544227.5, y=5468918.5
x = 544223.0, y=5468905.0
x = 544222.5, y=5468890.5
x = 544219.5, y=5468880.5
x = 544213.0, y=5468864.0
x = 544212.0, y=5468856.0
x = 544208.5, y=5468843.5
x = 544208.5, y=5468837.5
x = 544219.5, y=5468835.5
x = 544219.5, y=5468831.5
x = 544212.5, y=5468816.5
x = 544212.0, y=5468803.5
x = 544198.0, y=5468803.5
x = 544186.5, y=5468799.0
x = 544177.5, y=5468797.0
x = 544174.5, y=5468793.5
x = 544168.0, y=5468789.5
*****
Parts
[0]
*****
Points
x = 543992.0, y=5468975.5
x = 543983.5, y=5468982.0
x = 543970.5, y=5468995.5
x = 543954.0, y=5469013.5
x = 543938.5, y=5469033.5
x = 543938.5, y=5469038.0
x = 543944.0, y=5469065.5
x = 543942.5, y=5469074.5
x = 543924.0, y=5469086.0
x = 543920.5, y=5469092.0
x = 543913.5, y=5469107.0
x = 543907.0, y=5469117.5
x = 543906.0, y=5469124.5
x = 543907.5, y=5469128.0
x = 543908.5, y=5469134.0
x = 543909.0, y=5469139.5
x = 543907.5, y=5469144.0
x = 543894.0, y=5469159.0
x = 543895.0, y=5469163.5
x = 543901.5, y=5469173.5
x = 543908.5, y=5469193.0
x = 543933.0, y=5469158.0
x = 543961.0, y=5469142.5
x = 543981.5, y=5469126.5
x = 543988.5, y=5469102.0
x = 543990.0, y=5469084.5
x = 543998.0, y=5469057.5
x = 543996.5, y=5469031.5
x = 543992.0, y=5469011.0
x = 543992.0, y=5468975.5
*****
Parts
[0]
*****
Points
x = 543075.0, y=5468844.0
x = 543069.0, y=5468859.0
x = 543066.0, y=5468864.0
x = 543058.0, y=5468864.0
x = 543056.5, y=5468865.5
x = 543060.0, y=5468868.0
x = 543067.0, y=5468876.0
x = 543076.0, y=5468891.5
x = 543084.0, y=5468900.5
x = 543088.5, y=5468908.5
x = 543096.0, y=5468915.5
x = 543097.0, y=5468914.0
x = 543099.0, y=5468905.5
x = 543100.0, y=5468904.5
x = 543103.0, y=5468895.5
x = 543105.0, y=5468894.0
x = 543108.5, y=5468877.5
x = 543108.5, y=5468872.5
x = 543099.0, y=5468869.0
x = 543084.5, y=5468859.5
x = 543079.0, y=5468853.5
x = 543075.0, y=5468844.0
*****
Parts
[0]
*****
Points
x = 542980.0, y=5468657.0
x = 542968.5, y=5468659.0
x = 542959.5, y=5468658.0
x = 542958.5, y=5468659.0
x = 542958.5, y=5468660.0
x = 542968.5, y=5468667.5
x = 542975.5, y=5468669.5
x = 543003.0, y=5468687.0
x = 543006.5, y=5468690.5
x = 543015.5, y=5468702.5
x = 543020.5, y=5468713.0
x = 543022.5, y=5468719.0
x = 543026.5, y=5468722.0
x = 543053.5, y=5468721.0
x = 543052.5, y=5468716.0
x = 543048.5, y=5468709.5
x = 543044.5, y=5468700.5
x = 543037.5, y=5468691.0
x = 543024.0, y=5468678.0
x = 543020.5, y=5468676.0
x = 543009.0, y=5468673.0
x = 542997.0, y=5468668.0
x = 542992.0, y=5468664.0
x = 542980.0, y=5468657.0
*****
Parts
[0]
*****
Points
x = 545066.5, y=5468655.5
x = 545057.0, y=5468658.5
x = 545051.0, y=5468662.5
x = 545026.0, y=5468684.5
x = 545025.0, y=5468689.5
x = 545025.0, y=5468700.5
x = 545030.0, y=5468703.0
x = 545081.5, y=5468701.0
x = 545084.0, y=5468698.0
x = 545086.0, y=5468693.5
x = 545087.5, y=5468688.0
x = 545087.5, y=5468684.0
x = 545080.5, y=5468663.0
x = 545076.0, y=5468658.0
x = 545066.5, y=5468655.5
*****
Parts
[0]
*****
Points
x = 547354.5, y=5468607.0
x = 547352.5, y=5468607.5
x = 547346.0, y=5468614.5
x = 547337.5, y=5468618.0
x = 547333.5, y=5468618.5
x = 547328.0, y=5468628.5
x = 547324.0, y=5468632.0
x = 547316.0, y=5468636.5
x = 547306.0, y=5468637.5
x = 547282.5, y=5468636.0
x = 547292.0, y=5468642.0
x = 547301.5, y=5468643.5
x = 547323.5, y=5468643.5
x = 547323.5, y=5468649.0
x = 547332.0, y=5468653.0
x = 547344.5, y=5468652.5
x = 547353.0, y=5468654.5
x = 547357.0, y=5468660.0
x = 547360.5, y=5468668.5
x = 547368.0, y=5468668.5
x = 547368.0, y=5468664.5
x = 547363.0, y=5468641.5
x = 547361.5, y=5468617.0
x = 547360.0, y=5468611.0
x = 547354.5, y=5468607.0
*****
Parts
[0]
*****
Points
x = 544501.5, y=5468567.5
x = 544493.5, y=5468567.5
x = 544490.0, y=5468571.0
x = 544484.0, y=5468594.5
x = 544484.0, y=5468607.0
x = 544485.5, y=5468629.0
x = 544487.5, y=5468630.5
x = 544491.5, y=5468633.0
x = 544515.0, y=5468632.0
x = 544528.5, y=5468623.5
x = 544531.0, y=5468615.0
x = 544535.0, y=5468594.0
x = 544532.5, y=5468588.0

In [10]:
wbe = WbEnvironment()
structure_polygon_vector = wbe.read_vector(r"C:\Work\imWEBs\test\test_tutorial\watershed\input\wetland.shp")
dem_raster = wbe.read_raster(r"C:\Work\imWEBs\test\test_tutorial\watershed\input\dem.tif")
raster = wbe.vector_polygons_to_raster(structure_polygon_vector, 
        base_raster = dem_raster, 
        field_name = "ID")

In [9]:
os.chdir(r'C:\Work\imWEBs\test\test_tutorial\watershed\output')
wbe = WbEnvironment()
flow_dir_raster = wbe.read_raster("flow_dir.tif")
flow_dir_no_change_raster = wbe.read_raster("flow_dir_no_change.tif")

diff_raster = flow_dir_raster - flow_dir_no_change_raster
#diff_raster = diff_raster.con("value == 0", flow_dir_raster.configs.nodata, flow_dir_raster)
wbe.write_raster(diff_raster, "flow_dir_diff.tif")

In [6]:
os.chdir(r'C:\Work\imWEBs\Tutorial\model\tutorial\Watershed\Output\tif')
wbe = WbEnvironment()
dem_raster = wbe.read_raster("dem_mdfy.tif")
dem_burned_raster = wbe.read_raster("dem_mdfy_streamburned.tif")

diff_raster = dem_raster - dem_burned_raster
diff_raster = diff_raster.con("value == 0", dem_raster.configs.nodata, diff_raster)
wbe.write_raster(diff_raster, "dem_mdfy_streamburned_lowerd.tif")

In [1]:
import pandas as pd

In [34]:
bmp_names_df = pd.read_csv(r"C:\Work\imWEBs\Interface\bmp_definition.csv", index_col=0)
bmp_names_df.head()

,Name,Type,CODE,IsStructure,IsLandManagement,IsLivestock,IsReach,IsDate,IsAnnual,DateNumber,ParameterTable,ManagementTable,SelectionTable,AllItemTable,PossibleNames,TreeName
ID,,,,,,,,,,,,,,,,
1,Point source,1,PTSR,1,0,0,0,0,0,0,PTSR_Parameter,PTSR_management,PTSR_selection,PTSR_management_dist,"PTSR,PTSRs,Pointsource,Point_source,Point source",Point.Src
2,Stream flow diversion,1,SFDV,1,0,0,1,0,0,0,SFDV_Parameter,SFDV_management,SFDV_selection,SFDV_management_dist,"SFDV,SFDVs,Streamflowdiversion,Stream_flow_div...",Stream.Diversion
3,Reservoir,1,RESV,1,0,0,1,0,0,0,Reservoir,Reservoir,Reservoir_Management,Reservoir,"RESV,RESVs,Reservoir,Reservoir",Reservoir
4,Riparian wetland,1,RIWET,1,0,0,1,0,0,0,wetland_Parameter,wetland_Parameter,Wetland_Management,wetland_Parameter,"RIWET,RIWETs,Riparianwetland,Riparian_wetland,...",Ripa.Wetland
5,Riparian buffer,2,RIBUF,1,0,1,0,0,0,0,RipaBuffer_VegeFilter_parameter,RipaBuffer_management,RipaBuffer_selection,RipaBuffer_management,"RIBUF,RIBUFs,RiparianBufferstrip,Riparian_Buff...",Riparian buffer

In [46]:
bmp = bmp_names_df[bmp_names_df["ParameterTable"].str.lower() == "PTSR_Parameter".lower()]
bmp

,Name,Type,CODE,IsStructure,IsLandManagement,IsLivestock,IsReach,IsDate,IsAnnual,DateNumber,ParameterTable,ManagementTable,SelectionTable,AllItemTable,PossibleNames,TreeName
ID,,,,,,,,,,,,,,,,
1,Point source,1,PTSR,1,0,0,0,0,0,0,PTSR_Parameter,PTSR_management,PTSR_selection,PTSR_management_dist,"PTSR,PTSRs,Pointsource,Point_source,Point source",Point.Src

In [48]:
bmp = bmp.loc[bmp.index[-1]]
bmp

Name                                                    Point source
Type                                                               1
CODE                                                            PTSR
IsStructure                                                        1
IsLandManagement                                                   0
IsLivestock                                                        0
IsReach                                                            0
IsDate                                                             0
IsAnnual                                                           0
DateNumber                                                         0
ParameterTable                                        PTSR_Parameter
ManagementTable                                      PTSR_management
SelectionTable                                        PTSR_selection
AllItemTable                                    PTSR_management_dist
PossibleNames       PTSR,PTSRs,Pointsource,Point_source,Point source
TreeName                                                   Point.Src
Name: 1, dtype: object

In [58]:
def find_bmp(tablename:str):
    bmp = bmp_names_df[bmp_names_df["ParameterTable"].str.lower() == tablename.lower()]
    if len(bmp) > 0:
        bmp_id = bmp.index[-1]
        bmp = bmp.loc[bmp.index[-1]]
        return f'\t"""Parameter Table for BMP: {bmp.Name} ({bmp_id})"""'
    
    bmp = bmp_names_df[bmp_names_df["ManagementTable"].str.lower() == tablename.lower()]
    if len(bmp) > 0:
        bmp_id = bmp.index[-1]
        bmp = bmp.loc[bmp.index[-1]]
        return f'\t"""Distribution Table for BMP: {bmp.Name} ({bmp_id})"""'
    
    bmp = bmp_names_df[bmp_names_df["AllItemTable"].str.lower() == tablename.lower()]
    if len(bmp) > 0:
        bmp_id = bmp.index[-1]
        bmp = bmp.loc[bmp.index[-1]]
        return f'\t"""Distribution Table for BMP: {bmp.Name} ({bmp_id})"""'
    
    return None

In [52]:
find_bmp("PTSR_Parameter")

'\t"""Parameter Table for BMP Point source with id 1"""'

In [18]:
bmp_def_df = pd.read_csv(r"C:\Work\imWEBs\Interface\bmp_db_structure.csv")
bmp_def_df.head()

,TableID,TableName,ColumnID,ColumnName,ColumnType,Description,DefaultValue,IsDate,IsSelector,SelectRange,IsLinkFile,IsEditable
0,1,BMP_scenarios,1,ID,TEXT,-,0.0,0.0,0.0,NaN,0.0,0.0
1,1,BMP_scenarios,2,NAME,TEXT,-,0.0,0.0,0.0,NaN,0.0,0.0
2,1,BMP_scenarios,3,BMP,TEXT,-,0.0,0.0,0.0,NaN,0.0,0.0
3,1,BMP_scenarios,4,DISTRIBUTION,TEXT,-,0.0,0.0,0.0,NaN,0.0,0.0
4,1,BMP_scenarios,5,PARAMETER,TEXT,-,0.0,0.0,0.0,NaN,0.0,0.0

In [19]:
group = bmp_def_df.groupby("TableName")
group

In [61]:
for g in group:
    print("\n\n")
    table_name = g[0]
    table_def = g[1]
    print(f"class {table_name}(BMPTable):")    

    count = 0
    for index in table_def.index:
        if count == 0:
            table_name = table_def.loc[index, "TableName"]
            class_description = find_bmp(table_name)
            if class_description is not None:
                print(class_description)
            print(f"\t__tablename__ = '{table_name}'")
        count = count + 1


        description = table_def.loc[index, "Description"]
        if len(str(description)) > 1:
            print(f'\t"""{description}"""')

        name = table_def.loc[index, "ColumnName"]
        type = table_def.loc[index, "ColumnType"]

        if str(type).lower() == "int":
            type = "Integer"
        elif str(type).lower() == "text":
            type = "String"
        elif str(type).lower() == "real":
            type = "Float"
        elif str(type).lower() == "double":
            type = "Double"
        
        print(f"\t{name} = Column({type})")

class ASNL_management(BMPTable):
	"""Distribution Table for BMP: Application based on soil nitrogen limit (25)"""
	__tablename__ = 'ASNL_management'
	Scenario = Column(Integer)
	Location = Column(Integer)
	NO3_N_Limit_kg_ha = Column(Double)
	SELECTION = Column(Integer)



class ASNL_management_dist(BMPTable):
	"""Distribution Table for BMP: Application based on soil nitrogen limit (25)"""
	__tablename__ = 'ASNL_management_dist'
	Scenario = Column(Integer)
	Location = Column(Integer)
	NO3_N_Limit_kg_ha = Column(Double)
	SELECTION = Column(Integer)



class ASPL_management(BMPTable):
	"""Distribution Table for BMP: Application based on soil phosphorous limit (26)"""
	__tablename__ = 'ASPL_management'
	Scenario = Column(Integer)
	Location = Column(Integer)
	Soil_P_Limit_kg_ha = Column(Double)
	SELECTION = Column(Integer)



class ASPL_management_dist(BMPTable):
	"""Distribution Table for BMP: Application based on soil phosphorous limit (26)"""
	__tablename__ = 'ASPL_management_dist'
	Scenario = Column(Integer)
	Location = Column(Integer)
	Soil_P_Limit_kg_ha = Column(Double)
	SELECTION = Column(Integer)



class BMP_index(BMPTable):
	__tablename__ = 'BMP_index'
	ID = Column(Integer)
	Name = Column(String)
	Type = Column(Integer)
	CODE = Column(String)



class BMP_scenarios(BMPTable):
	__tablename__ = 'BMP_scenarios'
	ID = Column(String)
	NAME = Column(String)
	BMP = Column(String)
	DISTRIBUTION = Column(String)
	PARAMETER = Column(String)



class DGOT_parameter(BMPTable):
	"""Parameter Table for BMP: Dugout (38)"""
	__tablename__ = 'DGOT_parameter'
	"""Scenario ID"""
	Scenario = Column(Integer)
	"""Dugout ID, obtained from dugout input data"""
	ID = Column(Integer)
	"""Dugout type, 0 – filled with runoff, 1 – connected to a water course"""
	Type = Column(Integer)
	"""Operation starting year (designed for setting up dugout scenarios)"""
	Year = Column(Integer)
	"""Subbasin number, obtained from the watershed delineation"""
	Subbasin = Column(Integer)
	"""Length of dugout when filled (m)"""
	MaxL_m = Column(Double)
	"""Width of dugout when filled (m)"""
	MaxW_m = Column(Double)
	"""Dugout depth when filled (m)"""
	MaxD_m = Column(Double)
	"""Dugout side slope (-)"""
	SideSlope = Column(Double)
	"""Dugout end slope (-)"""
	EndSlope = Column(Double)
	"""Dugout volume capacity (104m3), calculated from above 4 parameters"""
	MaxVolume_104M3 = Column(Double)
	"""Dugout drainage area (ha), obtained from dugout drainage area distribution"""
	Drainage_Area = Column(Double)
	"""Animal ID"""
	AniID = Column(Integer)
	"""Adult animal number"""
	AniAdult = Column(Integer)
	"""Non-adult animal number"""
	AniNonAdult = Column(Integer)
	"""Normal (equilibrium) sediment concentration in wetland (mg/l)"""
	NSED = Column(Double)
	"""Sediment settling decay constant (1/day)"""
	Dcc = Column(Double)
	"""Median partical size"""
	D50 = Column(Double)
	"""Phosphorous settling rate in catch basin (m/year)"""
	SettVolP_mYr = Column(Double)
	"""Nitrogen settling rate in catch basin (m/year)"""
	SettVolN_mYr = Column(Double)
	"""Hydraulic conductivity of catch basin bottom (mm/hr)"""
	K_mmHr = Column(Double)
	"""Chlorophyll production coefficient of catch basin"""
	CHLAR = Column(Double)
	"""Water clarity coefficient of catch basin (m)"""
	SECCIR = Column(Double)
	"""Initial water volume in catch basin (% of capacity),"""
	InitialVolume = Column(Double)
	"""Initial sediment concentration in catch basin (mg/l)"""
	InitialSediment_mgL = Column(Double)
	"""Initial concentration of NO3-N in catch basin (mg/l)"""
	InitialNO3_mgL = Column(Double)
	"""Initial concentration of soluble P in catch basin (mg/l)"""
	InitialSolP_mgL = Column(Double)
	"""Initial concentration of organic N in catch basin (mg/l)"""
	InitialOrgN_mgL = Column(Double)
	"""Initial concentration of organic P in catch basin (mg/l)"""
	InitialOrgP_mgL = Column(Double)
	SELECTION = Column(Integer)



class DGOT_selection(BMPTable):
	__tablename__ = 'DGOT_selection'
	ID = Column(Integer)



class FDLT_Design(BMPTable):
	__tablename__ = 'FDLT_Design'
	ID = Column(Integer)



class FDLT_Parameter(BMPTable):
	"""Parameter Table for BMP: Manure feedlot (29)"""
	__tablename__ = 'FDLT_Parameter'
	"""ID"""
	ID = Column(Integer)
	"""Name"""
	Name = Column(Integer)
	"""Description"""
	Description = Column(Integer)
	"""Producer ID. Not used in the module"""
	ProducerID = Column(Integer)
	"""Subbasin. Not used in the module"""
	Subbasin = Column(Integer)
	"""The id of animal whose parameter could be found in livestok_parameter table"""
	AniID = Column(Integer)
	"""The id of catch basin which the feedlot would drains to."""
	CatBasID = Column(Integer)
	"""Initial manure storage of the feedlot"""
	ManInitial = Column(Double)
	"""Average CN increase fraction compare to non-feedlot area"""
	CN_change = Column(Double)
	"""Average PRC increase fraction compare to non-feedlot area"""
	PRC_change = Column(Double)
	"""Manure event mean concentration"""
	Manure_EMC = Column(Double)
	"""SELECTION"""
	SELECTION = Column(Integer)



class FDLT_management(BMPTable):
	"""Distribution Table for BMP: Manure feedlot (29)"""
	__tablename__ = 'FDLT_management'
	Scenario = Column(Integer)
	Location = Column(Integer)
	Year = Column(Integer)
	FDLMon = Column(Integer)
	FDLDay = Column(Integer)
	Days = Column(Integer)
	"""Number of adult animals"""
	AniAdult = Column(Integer)
	"""Number of non-adult animals"""
	AniNonAdult = Column(Integer)
	ManStoID = Column(String)
	ManStoDis = Column(String)
	ManRemMon = Column(Integer)
	ManRemDay = Column(Integer)
	ManRemFra = Column(Double)



class FDLT_management_dist(BMPTable):
	__tablename__ = 'FDLT_management_dist'
	Location = Column(Integer)
	ProducerID = Column(Integer)
	Subbasin = Column(Integer)
	CatBasID = Column(Integer)
	ManStoID = Column(String)
	ManStoDis = Column(String)
	SELECTION = Column(Integer)



class FLDV_parameter(BMPTable):
	__tablename__ = 'FLDV_parameter'
	"""Flow diversion ID"""
	ID = Column(Integer)
	"""X coordinates"""
	XLL = Column(Double)
	"""Y coordinates"""
	YLL = Column(Double)
	"""Operation date"""
	OPERATION = Column(String)
	"""Diversion source type, 0 - outside watershed e.g. deep groundwater, 1 - reach"""
	Source = Column(Integer)
	"""Source ID"""
	Source_ID = Column(Integer)
	"""Diversion target type, 0 - outside watershed e.g. deep groundwater, 1 - reach"""
	Target = Column(Integer)
	"""Target ID"""
	Target_ID = Column(Integer)
	"""Diversion rate type, 1 - divert fraction of water in source, 2 - leave minimum volume in source, 3 - divert rate (m3/s)"""
	div_type = Column(Integer)
	"""Constant diversion rate (fraction, m3, or m3/s)"""
	Q_REL = Column(Double)
	"""Flow diverting method, i.e. MEA_DIV - diversion using measured rate, CONS_DIV - diversion using constant rate (as Q_REL), MON_CONS_DIV - diversion using constant rate in monthes specified in start_mon and end_mon"""
	METHOD = Column(String)
	"""Sediment diverting method"""
	SEDMETHOD = Column(String)
	"""Nutrients diverting method"""
	NUTMETHOD = Column(String)
	"""Measured data table name in HydroClimate DB (must specify if selecting MEA_DIV method)"""
	FILE = Column(String)
	"""Start diversion month (only functional if selecting MON_CONS_DIV method)"""
	start_mon = Column(Integer)
	"""End diversion month (only functional if selecting MON_CONS_DIV method)"""
	end_mon = Column(Integer)
	"""Diversion channel length (m)"""
	length = Column(Double)
	"""Diversion channel width (m)"""
	width = Column(Double)
	"""Diversion channel main side slope (m/m)"""
	main_side_slope = Column(Double)
	"""Diversion channel floodplain side slope (m/m)"""
	floodplain_side_slope = Column(Double)
	"""Diversion channel main side slope (m/m)"""
	w_ratio = Column(Double)
	"""Diversion channel depth (m)"""
	depth = Column(Double)
	"""Diversion channel average channel slope (m/m)"""
	slope = Column(Double)
	"""Diversion channel manning coefficient"""
	manning = Column(Double)
	"""Diversion channel flow velocity (m/s)"""
	velocity = Column(Double)
	t0 = Column(Double)
	d0 = Column(Double)
	max_elevation = Column(Double)
	min_elevation = Column(Double)
	Ave_elevation = Column(Double)
	erodibility_factor = Column(Double)
	cover_factor = Column(Double)
	bc1 = Column(Double)
	bc2 = Column(Double)
	bc3 = Column(Double)
	bc4 = Column(Double)
	rk1 = Column(Double)
	rk2 = Column(Double)
	rk3 = Column(Double)
	rk4 = Column(Double)
	rs1 = Column(Double)
	rs2 = Column(Double)
	rs3 = Column(Double)
	rs4 = Column(Double)
	rs5 = Column(Double)



class FlowDiversion(BMPTable):
	__tablename__ = 'FlowDiversion'
	ID = Column(Integer)
	XLL = Column(Double)
	YLL = Column(Double)
	OPERATION = Column(String)
	TABLENAME = Column(String)



class GRAMG_management(BMPTable):
	"""Distribution Table for BMP: Grazing management (16)"""
	__tablename__ = 'GRAMG_management'
	"""Scenario ID"""
	Scenario = Column(Integer)
	"""Location ID"""
	Location = Column(Integer)
	"""BMP start year"""
	Year = Column(Integer)
	"""BMP start month"""
	GraMon = Column(Integer)
	"""BMP start day"""
	GraDay = Column(Integer)
	"""BMP lasting days"""
	Days = Column(Integer)
	"""Animal ID"""
	Ani_ID = Column(Integer)
	"""Adult animal percentage"""
	Ani_adult = Column(Integer)
	"""Grazing density (1/ha)"""
	GR_Density = Column(Double)
	"""Fraction of day animal stay in field"""
	DayFra = Column(Double)
	"""Water source type, 0 - outside watershed e.g. deep groundwater, 1 - reach, 2 - reservoir, 3 - catch basin, 4 - groundwater, 5 - wetland, 6 - dugout"""
	Source = Column(Integer)
	"""Water source ID"""
	SourceID = Column(Integer)
	"""Dugout IDs in the grazing area"""
	Dugout_ID = Column(Integer)
	"""0 – accessible, 1 – managed access, 2 – no access"""
	Access = Column(Integer)
	"""0 – no fencing, 1- fencing"""
	Fencing = Column(Integer)
	"""Percent of animals drinking in streams. Default is 1"""
	StreamAniPerc = Column(Float)
	"""Percent of day time for drinking, default is 0.02 (0.5/24)"""
	Drinking_time = Column(Float)
	"""Average bank erodibility change compared to no-fencing """
	BankK_Change = Column(Float)



class GRAMG_management_dist(BMPTable):
	"""Distribution Table for BMP: Grazing management (16)"""
	__tablename__ = 'GRAMG_management_dist'
	Scenario = Column(Integer)
	Location = Column(Integer)
	ID = Column(Integer)
	Level = Column(String)



class GRAMG_parameter(BMPTable):
	__tablename__ = 'GRAMG_parameter'
	"""Graze type ID"""
	ID = Column(Integer)



class GWW_management(BMPTable):
	"""Parameter Table for BMP: Grass waterway (6)"""
	__tablename__ = 'GWW_management'
	"""Riparian buffer drainage part id used for IMWEBs model calculation, one RIBUF may contain several drainage parts"""
	ID = Column(Integer)
	"""Year of operation"""
	Year = Column(Integer)
	"""Subbasin ID"""
	Subbasin = Column(Integer)
	"""GWW length (m)"""
	Length = Column(Double)
	"""GWW bankfull width (m), default is 10 m"""
	BFwidth = Column(Double)
	"""GWW bankfull depth (m), default is 0.5 m"""
	BFdepth = Column(Double)
	"""GWW channel side slope, default is 0.25 (1:4)"""
	SideSlope = Column(Double)
	"""GWW channel slope (%)"""
	Slope_perc = Column(Double)
	"""GWW roughness coefficient, default is 0.25"""
	Manning = Column(Double)
	"""GWW bankfull velocity (m/s)"""
	BFvelocity = Column(Double)
	"""GWW bottom conductivity (mm/hr), default is 10"""
	Conductivity = Column(Double)
	"""GWW erodibility factor, default is 0"""
	Erodibility = Column(Double)
	"""GWW cover factor, default is 0"""
	Cover = Column(Double)
	"""nan"""
	SELECTION = Column(Double)



class Livestock_Parameter(BMPTable):
	__tablename__ = 'Livestock_Parameter'
	"""Animal ID"""
	ID = Column(Integer)
	"""Animal name"""
	Name = Column(String)
	"""Description"""
	Description = Column(String)
	"""Manure ID corresponding the fertilizer table"""
	Man_ID = Column(Integer)
	"""Animal weight"""
	Ani_Weight = Column(Double)
	"""Fresh manure production per 1000kg live animal mass per day"""
	Man_Day = Column(Double)
	"""Dry mass intake per day in percent of body weight"""
	Mass_Intake = Column(Double)
	"""Average non-adult weight / adult weight"""
	Ani_nonadult = Column(Double)
	"""TSS percentage of the manure """
	Man_TSS_Fra = Column(Double)



class MAIF_parameter(BMPTable):
	"""Parameter Table for BMP: Managed access inluding fencing (40)"""
	__tablename__ = 'MAIF_parameter'
	"""Reach ID"""
	ID = Column(Integer)
	"""Subbasin ID"""
	Subbasin = Column(Integer)
	"""Operation starting year"""
	Year = Column(Integer)
	"""SELECTION"""
	SELECTION = Column(Integer)



class MAIF_selection(BMPTable):
	__tablename__ = 'MAIF_selection'
	"""Reach ID"""
	ID = Column(Integer)



class MASB_management(BMPTable):
	"""Distribution Table for BMP: Manure application setback (22)"""
	__tablename__ = 'MASB_management'
	Scenario = Column(Integer)
	Location = Column(Integer)
	SELECTION = Column(Integer)



class MASB_management_dist(BMPTable):
	"""Distribution Table for BMP: Manure application setback (22)"""
	__tablename__ = 'MASB_management_dist'
	Scenario = Column(Integer)
	Location = Column(Integer)
	SELECTION = Column(Integer)



class MCBI_Parameter(BMPTable):
	"""Parameter Table for BMP: Manure catch basin/impondment (28)"""
	__tablename__ = 'MCBI_Parameter'
	ID = Column(Integer)
	OperationYear = Column(Integer)
	Subbasin = Column(Integer)
	receive_reach_id = Column(Integer)
	MaxL_m = Column(Double)
	MaxW_m = Column(Double)
	MaxD_m = Column(Double)
	SideSlope = Column(Double)
	EndSlope = Column(Double)
	MaxVolume_104M3 = Column(Double)
	FDLT_Ratio = Column(Double)
	NonFDLT_Ratio = Column(Double)
	NSED = Column(Double)
	CB_Dcc = Column(Double)
	SettVolP_mYr = Column(Double)
	SettVolN_mYr = Column(Double)
	K_mmHr = Column(Double)
	CHLAR = Column(Double)
	SECCIR = Column(Double)
	InitialVolume_% = Column(Double)
	InitialSediment_mgL = Column(Double)
	InitialNO3_mgL = Column(Double)
	InitialSolP_mgL = Column(Double)
	InitialOrgN_mgL = Column(Double)
	InitialOrgP_mgL = Column(Double)
	SELECTION = Column(Integer)



class MCBI_Selection(BMPTable):
	__tablename__ = 'MCBI_Selection'
	ID = Column(Integer)



class MCL_crop_management(BMPTable):
	"""Distribution Table for BMP: Marginal crop management (30)"""
	__tablename__ = 'MCL_crop_management'
	Scenario = Column(Integer)
	Location = Column(Integer)
	ID = Column(Integer)
	Year = Column(Integer)
	ActualYear = Column(Integer)
	CropCode = Column(Integer)
	PlantingMon = Column(Integer)
	PlantingDay = Column(Integer)
	HarvestMon = Column(Integer)
	HarvestDay = Column(Integer)
	HarvestType = Column(Integer)
	HarvestEfficiency = Column(Double)
	HarvestIndexOverride = Column(Double)
	StoverFraction = Column(Double)
	CNOP = Column(Double)
	IsGrain = Column(Integer)
	PRCOP = Column(Double)



class MCL_crop_management_dist(BMPTable):
	"""Distribution Table for BMP: Marginal crop management (30)"""
	__tablename__ = 'MCL_crop_management_dist'
	Scenario = Column(Integer)
	Location = Column(Integer)
	ID = Column(Integer)
	Level = Column(String)



class MCL_fertilizer_management(BMPTable):
	"""Distribution Table for BMP: Marginal fertilizer management (31)"""
	__tablename__ = 'MCL_fertilizer_management'
	Scenario = Column(Integer)
	Location = Column(Integer)
	Year = Column(Integer)
	FerMon = Column(Integer)
	FerDay = Column(Integer)
	FerType = Column(Integer)
	FerRate = Column(Double)
	FerSurface = Column(Double)



class MCL_fertilizer_management_dist(BMPTable):
	"""Distribution Table for BMP: Marginal fertilizer management (31)"""
	__tablename__ = 'MCL_fertilizer_management_dist'
	Scenario = Column(Integer)
	Location = Column(Integer)
	ID = Column(Integer)
	Level = Column(String)



class MCL_tillage_management(BMPTable):
	"""Distribution Table for BMP: Marginal tillage management (32)"""
	__tablename__ = 'MCL_tillage_management'
	Scenario = Column(Integer)
	Location = Column(Integer)
	Year = Column(Integer)
	TillMon = Column(Integer)
	TillDay = Column(Integer)
	TillCode = Column(Integer)



class MCL_tillage_management_dist(BMPTable):
	"""Distribution Table for BMP: Marginal tillage management (32)"""
	__tablename__ = 'MCL_tillage_management_dist'
	Scenario = Column(Integer)
	Location = Column(Integer)
	ID = Column(Integer)
	Level = Column(String)



class MI48H_management(BMPTable):
	"""Distribution Table for BMP: Manure incorporation with 48h (21)"""
	__tablename__ = 'MI48H_management'
	Scenario = Column(Integer)
	Location = Column(Integer)
	FerSurface = Column(Double)
	SELECTION = Column(Integer)



class MI48H_management_dist(BMPTable):
	"""Distribution Table for BMP: Manure incorporation with 48h (21)"""
	__tablename__ = 'MI48H_management_dist'
	Scenario = Column(Integer)
	Location = Column(Integer)
	FerSurface = Column(Double)
	SELECTION = Column(Integer)



class MSCD_Parameter(BMPTable):
	"""Parameter Table for BMP: Manure storage capacity and design (27)"""
	__tablename__ = 'MSCD_Parameter'
	"""Manure storage ID"""
	ManStorageID = Column(Integer)
	"""Name"""
	Name = Column(String)
	"""Description"""
	Description = Column(String)
	"""Producer ID"""
	ProducerID = Column(Integer)
	"""Subbasin ID"""
	Subbasin = Column(Integer)
	"""Corresponding feedlot ID"""
	FeedlotID = Column(Integer)
	"""Length of the manure storage (m)"""
	ManLength_m = Column(Double)
	"""Width of the Manure storage (m)"""
	ManWidth_m = Column(Double)
	"""Area of the Manure storage (m2)"""
	ManArea_m2 = Column(Double)
	"""Drainage area of the manure storage (ha)"""
	DraArea_ha = Column(Double)
	"""Manure drainage area fraction of the subbasin area (-)"""
	DraFraction = Column(Double)
	"""Height to the nearby stream"""
	HigReach_m = Column(Double)
	"""Distance to the nearby stream"""
	DisReach_m = Column(Double)
	"""Threshold value of storage distance to the nearby stream (100m)"""
	ThDisReach = Column(Double)
	"""Threshold value of storage height to the nearby stream (10m)"""
	ThHigReach = Column(Double)
	"""Initial storage (kg)"""
	ManInitial = Column(Double)
	"""CN change fraction compared to non-storage area"""
	CN_change = Column(Double)
	"""PRC change fraction compared to non-storage area"""
	PRC_change = Column(Double)
	"""Manure event mean concentration (mg/l)"""
	Manure_EMC = Column(Double)
	"""Closest (distance or height difference) reach ID"""
	ReachID = Column(Integer)
	"""SELECTION"""
	SELECTION = Column(Integer)



class MSCD_Selection(BMPTable):
	__tablename__ = 'MSCD_Selection'
	"""SELECTION"""
	ID = Column(Integer)



class MSCD_management(BMPTable):
	"""Distribution Table for BMP: Manure storage capacity and design (27)"""
	__tablename__ = 'MSCD_management'
	"""Scenario ID"""
	Scenario = Column(Integer)
	"""Manure Storage ID"""
	Location = Column(Integer)
	"""nan"""
	Year = Column(Integer)
	"""Month of manure application"""
	ManAppMon = Column(Integer)
	"""Day of manure application"""
	ManAppDay = Column(Integer)
	"""Fraction of manure amount applied to the field"""
	ManAppFra = Column(Integer)



class NAOS_management(BMPTable):
	"""Distribution Table for BMP: No application on snow (23)"""
	__tablename__ = 'NAOS_management'
	Scenario = Column(Integer)
	Location = Column(Integer)
	StartYear = Column(Integer)
	StartMon = Column(Integer)
	StartDay = Column(Integer)
	EndYear = Column(Integer)
	EndMon = Column(Integer)
	EndDay = Column(Integer)
	IsAnnually = Column(Integer)
	SELECTION = Column(Integer)



class NAOS_management_dist(BMPTable):
	"""Distribution Table for BMP: No application on snow (23)"""
	__tablename__ = 'NAOS_management_dist'
	Scenario = Column(Integer)
	Location = Column(Integer)
	StartYear = Column(Integer)
	StartMon = Column(Integer)
	StartDay = Column(Integer)
	EndYear = Column(Integer)
	EndMon = Column(Integer)
	EndDay = Column(Integer)
	IsAnnually = Column(Integer)
	SELECTION = Column(Integer)



class OFSW_parameter(BMPTable):
	"""Parameter Table for BMP: Off site watering (39)"""
	__tablename__ = 'OFSW_parameter'
	"""Off-site watering ID"""
	ID = Column(Integer)
	"""Operation starting year (designed for setting up dugout scenarios)"""
	Year = Column(Integer)
	"""Subbasin ID"""

In [17]:
table_def.index

Index([39, 39, 39, 39], dtype='int64', name='TableID')

In [15]:
import pandas as pd

df = pd.read_csv(r"C:\Work\imWEBs\test\test_model\watershed\input\landuseLookup.csv", usecols=[0, 1], index_col=0, dtype='int')
dict = df[df.columns[0]].to_dict()
dict.items().t

dict_items([(1, 1), (2, 2), (3, 3), (7, 7), (12, 12), (18, 18), (28, 28), (36, 36), (75, 75), (107, 107)])

In [6]:
from whitebox_workflows import WbEnvironment
import math


wbe = WbEnvironment()

subbasin_raster = wbe.read_raster(r"C:\Work\imWEBs\Interface\BRC_TIFFs\subbasin.tif")
values = wbe.list_unique_values_raster(subbasin_raster)
values

#slope_raster = wbe.read_raster(r"C:\Work\imWEBs\Interface\BRC_TIFFs\slopeDeg.tif")
#raster_2 = (slope_raster * math.pi / 180).tan()

'Category,Frequency\n1,879\n2,1353\n3,613\n4,123\n5,234\n6,101\n7,99\n8,52\n9,45\n10,128\n11,98\n12,19\n13,96\n14,36\n15,14\n16,8\n17,14\n18,147\n19,37\n20,6\n21,15\n22,9\n23,40\n24,92\n25,32\n26,72\n27,137\n28,7\n29,105\n30,12\n31,9\n32,93\n33,97\n34,10\n35,23\n36,92\n37,17\n38,123\n39,44\n40,240\n41,2\n42,46\n43,13\n44,5\n45,35\n46,4\n47,44\n48,20\n49,22\n50,31\n51,26\n52,7\n53,30\n54,11\n55,17\n56,33\n57,212\n58,13\n59,47\n60,82\n61,70\n62,73\n63,42\n64,14\n65,14\n66,515\n67,19\n68,14\n69,50\n70,9\n71,13\n72,1049\n73,22\n74,40\n75,17\n76,26\n77,14\n78,19\n79,350\n80,305\n81,17\n82,16\n83,7\n84,89\n85,7\n86,193\n87,34\n88,42\n89,17\n90,98\n91,14\n92,14\n93,35\n94,61\n95,137\n96,4\n97,16\n98,38\n99,16\n100,38\n101,9\n102,52\n103,81\n104,4\n105,18\n106,8\n107,657\n108,136\n109,11\n110,7\n111,20\n112,23\n113,7\n114,622\n115,35\n116,30\n117,97\n118,25\n119,18\n120,36\n121,82\n122,16\n123,23\n124,10\n125,34\n126,90\n127,18\n128,26\n129,35\n130,79\n131,27\n132,40\n133,9\n134,61\n135,9\n136,10\n137,178\n138,6\n139,17\n140,16\n141,93\n142,51\n143,2\n144,16\n145,15\n146,157\n147,55\n148,27\n149,93\n150,175\n151,35\n152,11\n153,27\n154,115\n155,14\n156,7\n157,83\n158,81\n159,5\n160,71\n161,33\n162,84\n163,21\n164,17\n165,38\n166,11\n167,38\n168,55\n169,310\n170,26\n171,7\n172,8\n173,184\n174,32\n175,29\n176,86\n177,9\n178,17\n179,7\n180,4\n181,230\n182,104\n183,170\n184,1\n185,15\n186,28\n187,9\n188,13\n189,6\n190,27\n191,26\n192,43\n193,20\n194,3\n195,73\n196,6\n197,11\n198,14\n199,79\n200,25\n201,65\n202,20\n203,6\n204,134\n205,5\n206,55\n207,11\n208,39\n209,53\n210,366\n211,105\n212,26\n213,7\n214,17\n215,15\n216,185\n217,10\n218,26\n219,9\n220,51\n221,15\n222,11\n223,19\n224,125\n225,5\n226,66\n227,47\n228,16\n229,63\n230,88\n231,29\n232,16\n233,22\n234,29\n235,166\n236,76\n237,15\n238,51\n239,91\n240,11\n241,38\n242,35\n243,7\n244,165\n245,7\n246,70\n247,79\n248,384\n249,26\n250,56\n251,30\n252,127\n253,12\n254,55\n255,20\n256,4\n257,51\n258,8\n259,74\n260,25\n261,7\n262,62\n263,67\n264,8\n265,33\n266,15\n267,14\n268,21\n269,56\n270,7\n271,48\n272,14\n273,2\n274,48\n275,42\n276,64\n277,10\n278,15\n279,49\n280,141\n281,8\n282,20\n283,19\n284,4\n285,186\n286,107\n287,25\n288,15\n289,9\n290,162\n291,145\n292,12\n293,13\n294,14\n295,14\n296,19\n297,240\n298,30\n299,51\n300,14\n301,51\n302,15\n303,1489\n304,5\n305,36\n306,33\n307,22\n308,23\n309,24\n310,54\n311,27\n312,60\n313,39\n314,16\n315,13\n316,20\n317,34\n318,16\n319,125\n320,71\n321,86\n322,22\n323,47\n324,65\n325,24\n326,3\n327,4\n328,14\n329,27\n330,16\n331,34\n332,35\n333,91\n334,108\n335,19\n336,34\n337,16\n338,17\n339,12\n340,49\n341,14\n342,24\n343,64\n344,15\n345,32\n346,16\n347,72\n348,12\n349,135\n350,7\n351,36\n352,11\n353,33\n354,413\n355,111\n356,4\n357,54\n358,24\n359,54\n360,271\n361,10\n362,42\n363,16\n364,14\n365,28\n366,55\n367,132\n368,107\n369,94\n370,4\n371,7\n372,19\n373,39\n374,11\n375,16\n376,87\n377,70\n378,10\n379,227\n380,58\n381,7\n382,9\n383,12\n384,17\n385,7\n386,21\n387,24\n388,99\n389,125\n390,190\n391,45\n392,33\n393,7\n394,20\n395,24\n396,84\n397,17\n398,20\n399,37\n400,14\n401,27\n402,34\n403,6\n404,39\n405,10\n406,111\n407,322\n408,3\n409,10\n410,78\n411,12\n412,43\n413,31\n414,37\n415,16\n416,26\n417,17\n418,6\n419,19\n420,69\n421,35\n422,5\n423,329\n424,28\n425,14\n426,28\n427,17\n428,23\n429,62\n430,17\n431,20\n432,806\n433,31\n434,21\n435,14\n436,21\n437,16\n438,56\n439,31\n440,11\n441,16\n442,245\n443,16\n444,189\n445,126\n446,27\n447,353\n448,30\n449,1\n450,11\n451,87\n452,24\n453,27\n454,35\n455,9\n456,9\n457,127\n458,141\n459,34\n460,66\n461,7\n462,14\n463,36\n464,1\n465,63\n466,5\n467,55\n468,26\n469,526\n470,68\n471,8\n472,6\n473,54\n474,29\n475,14\n476,11\n477,96\n478,4\n479,27\n480,47\n481,83\n482,17\n483,35\n484,17\n485,12\n486,83\n487,23\n488,39\n489,13\n490,3\n491,185\n492,39\n493,18\n494,38\n495,26\n496,14\n497,16\n498,106\n499,5\n500,46\n501,49\n502,13\n503,9\n504,16\n505,3\n506,53\n507,68\n508,44\n509,347\n510,100\n511,24\n512,24\n513,10\n514,32\n515,133\n516,56\n517,42\n518,52\n519,18\n520,6\n521,10\n522,86\n523,68\n524,24\n525,85\n526,220\n527,12\n528,19\n529,41\n530,35\n531,14\n532,34\n533,15\n534,9\n535,67\n536,96\n537,16\n538,144\n539,2\n540,78\n541,33\n542,33\n543,61\n544,10\n545,13\n546,13\n547,21\n548,32\n549,14\n550,43\n551,55\n552,17\n553,25\n554,13\n555,66\n556,20\n557,16\n558,4\n559,353\n560,14\n561,54\n562,37\n563,32\n564,62\n565,8\n566,70\n567,69\n568,212\n569,9\n570,36\n571,17\n572,10\n573,15\n574,11\n575,18\n576,17\n577,11\n578,175\n579,7\n580,34\n581,113\n582,10\n583,436\n584,31\n585,65\n586,7\n587,7\n588,65\n589,70\n590,27\n591,6\n592,16\n593,17\n594,38\n595,18\n596,10\n597,23\n598,5\n599,33\n600,19\n601,24\n602,28\n603,8\n604,26\n605,113\n606,170\n607,4\n608,7\n609,404\n610,26\n611,17\n612,173\n613,76\n614,8\n615,78\n616,49\n617,16\n618,47\n619,130\n620,31\n621,18\n622,120\n623,4\n624,244\n625,37\n626,27\n627,4\n628,14\n629,9\n630,146\n631,37\n632,30\n633,40\n634,48\n635,52\n636,130\n637,7\n638,7\n639,51\n640,58\n641,27\n642,14\n643,7\n644,4\n645,37\n646,21\n647,9\n648,6\n649,85\n650,29\n651,23\n652,19\n653,60\n654,59\n655,10\n656,11\n657,17\n658,34\n659,99\n660,56\n661,24\n662,18\n663,262\n664,10\n665,60\n666,15\n667,9\n668,16\n669,20\n670,61\n671,13\n672,87\n673,112\n674,33\n675,84\n676,75\n677,86\n678,34\n679,79\n680,85\n681,10\n682,165\n683,114\n684,2840\n685,8\n686,77\n687,16\n688,10\n689,43\n690,141\n691,45\n692,113\n693,4\n694,10\n695,99\n696,280\n697,26\n698,4\n699,72\n700,29\n701,54\n702,26\n703,10\n704,35\n705,57\n706,52\n707,8\n708,63\n709,38\n710,135\n711,7\n712,2\n713,8\n714,41\n715,58\n716,1955\n717,16\n718,29\n719,16\n720,877\n721,58\n722,40\n723,11\n724,30\n725,36\n726,3\n727,61\n728,13\n729,31\n730,14\n731,67\n732,5\n733,404\n734,64\n735,7\n736,190\n737,370\n738,47\n739,7\n740,7\n741,11\n742,31\n743,11\n744,24\n745,57\n746,20\n747,31\n748,39\n749,74\n750,53\n751,9\n752,11\n753,49\n754,24\n755,21\n756,114\n757,8\n758,31\n759,22\n760,4\n761,17\n762,45\n763,36\n764,74\n765,123\n766,45\n767,94\n768,14\n769,28\n770,39\n771,64\n772,59\n773,36\n774,8\n775,27\n776,9\n777,16\n778,30\n779,14\n780,7\n781,11\n782,10\n783,83\n784,19\n785,44\n786,63\n787,24\n788,10\n789,58\n790,39\n791,62\n792,25\n793,11\n794,133\n795,13\n796,13\n797,63\n798,35\n799,26\n800,17\n801,47\n802,560\n803,19\n804,20\n805,8\n806,19\n807,145\n808,92\n809,7\n810,14\n811,19\n812,341\n813,18\n814,10\n815,110\n816,8\n817,33\n818,13\n819,13\n820,27\n821,20\n822,4\n823,13\n824,92\n825,16\n826,34\n827,13\n828,10\n829,71\n830,80\n831,100\n832,33\n833,7\n834,10\n835,17\n836,18\n837,11\n838,8\n839,80\n840,28\n841,40\n842,157\n843,6\n844,20\n845,8\n846,39\n847,70\n848,79\n849,57\n850,9\n851,83\n852,18\n853,34\n854,118\n855,69\n856,43\n857,16\n858,20\n859,17\n860,10\n861,22\n862,47\n863,19\n864,19\n865,106\n866,8\n867,82\n868,12\n869,23\n870,23\n871,20\n872,6\n873,157\n874,106\n875,37\n876,12\n877,17\n878,42\n879,6\n880,38\n881,143\n882,77\n883,30\n884,31\n885,11\n886,14\n887,14\n888,46\n889,498\n890,30\n891,6\n892,35\n893,98\n894,10\n895,36\n896,10\n897,69\n898,55\n899,34\n900,73\n901,19\n902,8\n903,9\n904,8\n905,100\n906,5\n907,81\n908,6\n909,13\n910,106\n911,100\n912,39\n913,23\n914,16\n915,43\n916,10\n917,59\n918,131\n919,31\n920,18\n921,27\n922,22\n923,57\n924,21\n925,128\n926,167\n927,36\n928,62\n929,36\n930,1\n931,37\n932,51\n933,10\n934,17\n935,20\n936,18\n937,8\n938,14\n939,27\n940,24\n941,41\n942,260\n943,32\n944,33\n945,101\n946,17\n947,58\n948,30\n949,17\n950,22\n951,17\n952,60\n953,21\n954,62\n955,21\n956,41\n957,44\n958,17\n959,14\n960,47\n961,72\n962,47\n963,15\n964,14\n965,23\n966,17\n967,15\n968,245\n969,132\n970,6\n971,4\n972,30\n973,12\n974,10\n975,6\n976,10\n977,10\n978,5\n979,24\n980,40\n981,42\n982,75\n983,2\n984,57\n985,8\n986,8\n987,8\n988,15\n989,13\n990,7\n991,3\n992,28\n993,50\n994,28\n995,30\n996,28\n997,64\n998,24\n999,10\n1000,105\n1001,24\n1002,135\n1003,16\n1004,373\n1005,181\n1006,77\n1007,40\n1008,3\n1009,16\n1010,1\n1011,13\n1012,105\n1013,77\n1014,66\n1015,42\n1016,24\n1017,59\n1018,28\n1019,26\n1020,20\n1021,302\n1022,19\n1023,287\n1024,19\n1025,38\n1026,476\n1027,26\n1028,15\n1029,60\n1030,21\n1031,40\n1032,23\n1033,13\n1034,6\n1035,36\n1036,34\n1037,34\n1038,12\n1039,120\n1040,37\n1041,21\n1042,7\n1043,127\n1044,41\n1045,32\n1046,152\n1047,38\n1048,42\n1049,408\n1050,7\n1051,14\n1052,33\n1053,4\n1054,36\n1055,265\n1056,127\n1057,52\n1058,76\n1059,27\n1060,67\n1061,8\n1062,66\n1063,10\n1064,12\n1065,29\n1066,18\n1067,58\n1068,15\n1069,78\n1070,52\n1071,78\n1072,9\n1073,14\n1074,324\n1075,59\n1076,63\n1077,9\n1078,139\n1079,3\n1080,17\n1081,56\n1082,70\n1083,87\n1084,44\n1085,9\n1086,6\n1087,36\n1088,33\n1089,25\n1090,26\n1091,18\n1092,6\n1093,34\n1094,25\n1095,4\n1096,9\n1097,29\n1098,48\n1099,86\n1100,14\n1101,49\n1102,12\n1103,34\n1104,70\n1105,20\n1106,44\n1107,10\n1108,7\n1109,45\n1110,15\n1111,73\n1112,11\n1113,20\n1114,64\n1115,22\n1116,31\n1117,59\n1118,13\n1119,6\n1120,24\n1121,50\n1122,8\n1123,44\n1124,138\n1125,11\n1126,12\n1127,9\n1128,35\n1129,22\n1130,13\n1131,57\n1132,10\n1133,6\n1134,30\n1135,152\n1136,12\n1137,188\n1138,11\n1139,18\n1140,77\n1141,21\n1142,89\n1143,13\n1144,41\n1145,27\n1146,27\n1147,12\n1148,9\n1149,6\n1150,4\n1151,49\n1152,49\n1153,8\n1154,7\n1155,274\n1156,4\n1157,11\n1158,546\n1159,10\n1160,14\n1161,28\n1162,7\n1163,13\n1164,160\n1165,50\n1166,26\n1167,16\n1168,130\n1169,67\n1170,29\n1171,9\n1172,118\n1173,8\n1174,42\n1175,902\n1176,39\n1177,16\n1178,10\n1179,6\n1180,7\n1181,11\n1182,7\n1183,15\n1184,9\n1185,26\n1186,55\n1187,18\n1188,92\n1189,289\n1190,19\n1191,22\n1192,16\n1193,7\n1194,19\n1195,103\n1196,35\n1197,11\n1198,157\n1199,76\n1200,11\n1201,10\n1202,3\n1203,42\n1204,52\n1205,110\n1206,32\n1207,60\n1208,41\n1209,61\n1210,34\n1211,19\n1212,29\n1213,80\n1214,12\n1215,2\n1216,6\n1217,13\n1218,23\n1219,22\n1220,55\n1221,16\n1222,22\n1223,150\n1224,34\n1225,48\n1226,26\n1227,56\n1228,10\n1229,9\n1230,109\n1231,10\n1232,44\n1233,38\n1234,36\n1235,22\n1236,6\n1237,51\n1238,16\n1239,566\n1240,6\n1241,30\n1242,20\n1243,61\n1244,22\n1245,54\n1246,8\n1247,13\n1248,57\n1249,12\n1250,85\n1251,9\n1252,14\n1253,7\n1254,16\n1255,34\n1256,20\n1257,76\n1258,13\n1259,6\n1260,48\n1261,273\n1262,10\n1263,465\n1264,38\n1265,9\n1266,12\n1267,56\n1268,76\n1269,28\n1270,8\n1271,14\n1272,21\n1273,29\n1274,9\n1275,6\n1276,18\n1277,449\n1278,83\n1279,40\n1280,32\n1281,19\n1282,12\n1283,840\n1284,99\n1285,15\n1286,6\n1287,10\n1288,17\n1289,92\n1290,28\n1291,7\n1292,14\n1293,61\n1294,11\n1295,2\n1296,23\n1297,111\n1298,32\n1299,22\n1300,5\n1301,501\n1302,59\n1303,33\n1304,20\n1305,26\n1306,422\n1307,3\n1308,35\n1309,10\n1310,20\n1311,7\n1312,17\n1313,2\n1314,36\n1315,29\n1316,29\n1317,72\n1318,28\n1319,16\n1320,207\n1321,33\n1322,47\n1323,23\n1324,52\n1325,22\n1326,23\n1327,12\n1328,32\n1329,39\n1330,58\n1331,79\n1332,15\n1333,49\n1334,7\n1335,24\n1336,37\n1337,18\n1338,21\n1339,12\n1340,10\n1341,57\n1342,13\n1343,36\n1344,22\n1345,45\n1346,29\n1347,4\n1348,42\n1349,6\n1350,13\n1351,144\n1352,2\n1353,30\n1354,15\n1355,654\n1356,18\n1357,58\n1358,33\n1359,7\n1360,24\n1361,21\n1362,14\n1363,7\n1364,67\n1365,25\n1366,5\n1367,90\n1368,182\n1369,48\n1370,28\n1371,75\n1372,36\n1373,95\n1374,21\n1375,14\n1376,125\n1377,20\n1378,53\n1379,21\n1380,46\n1381,62\n1382,7\n1383,5\n1384,32\n1385,13\n1386,19\n1387,31\n1388,72\n1389,105\n1390,10\n1391,35\n1392,184\n1393,104\n1394,12\n1395,8\n1396,17\n1397,63\n1398,201\n1399,4\n1400,23\n1401,12\n1402,8\n1403,44\n1404,14\n1405,24\n1406,59\n1407,29\n1408,17\n1409,4\n1410,40\n1411,13\n1412,30\n1413,179\n1414,22\n1415,32\n1416,3\n1417,8\n1418,4\n1419,24\n1420,10\n1421,2\n1422,58\n1423,19\n1424,237\n1425,267\n1426,12\n1427,255\n1428,24\n1429,14\n1430,11\n1431,54\n1432,7\n1433,18\n1434,14\n1435,153\n1436,97\n1437,15\n1438,145\n1439,80\n1440,2\n1441,18\n1442,22\n1443,42\n1444,16\n1445,23\n1446,69\n1447,21\n1448,92\n1449,12\n1450,10\n1451,29\n1452,6\n1453,53\n1454,28\n1455,87\n1456,49\n1457,10\n1458,22\n1459,111\n1460,12\n1461,17\n1462,135\n1463,44\n1464,164\n1465,33\n1466,44\n1467,41\n1468,3\n1469,12\n1470,16\n1471,13\n1472,27\n1473,30\n1474,179\n1475,78\n1476,23\n1477,98\n1478,34\n1479,299\n1480,47\n1481,82\n1482,73\n1483,30\n1484,30\n1485,20\n1486,13\n1487,66\n1488,71\n1489,95\n1490,37\n1491,9\n1492,36\n1493,46\n1494,1291\n1495,67\n1496,6\n1497,426\n1498,577\n1499,4\n1500,26\n1501,35\n1502,72\n1503,8\n1504,10\n1505,117\n1506,38\n1507,57\n1508,6\n1509,18\n1510,72\n1511,52\n1512,58\n1513,109\n1514,40\n1515,16\n1516,19\n1517,29\n1518,97\n1519,15\n1520,15\n1521,69\n1522,19\n1523,56\n1524,162\n1525,38\n1526,47\n1527,13\n1528,14\n1529,23\n1530,8\n1531,4\n1532,44\n1533,14\n1534,16\n1535,67\n1536,18\n1537,22\n1538,112\n1539,9\n1540,34\n1541,10\n1542,12\n1543,170\n1544,19\n1545,178\n1546,147\n1547,188\n1548,16\n1549,6\n1550,42\n1551,43\n1552,290\n1553,15\n1554,24\n1555,11\n1556,59\n1557,20\n1558,94\n1559,30\n1560,4\n1561,11\n1562,129\n1563,5\n1564,48\n1565,52\n1566,6\n1567,75\n1568,12\n1569,72\n1570,39\n1571,29\n1572,91\n1573,63\n1574,56\n1575,28\n1576,37\n1577,32\n1578,95\n1579,258\n1580,7\n1581,40\n1582,63\n1583,19\n1584,250\n1585,113\n1586,859\n1587,39\n1588,42\n1589,4\n1590,104\n1591,16\n1592,23\n1593,43\n1594,318\n1595,33\n1596,233\n1597,65\n1598,24\n1599,5\n1600,25\n1601,26\n1602,18\n1603,539\n1604,12\n1605,11\n1606,917\n1607,11\n1608,13\n1609,16\n1610,10\n1611,12\n1612,4\n1613,18\n1614,268\n1615,6\n1616,81\n1617,45\n1618,42\n1619,1\n1620,26\n1621,9\n1622,55\n1623,151\n1624,41\n1625,8\n1626,74\n1627,7\n1628,24\n1629,17\n1630,13\n1631,42\n1632,24\n1633,109\n1634,5\n1635,292\n1636,49\n1637,60\n1638,27\n1639,26\n1640,24\n1641,39\n1642,155\n1643,7\n1644,5\n1645,94\n1646,32\n1647,27\n1648,87\n1649,20\n1650,51\n1651,7\n1652,19\n1653,34\n1654,12\n1655,75\n1656,54\n1657,70\n1658,61\n1659,4\n1660,62\n1661,37\n1662,40\n1663,12\n1664,20\n1665,15\n1666,61\n1667,46\n1668,8\n1669,10\n1670,7\n1671,5\n1672,19\n1673,6\n1674,82\n1675,16\n1676,419\n1677,26\n1678,6\n1679,94\n1680,11\n1681,15\n1682,48\n1683,13\n1684,14\n1685,8\n1686,46\n1687,8\n1688,59\n1689,7\n1690,10\n1691,58\n1692,40\n1693,245\n1694,94\n1695,5\n1696,7\n1697,20\n1698,50\n1699,17\n1700,36\n1701,265\n1702,10\n1703,166\n1704,81\n1705,9\n1706,6\n1707,12\n1708,132\n1709,41\n1710,4\n1711,4\n1712,145\n1713,54\n1714,170\n1715,8\n1716,13\n1717,14\n1718,29\n1719,38\n1720,8\n1721,16\n1722,27\n1723,63\n1724,66\n1725,48\n1726,61\n1727,63\n1728,34\n1729,11\n1730,12\n1731,13\n1732,41\n1733,18\n1734,557\n1735,61\n1736,57\n1737,32\n1738,19\n1739,14\n1740,48\n1741,9\n1742,20\n1743,21\n1744,26\n1745,56\n1746,330\n1747,43\n1748,25\n1749,157\n1750,424\n1751,21\n1752,7\n1753,12\n1754,6\n1755,29\n1756,18\n1757,69\n1758,6\n1759,22\n1760,6\n1761,30\n1762,31\n1763,56\n1764,85\n1765,28\n1766,108\n1767,289\n1768,22\n1769,340\n1770,26\n1771,25\n1772,9\n1773,2\n1774,7\n1775,28\n1776,11\n1777,11\n1778,7\n1779,71\n1780,65\n1781,4\n1782,52\n1783,12\n1784,8\n1785,43\n1786,26\n1787,124\n1788,7\n1789,24\n1790,34\n1791,16\n1792,35\n1793,34\n1794,25\n1795,16\n1796,61\n1797,23\n1798,20\n1799,16\n1800,66\n1801,7\n1802,30\n1803,759\n1804,14\n1805,38\n1806,138\n1807,6\n1808,51\n1809,13\n1810,12\n1811,18\n1812,21\n1813,6\n1814,202\n1815,68\n1816,39\n1817,31\n1818,28\n1819,11\n1820,23\n1821,7\n1822,237\n1823,17\n1824,48\n1825,12\n1826,81\n1827,16\n1828,60\n1829,49\n1830,18\n1831,190\n1832,35\n1833,8\n1834,26\n1835,140\n1836,14\n1837,15\n1838,135\n1839,75\n1840,135\n1841,24\n1842,10\n1843,10\n1844,26\n1845,10\n1846,42\n1847,19\n1848,11\n1849,26\n1850,9\n1851,19\n1852,11\n1853,120\n1854,62\n1855,8\n1856,108\n1857,29\n1858,26\n1859,25\n1860,13\n1861,13\n1862,93\n1863,585\n1864,4\n1865,97\n1866,60\n1867,15\n1868,84\n1869,84\n1870,38\n1871,11\n1872,35\n1873,40\n1874,10\n1875,35\n1876,21\n1877,37\n1878,12\n1879,6\n1880,15\n1881,77\n1882,124\n1883,16\n1884,16\n1885,5\n1886,6\n1887,14\n1888,240\n1889,22\n1890,18\n1891,4\n1892,21\n1893,26\n1894,46\n1895,14\n1896,9\n1897,152\n1898,784\n1899,31\n1900,21\n1901,22\n1902,28\n1903,134\n1904,28\n1905,64\n1906,155\n1907,37\n1908,138\n1909,14\n1910,61\n1911,25\n1912,8\n1913,9\n1914,18\n1915,158\n1916,262\n1917,695\n1918,17\n1919,43\n1920,36\n1921,29\n1922,9\n1923,99\n1924,25\n1925,15\n1926,1894\n1927,9\n1928,15\n1929,16\n1930,86\n1931,14\n1932,27\n1933,18\n1934,14\n1935,34\n1936,66\n1937,16\n1938,52\n1939,6\n1940,21\n1941,138\n1942,457\n1943,76\n1944,51\n1945,55\n1946,17\n1947,89\n1948,9\n1949,84\n1950,15\n1951,68\n1952,15\n1953,126\n1954,4\n1955,90\n1956,32\n1957,51\n1958,99\n1959,12\n1960,7\n1961,103\n1962,181\n1963,41\n1964,44\n1965,99\n1966,12\n1967,5\n1968,32\n1969,81\n1970,96\n1971,14\n1972,13\n1973,32\n1974,39\n1975,70\n1976,6\n1977,24\n1978,118\n1979,122\n1980,58\n1981,92\n1982,40\n1983,49\n1984,16\n1985,14\n1986,37\n1987,27\n1988,22\n1989,30\n1990,116\n1991,81\n1992,420\n1993,94\n1994,10\n1995,10\n1996,15\n1997,74\n1998,311\n1999,26\n2000,9\n2001,7\n2002,9\n2003,589\n2004,26\n2005,7\n2006,15\n2007,84\n2008,43\n2009,2\n2010,42\n2011,131\n2012,93\n2013,134\n2014,38\n2015,44\n2016,89\n2017,5\n2018,21\n2019,6\n2020,12\n2021,18\n2022,57\n2023,8\n2024,3\n2025,139\n2026,5\n2027,50\n2028,24\n2029,26\n2030,79\n2031,12\n2032,218\n2033,64\n2034,16\n2035,78\n2036,82\n2037,56\n2038,25\n2039,19\n2040,10\n2041,75\n2042,31\n2043,21\n2044,33\n2045,91\n2046,26\n2047,37\n2048,106\n2049,31\n2050,22\n2051,17\n2052,1\n2053,23\n2054,25\n2055,50\n2056,194\n2057,24\n2058,312\n2059,136\n2060,14\n2061,12\n2062,7\n2063,51\n2064,384\n2065,15\n2066,14\n2067,3\n2068,103\n2069,54\n2070,17\n2071,41\n2072,6\n2073,53\n2074,19\n2075,34\n2076,58\n2077,58\n2078,14\n2079,64\n2080,42\n2081,15\n2082,59\n2083,103\n2084,11\n2085,34\n2086,38\n2087,30\n2088,65\n2089,56\n2090,17\n2091,15\n2092,12\n2093,9\n2094,21\n2095,34\n2096,12\n2097,35\n2098,241\n2099,13\n2100,28\n2101,31\n2102,11\n2103,70\n2104,39\n2105,9\n2106,39\n2107,36\n2108,71\n2109,13\n2110,53\n2111,11\n2112,7\n2113,58\n2114,899\n2115,119\n2116,41\n2117,123\n2118,58\n2119,25\n2120,525\n2121,56\n2122,5\n2123,33\n2124,76\n2125,6\n2126,5\n2127,18\n2128,150\n2129,13\n2130,13\n2131,62\n2132,17\n2133,9\n2134,39\n2135,14\n2136,7\n2137,129\n2138,114\n2139,81\n2140,8\n2141,195\n2142,47\n2143,77\n2144,12\n2145,49\n2146,19\n2147,83\n2148,5\n2149,12\n2150,177\n2151,68\n2152,55\n2153,2\n2154,12\n2155,6\n2156,12\n2157,5\n2158,10\n2159,39\n2160,512\n2161,12\n2162,10\n2163,7\n2164,24\n2165,1\n2166,1126\n2167,142\n2168,5\n2169,47\n2170,7\n2171,8\n2172,71\n2173,15\n2174,55\n2175,74\n2176,76\n2177,32\n2178,29\n2179,44\n2180,1319\n2181,132\n2182,29\n2183,23\n2184,359\n2185,32\n2186,15\n2187,84\n2188,22\n2189,1143\n2190,4\n2191,11\n2192,13\n2193,9\n2194,21\n2195,151\n2196,3\n2197,12\n2198,33\n2199,123\n2200,58\n2201,17\n2202,12\n2203,8\n2204,81\n2205,6\n2206,23\n2207,27\n2208,100\n2209,26\n2210,35\n2211,32\n2212,29\n2213,12\n2214,12\n2215,14\n2216,188\n2217,53\n2218,25\n2219,29\n2220,12\n2221,7\n2222,46\n2223,26\n2224,6\n2225,13\n2226,4\n2227,2\n2228,7\n2229,14\n2230,18\n2231,26\n2232,26\n2233,30\n2234,11\n2235,30\n2236,10\n2237,21\n2238,13\n2239,124\n2240,20\n2241,21\n2242,28\n2243,737\n2244,23\n2245,109\n2246,13\n2247,17\n2248,8\n2249,8\n2250,81\n2251,3\n2252,15\n2253,19\n2254,24\n2255,15\n2256,35\n2257,45\n2258,185\n2259,69\n2260,23\n2261,6\n2262,30\n2263,30\n2264,5\n2265,13\n2266,23\n2267,5\n2268,10\n2269,6\n2270,90\n2271,11\n2272,47\n2273,44\n2274,10\n2275,8\n2276,8\n2277,29\n2278,47\n2279,58\n2280,7\n2281,398\n2282,107\n2283,22\n2284,16\n2285,33\n2286,23\n2287,76\n2288,117\n2289,522\n2290,7\n2291,22\n2292,69\n2293,11\n2294,120\n2295,9\n2296,28\n2297,34\n2298,2\n2299,6\n2300,39\n2301,237\n2302,812\n2303,12\n2304,37\n2305,84\n2306,23\n2307,54\n2308,12\n2309,19\n2310,229\n2311,24\n2312,24\n2313,73\n2314,92\n2315,38\n2316,209\n2317,185\n2318,106\n2319,51\n2320,55\n2321,10\n2322,13\n2323,4\n2324,23\n2325,3\n2326,5\n2327,9\n2328,45\n2329,210\n2330,22\n2331,78\n2332,26\n2333,57\n2334,120\n2335,21\n2336,22\n2337,187\n2338,18\n2339,38\n2340,16\n2341,26\n2342,7\n2343,36\n2344,127\n2345,6\n2346,57\n2347,7\n2348,5

In [7]:
from io import StringIO
df = pd.read_csv(StringIO(values), sep =",", usecols = [0])
dict = df[df.columns[0]].to_list()
dict

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 ...]

In [3]:
wbe.write_raster(raster_2, r"C:\Work\imWEBs\Interface\BRC_TIFFs\slopeRadius.tif")

In [4]:
from imWEBs.database.reach_parameter import ReachParameter

attributes = [attr for attr in dir(ReachParameter) if not attr.startswith("_") and not callable(getattr(ReachParameter, attr))]
print(attributes)  # Output: ['a', 'b']

['Ave_elevation', 'MSK_X', 'MSK_col', 'a_bnk', 'b_bnk', 'bc1', 'bc2', 'bc3', 'bc4', 'bnk0', 'chs0', 'contribution_area', 'cover_factor', 'd0', 'depth', 'erodibility_factor', 'floodplain_side_slope', 'k_bank', 'k_chb', 'length', 'main_side_slope', 'manning', 'max_elevation', 'metadata', 'minFlow', 'min_elevation', 'order', 'outlet_id', 'reach_id', 'receive_reach_id', 'registry', 'rk1', 'rk2', 'rk3', 'rk4', 'rs1', 'rs2', 'rs3', 'rs4', 'rs5', 'slope', 'subbasin_id', 't0', 'velocity', 'w_ratio', 'width']

In [5]:
len(attributes)

46

In [8]:
p = ReachParameter()
dict = p.to_dict()
print(dict)

AttributeError: 'ReachParameter' object has no attribute 'to_dict'

In [6]:
import pandas as pd

In [7]:
reach_parameters = []
for row in range(10):
    reach_parameters.append(ReachParameter())
df = pd.DataFrame([p.to_dict() for p in reach_parameters])
print(df)

AttributeError: 'ReachParameter' object has no attribute 'to_dict'

In [1]:
class test:
    @property
    def some_property(self):
        return 1
    
t = test()
getattr(t, "some_property")

1