In [9]:
import geopandas as gpd
import pandas as pd
import numpy as np

In [6]:
field_shp = r"D:\imWEBs\STC\STC-Landuse-Data\field\unit_management_from_raster_dissolved.shp"
grazing_management_csv = r"D:\imWEBs\STC\STC-Landuse-Data\Processed\grazing_management.csv"
fertilizer_parameter_csv = r"D:\imWEBs\STC\STC-Landuse-Data\Processed\lookups\fertilizer_parameter.csv"
livestock_parameter_csv = r"D:\imWEBs\STC\STC-Landuse-Data\Processed\lookups\lvestock_parameter.csv"

In [14]:
#read grazing management table
df_grazing = pd.read_csv(grazing_management_csv)

#add field area from shapefile 
field_shp_df = gpd.read_file(field_shp)
field_shp_df['Area'] = field_shp_df.geometry.area / 10000
field_shp_df = field_shp_df.rename(columns={"LAND_ID": "Location"})
reach_deposit_df = df_grazing.merge(field_shp_df, how = 'inner', on = 'Location')
reach_deposit_df.drop('geometry', inplace=True, axis=1)
reach_deposit_df

,Scenario,Location,Year,GraMon,GraDay,Days,Ani_ID,Ani_adult,GR_Density,DayFra,Source,SourceID,Dugout_ID,Access,Fencing,StreamAniPerc,Drinking_time,BankK_Change,Area
0,1,1162,1,5,1,180,2,100,1.0,1,1,32,0,0,0,0,0.02,0.3,1.26
1,1,1162,2,5,1,180,2,100,1.0,1,1,32,0,0,0,0,0.02,0.3,1.26
2,1,1162,3,5,1,180,2,100,1.0,1,1,32,0,0,0,0,0.02,0.3,1.26
3,1,1162,4,5,1,180,2,100,1.0,1,1,32,0,0,0,0,0.02,0.3,1.26
4,1,1162,5,5,1,180,2,100,1.0,1,1,32,0,0,0,0,0.02,0.3,1.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4602,1,6905,30,5,1,180,2,100,1.0,1,1,92,0,0,0,0,0.02,0.3,0.18
4603,1,7006,30,5,1,180,2,100,1.0,1,1,66,0,0,0,0,0.02,0.3,0.72
4604,1,7071,30,5,1,180,2,100,1.0,1,1,87,0,0,0,0,0.02,0.3,1.17
4605,1,7084,30,5,1,180,2,100,1.0,1,1,87,0,0,0,0,0.02,0.3,0.27
4606,1,7649,30,5,1,180,2,100,1.0,1,1,99,0,0,0,0,0.02,0.3,3.06

In [19]:
np.repeat(reach_deposit_df.iloc[[0]].values,180,axis=0)

array([[1.000e+00, 1.162e+03, 1.000e+00, ..., 2.000e-02, 3.000e-01,
        1.260e+00],
       [1.000e+00, 1.162e+03, 1.000e+00, ..., 2.000e-02, 3.000e-01,
        1.260e+00],
       [1.000e+00, 1.162e+03, 1.000e+00, ..., 2.000e-02, 3.000e-01,
        1.260e+00],
       ...,
       [1.000e+00, 1.162e+03, 1.000e+00, ..., 2.000e-02, 3.000e-01,
        1.260e+00],
       [1.000e+00, 1.162e+03, 1.000e+00, ..., 2.000e-02, 3.000e-01,
        1.260e+00],
       [1.000e+00, 1.162e+03, 1.000e+00, ..., 2.000e-02, 3.000e-01,
        1.260e+00]])

In [22]:
reach_deposit_df.iloc[0].Days

180.0

In [ ]:
def get_month_day(year, month, day, adddays):

In [20]:
df = pd.DataFrame(np.repeat(reach_deposit_df.iloc[[0]].values,reach_deposit_df.iloc[0].Days,axis=0),columns=reach_deposit_df.columns)
df["Month"] =

,Scenario,Location,Year,GraMon,GraDay,Days,Ani_ID,Ani_adult,GR_Density,DayFra,Source,SourceID,Dugout_ID,Access,Fencing,StreamAniPerc,Drinking_time,BankK_Change,Area
0,1.0,1162.0,1.0,5.0,1.0,180.0,2.0,100.0,1.0,1.0,1.0,32.0,0.0,0.0,0.0,0.0,0.02,0.3,1.26
1,1.0,1162.0,1.0,5.0,1.0,180.0,2.0,100.0,1.0,1.0,1.0,32.0,0.0,0.0,0.0,0.0,0.02,0.3,1.26
2,1.0,1162.0,1.0,5.0,1.0,180.0,2.0,100.0,1.0,1.0,1.0,32.0,0.0,0.0,0.0,0.0,0.02,0.3,1.26
3,1.0,1162.0,1.0,5.0,1.0,180.0,2.0,100.0,1.0,1.0,1.0,32.0,0.0,0.0,0.0,0.0,0.02,0.3,1.26
4,1.0,1162.0,1.0,5.0,1.0,180.0,2.0,100.0,1.0,1.0,1.0,32.0,0.0,0.0,0.0,0.0,0.02,0.3,1.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,1.0,1162.0,1.0,5.0,1.0,180.0,2.0,100.0,1.0,1.0,1.0,32.0,0.0,0.0,0.0,0.0,0.02,0.3,1.26
176,1.0,1162.0,1.0,5.0,1.0,180.0,2.0,100.0,1.0,1.0,1.0,32.0,0.0,0.0,0.0,0.0,0.02,0.3,1.26
177,1.0,1162.0,1.0,5.0,1.0,180.0,2.0,100.0,1.0,1.0,1.0,32.0,0.0,0.0,0.0,0.0,0.02,0.3,1.26
178,1.0,1162.0,1.0,5.0,1.0,180.0,2.0,100.0,1.0,1.0,1.0,32.0,0.0,0.0,0.0,0.0,0.02,0.3,1.26
179,1.0,1162.0,1.0,5.0,1.0,180.0,2.0,100.0,1.0,1.0,1.0,32.0,0.0,0.0,0.0,0.0,0.02,0.3,1.26

In [21]:
df.index

RangeIndex(start=0, stop=180, step=1)

In [ ]:
#repeat each row for each grazing day

for index in reach_deposit_df.index:
    reach_deposit_df.iloc[index].values

reach_deposit_df

In [8]:
one_year_df = reach_deposit_df[reach_deposit_df["Year"] == 3]
one_year_pivot = pd.pivot_table(one_year_df, values="Area", index="SourceID", aggfunc=np.sum)
one_year_pivot

NameError: name 'np' is not defined