In [1]:
from whitebox_workflows import WbEnvironment
from whitebox_workflows import WbEnvironment, Raster
from io import StringIO
import pandas as pd

In [2]:
wbe = WbEnvironment()

print(wbe.version())

Whitebox Workflows for Python v1.2.8 by Whitebox Geospatial Inc.
Developed by Dr. John B. Lindsay, (c) 2022-2024

Description:
Whitebox Workflows for Python is an advanced geospatial data analysis platform
and Python extension module.

In [3]:
vector = wbe.read_vector(r"C:\Work\imWEBs\Junzhi Liu\Zhangbin\Wetland\run_data\run_data\Watershed_line.shp")
vector.header

In [5]:
type(vector.header.shape_type)

VectorGeometryType

In [5]:
wbe.available_functions()

Available Methods (LicenseType.WbW):
1. adaptive_filter                                2. add_point_coordinates_to_table
3. aggregate_raster                               4. anova
5. ascii_to_las                                   6. aspect
7. attribute_correlation                          8. attribute_histogram
9. attribute_scattergram                          10. available_functions
11. average_flowpath_slope                        12. average_normal_vector_angular_deviation
13. average_overlay                               14. average_upslope_flowpath_length
15. balance_contrast_enhancement                  16. basins
17. bilateral_filter                              18. block_maximum
19. block_minimum                                 20. bool_and
21. bool_not                                      22. bool_or
23. bool_xor                                      24. boundary_shape_complexity
25. breach_depressions_least_cost                 26. breach_single_cell_pits
27. buffer_raster                                 28. burn_streams_at_roads
29. centroid_raster                               30. centroid_vector
31. change_vector_analysis                        32. check_in_license
33. circular_variance_of_aspect                   34. classify_buildings_in_lidar
35. classify_overlap_points                       36. clean_vector
37. clip                                          38. clip_lidar_to_polygon
39. clip_raster_to_polygon                        40. closing
41. clump                                         42. compactness_ratio
43. conservative_smoothing_filter                 44. construct_vector_tin
45. contours_from_points                          46. contours_from_raster
47. convert_nodata_to_zero                        48. corner_detection
49. correct_vignetting                            50. cost_allocation
51. cost_distance                                 52. cost_pathway
53. count_if                                      54. create_colour_composite
55. create_plane                                  56. crispness_index
57. cross_tabulation                              58. csv_points_to_vector
59. cumulative_distribution                       60. d8_flow_accum
61. d8_mass_flux                                  62. d8_pointer
63. depth_in_sink                                 64. deviation_from_mean_elevation
65. deviation_from_regional_direction             66. diff_of_gaussians_filter
67. difference                                    68. difference_from_mean_elevation
69. dinf_flow_accum                               70. dinf_mass_flux
71. dinf_pointer                                  72. direct_decorrelation_stretch
73. directional_relief                            74. dissolve
75. distance_to_outlet                            76. diversity_filter
77. downslope_distance_to_stream                  78. downslope_flowpath_length
79. downslope_index                               80. edge_contamination
81. edge_density                                  82. edge_preserving_mean_filter
83. edge_proportion                               84. elev_relative_to_min_max
85. elev_relative_to_watershed_min_max            86. elevation_above_pit
87. elevation_above_stream                        88. elevation_above_stream_euclidean
89. elevation_percentile                          90. eliminate_coincident_points
91. elongation_ratio                              92. embankment_mapping
93. emboss_filter                                 94. erase
95. erase_polygon_from_lidar                      96. erase_polygon_from_raster
97. euclidean_allocation                          98. euclidean_distance
99. export_table_to_csv                           100. exposure_towards_wind_flux
101. extend_vector_lines                          102. extract_by_attribute
103. extract_nodes                                104. extract_raster_values_at_points
105. extract_streams                              106. extract_valleys
107. farthest_channel_head                        108. fast_almost_gaussian_filter
109. fd8_flow_accum                               110. fd8_pointer
111. feature_preserving_smoothing                 112. fetch_analysis
113. fill_burn                                    114. fill_depressions
115. fill_depressions_planchon_and_darboux        116. fill_depressions_wang_and_liu
117. fill_missing_data                            118. fill_pits
119. filter_lidar_classes                         120. filter_lidar_noise
121. filter_lidar_scan_angles                     122. filter_raster_features_by_area
123. find_flightline_edge_points                  124. find_lowest_or_highest_points
125. find_main_stem                               126. find_noflow_cells
127. find_parallel_flow                           128. find_patch_edge_cells
129. find_ridges                                  130. flatten_lakes
131. flightline_overlap                           132. flip_image
133. flood_order                                  134. flow_accum_full_workflow
135. flow_length_diff                             136. gamma_correction
137. gaussian_contrast_stretch                    138. gaussian_curvature
139. gaussian_filter                              140. geomorphons
141. hack_stream_order                            142. heat_map
143. height_above_ground                          144. hexagonal_grid_from_raster_base
145. hexagonal_grid_from_vector_base              146. high_pass_filter
147. high_pass_median_filter                      148. highest_position
149. hillshade                                    150. hillslopes
151. histogram_equalization                       152. histogram_matching
153. histogram_matching_two_images                154. hole_proportion
155. horizon_angle                                156. horton_ratios
157. horton_stream_order                          158. hypsometric_analysis
159. hypsometrically_tinted_hillshade             160. idw_interpolation
161. ihs_to_rgb                                   162. image_autocorrelation
163. image_correlation                            164. image_correlation_neighbourhood_analysis
165. image_regression                             166. image_stack_profile
167. impoundment_size_index                       168. individual_tree_detection
169. insert_dams                                  170. integral_image_transform
171. intersect                                    172. isobasins
173. jenson_snap_pour_points                      174. join_tables
175. k_means_clustering                           176. k_nearest_mean_filter
177. kappa_index                                  178. ks_normality_test
179. laplacian_filter                             180. laplacian_of_gaussians_filter
181. las_to_ascii                                 182. las_to_shapefile
183. layer_footprint_raster                       184. layer_footprint_vector
185. lee_filter                                   186. length_of_upstream_channels
187. lidar_block_maximum                          188. lidar_block_minimum
189. lidar_classify_subset                        190. lidar_colourize
191. lidar_construct_vector_tin                   192. lidar_digital_surface_model
193. lidar_elevation_slice                        194. lidar_ground_point_filter
195. lidar_hex_bin                                196. lidar_hillshade
197. lidar_histogram                              198. lidar_idw_interpolation
199. lidar_info                                   200. lidar_join
201. lidar_kappa                                  202. lidar_nearest_neighbour_gridding
203. lidar_point_density                          204. lidar_point_stats
205. lidar_radial_basis_function_interpolation    206. lidar_ransac_planes
207. lidar_remove_outliers                        208. lidar_rooftop_analysis
209. lidar_segmentation                           210. lidar_segmentation_based_filter
211. lidar_shift                                  212. lidar_thin
213. lidar_thin_high_density                      214. lidar_tile
215. lidar_tile_footprint                         216. lidar_tin_gridding
217. lidar_tophat_transform                       218. line_detection_filter
219. line_intersections                           220. line_thinning
221. linearity_index                              222. lines_to_polygons
223. list_unique_values                           224. list_unique_values_raster
225. long_profile                                 226. long_profile_from_points
227. longest_flowpath                             228. lowest_position
229. majority_filter                              230. map_off_terrain_objects
231. max_absolute_overlay                         232. max_anisotropy_dev
233. max_anisotropy_dev_signature                 234. max_branch_length
235. max_difference_from_mean                     236. max_downslope_elev_change
237. max_elevation_dev_signature                  238. max_elevation_deviation
239. max_overlay                                  240. max_upslope_elev_change
241. max_upslope_flowpath_length                  242. max_upslope_value
243. maximal_curvature                            244. maximum_filter
245. mdinf_flow_accum                             246. mean_curvature
247. mean_filter                                  248. median_filter
249. medoid                                       250. merge_line_segments
251. merge_table_with_csv                         252. merge_vectors
253. min_absolute_overlay                         254. min_downslope_elev_change
255. min_max_contrast_stretch                     256. min_overlay
257. minimal_curvature                            258. minimum_bounding_box
259. minimum_bounding_circle                      260. minimum_bounding_envelope
261. minimum_convex_hull                          262. minimum_filter
263. modified_k_means_clustering                  264. modified_shepard_interpolation
265. modify_nodata_value                          266. mosaic
267. mosaic_with_feathering                       268. multidirectional_hillshade
269. multipart_to_singlepart                      270. multiply_overlay
271. multiscale_elevation_percentile              272. multiscale_roughness
273. multiscale_roughness_signature               274. multiscale_std_dev_normals
275. multiscale_std_dev_normals_signature         276. multiscale_topographic_position_image
277. narrowness_index                             278. natural_neighbour_interpolation
279. nearest_neighbour_interpolation              280. new_lidar
281. new_raster                                   282. new_raster_from_base_raster
283. new_raster_from_base_vector                  284. new_vector
285. normal_vectors                               286. normalize_lidar
287. normalized_difference_index                  288. num_downslope_neighbours
289. num_inflowing_neighbours                     290. olympic_filter
291. opening                                      292. otsu_thresholding
293. paired_sample_t_test                         294. panchromatic_sharpening
295. patch_orientation                            296. pennock_landform_classification
297. percent_elev_range                           298. percent_equal_to
299. percent_greater_than                         300. percent_less_than
301. percentage_contrast_stretch                  302. percentile_filter
303. perimeter_area_ratio                         304. pick_from_list
305. plan_curvature                               306. polygon_area
307. polygon_long_axis                            308. polygon_perimeter
309. polygon_short_axis                           310. polygonize
311. polygons_to_lines                            312. prewitt_filter
313. principal_component_analysis                 314. print_geotiff_tags
315. profile                                      316. profile_curvature
317. qin_flow_accumulation                        318. quantiles
319. quinn_flow_accumulation                      320. radial_basis_function_interpolation
321. radius_of_gyration                           322. raise_walls
323. random_field                                 324. random_sample
325. range_filter                                 326. raster_area
327. raster_calculator                            328. raster_cell_assignment
329. raster_histogram                             330. raster_perimeter
331. raster_streams_to_vector                     332. raster_summary_stats
333. raster_to_vector_lines                       334. raster_to_vector_points
335. raster_to_vector_polygons                    336. rasterize_streams
337. read_lidar                                   338. read_lidars
339. read_raster                                  340. read_rasters
341. read_vector                                  342. read_vectors
343. reciprocal                                   344. reclass
345. reclass_equal_interval                       346. rectangular_grid_from_raster_base
347. rectangular_grid_from_vector_base            348. reinitialize_attribute_table
349. related_circumscribing_circle                350. relative_aspect
351. relative_stream_power_index                  352. relative_topographic_position
353. remove_duplicates                            354. remove_off_terrain_objects
355. remove_polygon_holes                         356. remove_short_streams
357. remove_spurs                                 358. repair_stream_vector_topology
359. resample                                     360. rescale_value_range
361. rgb_to_ihs                                   362. rho8_flow_accum
363. rho8_pointer                                 364. roberts_cross_filter
365. root_mean_square_error                       366. ruggedness_index
367. scharr_filter                                368. sediment_transport_index
369. select_tiles_by_polygon                      370. set_nodata_value
371. shape_complexity_index_raster                372. shape_complexity_index_vector
373. shreve_stream_magnitude                      374. sigmoidal_contrast_stretch
375. singlepart_to_multipart                      376. sink
377. slope                                        378. slope_vs_elev_plot
379. smooth_vectors                               380. snap_pour_points
381. sobel_filter                                 382. spherical_std_dev_of_normals
383. split_colour_composite                       384. split_vector_lines
385. split_with_lines                             386. standard_deviation_contrast_stretch
387. standard_deviation_filter                    388. standard_deviation_of_slope
389. standard_deviation_overlay                   390. stochastic_depression_analysis
391. strahler_order_basins                        392. strahler_stream_order
393. stream_link_class                            394. stream_link_identifier
395. stream_link_length                           396. stream_link_slope
397. stream_slope_continuous                      398. subbasins
399. sum_overlay                                  400. surface_area_ratio
401. symmetrical_difference                       402. tangential_curvature
403. thicken_raster_line                          404. time_in_daylight
405. tin_interpolation                            406. tophat_transform
407. topographic_hachures                         408. topological_stream_order
409. total_curvature                              410. total_filter
411. trace_downslope_flowpaths                    412. travelling_salesman_problem
413. trend_surface                                414. trend_surface_vector_points
415. tributary_identifier                         416. turning_bands_simulation
417. two_sample_ks_test                           418. union
419. unnest_basins                                420. unsharp_masking
421. update_nodata_cells                          422. upslope_depression_storage
423. user_defined_weights_filter                  424. vector_hex_binning
425. vector_lines_to_raster                       426. vector_points_to_raster
427. vector_polygons_to_raster                    428. vector_stream_network_analysis
429. version                                      430. viewshed
431. visibility_index                             432. voronoi_diagram
433. watershed                                    434. watershed_from_raster_pour_points
435. weighted_overlay                             436. weighted_sum
437. wetness_index                                438. wilcoxon_signed_rank_test
439. write_function_memory_insertion              440. write_lidar
441. write_raster                                 442. write_text
443. write_vector                                 444. z_scores
445. zonal_statistics

In [6]:
print(wbe.working_directory)

In [40]:
def get_category_area(raster:Raster)->dict: 
    raster_area = wbe.raster_area(raster)

    #the area is saved in a string. we will need to parse to get the dicitionary.
    print(raster_area[1])
    pd.read_csv(StringIO(raster_area[1]),skiprows=1, index_col=0,names=["ID","Area_Ha"])
    strs = raster_area[1].split("\n")
    areas = {}
    for str in strs:
        if 'Class' in str or len(str) <= 0:
            continue
        id_area_array = str.split(",")
        areas[int(id_area_array[0])] = float(id_area_array[1])

    return areas

    

subbasin_file = r"C:\Work\imWEBs\Interface\BRC_TIFFs\subbasin.tif"
subbasin_raster = wbe.read_raster(subbasin_file)
areas = get_category_area(subbasin_raster)
print(list(areas.keys())[0])
print(list(areas.keys())[-1])

Class,Area
1,788904.9542789336
2,1214321.2777467563
3,550169.2115733625
4,110392.84343152314
5,210015.65335753185
6,90647.78200474664
7,88852.77642049422
8,46670.145190562616
9,40387.625645679196
10,114880.35739215415
11,87955.27362836801
12,17052.55305039788
13,86160.26804411561
14,32310.100516543356
15,12565.039089766859
16,7180.022337009634
17,12565.039089766859
18,131932.910442552
19,33207.60330866956
20,5385.016752757226
21,13462.541881893063
22,8077.525129135838
23,35900.11168504817
24,82570.25687561081
25,28720.08934803854
26,64620.201033086705
27,122957.88252129
28,6282.519544883429
29,94237.79317325146
30,10770.03350551445
31,8077.525129135837
32,83467.759667737
33,87057.77083624182
34,8975.02792126204
35,20642.5642189027
36,82570.25687561078
37,15257.547466145472
38,110392.84343152311
39,39490.12285355299
40,215400.67011028904
41,1795.0055842524084
42,41285.1284378054
43,11667.536297640656
44,4487.51396063102
45,31412.59772441715
46,3590.011168504817
47,39490.12285355299
48,17950.055842524085
49,19745.061426776494
50,27822.586555912334
51,23335.07259528131
52,6282.519544883429
53,26925.08376378613
54,9872.530713388245
55,15257.547466145472
56,29617.592140164743
57,190270.59193075533
58,11667.536297640654
59,42182.6312299316
60,73595.22895434876
61,62825.1954488343
62,65517.70382521291
63,37695.11726930058
64,12565.039089766859
65,12565.039089766859
66,462213.9379449945
67,17052.55305039788
68,12565.039089766859
69,44875.13960631021
70,8077.525129135838
71,11667.536297640654
72,941480.4289403891
73,19745.061426776494
74,35900.11168504817
75,15257.547466145472
76,23335.07259528131
77,12565.039089766859
78,17052.55305039788
79,314125.9772441713
80,273738.3515984923
81,15257.547466145472
82,14360.044674019267
83,6282.519544883429
84,79877.74849923217
85,6282.519544883429
86,173218.0388803574
87,30515.094932290947
88,37695.11726930058
89,15257.547466145472
90,87955.27362836803
91,12565.039089766859
92,12565.039089766859
93,31412.59772441715
94,54747.67031969846
95,122957.88252128998
96,3590.011168504817
97,14360.044674019267
98,34105.10610079576
99,14360.044674019267
100,34105.10610079576
101,8077.525129135837
102,46670.14519056262
103,72697.72616222255
104,3590.011168504817
105,16155.050258271676
106,7180.022337009634
107,589659.3344269155
108,122060.37972916379
109,9872.530713388245
110,6282.519544883429
111,17950.055842524085
112,20642.5642189027
113,6282.519544883429
114,558246.7367024982
115,31412.59772441715
116,26925.08376378613
117,87057.77083624182
118,22437.569803155107
119,16155.050258271676
120,32310.100516543356
121,73595.22895434876
122,14360.044674019267
123,20642.5642189027
124,8975.027921262043
125,30515.094932290947
126,80775.25129135838
127,16155.050258271676
128,23335.07259528131
129,31412.59772441715
130,70902.72057797015
131,24232.575387407516
132,35900.11168504817
133,8077.525129135838
134,54747.67031969845
135,8077.525129135838
136,8975.02792126204
137,159755.49699846437
138,5385.016752757225
139,15257.547466145472
140,14360.044674019267
141,83467.759667737
142,45772.64239843642
143,1795.0055842524084
144,14360.044674019267
145,13462.541881893063
146,140907.9383638141
147,49362.65356694123
148,24232.575387407516
149,83467.759667737
150,157062.98862208574
151,31412.59772441715
152,9872.530713388245
153,24232.575387407516
154,103212.8210945135
155,12565.039089766859
156,6282.519544883429
157,74492.73174647495
158,72697.72616222255
159,4487.51396063102
160,63722.6982409605
161,29617.592140164743
162,75390.23453860116
163,18847.55863465029
164,15257.547466145472
165,34105.10610079576
166,9872.530713388245
167,34105.10610079576
168,49362.65356694124
169,278225.8655591232
170,23335.07259528131
171,6282.519544883429
172,7180.022337009634
173,165140.51375122162
174,28720.08934803854
175,26027.580971659925
176,77185.24012285357
177,8077.525129135838
178,15257.547466145472
179,6282.519544883429
180,3590.011168504817
181,206425.64218902698
182,93340.29038112525
183,152575.47466145473
184,897.5027921262042
185,13462.541881893063
186,25130.07817953372
187,8077.525129135838
188,11667.536297640654
189,5385.016752757225
190,24232.575387407516
191,23335.07259528131
192,38592.62006142679
193,17950.055842524085
194,2692.5083763786124
195,65517.70382521291
196,5385.016752757225
197,9872.530713388245
198,12565.039089766859
199,70902.72057797013
200,22437.569803155107
201,58337.68148820327
202,17950.055842524085
203,5385.016752757225
204,120265.37414491137
205,4487.513960631021
206,49362.65356694123
207,9872.530713388245
208,35002.60889292197
209,47567.647982688824
210,328486.0219181906
211,94237.79317325146
212,23335.07259528131
213,6282.519544883429
214,15257.547466145472
215,13462.541881893063
216,166038.0165433478
217,8975.027921262043
218,23335.07259528131
219,8077.525129135838
220,45772.642398436416
221,13462.541881893063
222,9872.530713388245
223,17052.55305039788
224,112187.84901577553
225,4487.513960631021
226,59235.18428032948
227,42182.6312299316
228,14360.044674019267
229,56542.675903950876
230,78980.24570710598
231,26027.580971659925
232,14360.044674019267
233,19745.061426776494
234,26027.580971659925
235,148985.4634929499
236,68210.21220159152
237,13462.541881893063
238,45772.642398436416
239,81672.75408348459
240,9872.530713388245
241,34105.10610079576
242,31412.59772441715
243,6282.519544883429
244,148087.9607008237
245,6282.519544883429
246,62825.195448834296
247,70902.72057797013
248,344641.07217646216
249,23335.07259528131
250,50260.15635906744
251,26925.08376378613
252,113982.85460002796
253,10770.03350551445
254,49362.65356694123
255,17950.055842524085
256,3590.011168504817
257,45772.642398436416
258,7180.022337009634
259,66415.20661733912
260,22437.569803155107
261,6282.519544883429
262,55645.17311182467
263,60132.68707245568
264,7180.022337009634
265,29617.592140164743
266,13462.541881893063
267,12565.039089766859
268,18847.55863465029
269,50260.156359067434
270,6282.519544883429
271,43080.134022057806
272,12565.039089766859
273,1795.0055842524084
274,43080.1340220578
275,37695.11726930058
276,57440.17869607706
277,8975.02792126204
278,13462.541881893063
279,43977.63681418401
280,126547.8936897948
281,7180.022337009634
282,17950.055842524085
283,17052.55305039788
284,3590.011168504817
285,166935.519335474
286,96032.79875750386
287,22437.569803155107
288,13462.541881893063
289,8077.525129135838
290,145395.4523244451
291,130137.90485829963
292,10770.03350551445
293,11667.536297640654
294,12565.039089766859
295,12565.039089766859
296,17052.55305039788
297,215400.67011028904
298,26925.08376378613
299,45772.642398436416
300,12565.039089766859
301,45772.642398436416
302,13462.541881893063
303,1336381.6574759206
304,4487.513960631021
305,32310.100516543356
306,29617.592140164743
307,19745.061426776494
308,20642.5642189027
309,21540.067011028903
310,48465.15077481503
311,24232.575387407516
312,53850.16752757226
313,35002.60889292197
314,14360.044674019267
315,11667.536297640654
316,17950.055842524085
317,30515.094932290947
318,14360.044674019267
319,112187.84901577554
320,63722.698240960504
321,77185.24012285356
322,19745.061426776494
323,42182.631229931605
324,58337.68148820327
325,21540.067011028903
326,2692.5083763786124
327,3590.011168504817
328,12565.039089766859
329,24232.575387407516
330,14360.044674019267
331,30515.094932290947
332,31412.59772441715
333,81672.75408348459
334,96930.30154963005
335,17052.55305039788
336,30515.094932290947
337,14360.044674019267
338,15257.547466145472
339,10770.03350551445
340,43977.636814184014
341,12565.039089766859
342,21540.067011028903
343,57440.17869607707
344,13462.541881893063
345,28720.08934803854
346,14360.044674019267
347,64620.201033086705
348,10770.03350551445
349,121162.87693703757
350,6282.519544883429
351,32310.100516543356
352,9872.530713388247
353,29617.592140164743
354,370668.653148122
355,99622.80992600867
356,3590.011168504817
357,48465.15077481503
358,21540.067011028903
359,48465.15077481503
360,243223.25666620137
361,8975.027921262043
362,37695.11726930058
363,14360.044674019267
364,12565.039089766859
365,25130.07817953372
366,49362.65356694123
367,118470.36856065897
368,96032.79875750386
369,84365.26245986321
370,3590.011168504817
371,6282.519544883429
372,17052.55305039788
373,35002.60889292197
374,9872.530713388245
375,14360.044674019267
376,78082.74291497977
377,62825.195448834296
378,8975.027921262043
379,203733.13381264836
380,52055.16194331984
381,6282.519544883429
382,8077.525129135837
383,10770.03350551445
384,15257.547466145472
385,6282.519544883429
386,18847.55863465029
387,21540.067011028903
388,88852.77642049422
389,112187.84901577556
390,170525.5305039788
391,40387.62564567919
392,29617.592140164743
393,6282.519544883429
394,17950.055842524085
395,21540.067011028903
396,75390.23453860116
397,15257.547466145472
398,17950.055842524085
399,33207.60330866956
400,12565.039089766859
401,24232.575387407516
402,30515.094932290947
403,5385.016752757225
404,35002.60889292197
405,8975.02792126204
406,99622.80992600866
407,288995.8990646377
408,2692.5083763786124
409,8975.02792126204
410,70005.21778584394
411,10770.033505514451
412,38592.62006142679
413,27822.586555912334
414,33207.60330866956
415,14360.044674019267
416,23335.07259528131
417,15257.547466145472
418,5385.016752757225
419,17052.55305039788
420,61927.692656708095
421,31412.59772441715
422,4487.513960631021
423,295278.4186095211
424,25130.07817953372
425,12565.039089766859
426,25130.07817953372
427,15257.547466145472
428,20642.5642189027
429,55645.17311182466
430,15257.547466145472
431,17950.055842524085
432,723387.2504537203
433,27822.586555912334
434,18847.55863465029
435,12565.039089766859
436,18847.55863465029
437,14360.044674019267
438,50260.15635906744
439,27822.586555912334
440,9872.530713388245
441,14360.044674019267
442,219888.18407092005
443,14360.044674019267
444,169628.0277118526
445,113085.35180790175
446,24232.575387407516
447,316818.48562054994
448,26925.08376378613
449,897.5027921262042
450,9872.530713388245
451,78082.74291497978
452,21540.067011028903
453,24232.575387407516
454,31412.59772441715
455,8077.525129135837
456,8077.525129135837
457,113982.85460002795
458,126547.8936897948
459,30515.094932290947
460,59235.18428032948
461,6282.519544883429
462,12565.039089766859
463,32310.100516543356
464,897.5027921262042
465,56542.67590395087
466,4487.513960631021
467,49362.65356694123
468,23335.07259528131
469,472086.46865838266
470,61030.189864581895
471,7180.022337009634
472,5385.016752757225
473,48465.15077481503
474,26027.580971659925
475,12565.039089766859
476,9872.530713388245
477,86160.26804411561
478,3590.011168504817
479,24232.575387407516
480,42182.6312299316
481,74492.73174647495
482,15257.547466145472
483,31412.59772441715
484,15257.547466145472
485,10770.03350551445
486,74492.73174647495
487,20642.5642189027
488,35002.60889292197
489,11667.536297640654
490,2692.5083763786124
491,166038.0165433478
492,35002.60889292197
493,16155.050258271676
494,34105.10610079576
495,23335.07259528131
496,12565.039089766859
497,14360.044674019267
498,95135.29596537765
499,4487.513960631021
500,41285.1284378054
501,43977.63681418401
502,11667.536297640654
503,8077.525129135838
504,14360.044674019267
505,2692.5083763786124
506,47567.647982688824
507,61030.18986458188
508,39490.12285355299
509,311433.46886779275
510,89750.27921262041
511,21540.067011028903
512,21540.067011028903
513,8975.02792126204
514,28720.08934803854
515,119367.87135278518
516,50260.156359067434
517,37695.11726930058
518,46670.145190562616
519,16155.050258271676
520,5385.016752757225
521,8975.027921262043
522,77185.24012285357
523,61030.189864581895
524,21540.067011028903
525,76287.73733072737
526,197450.61426776493
527,10770.03350551445
528,17052.55305039788
529,36797.61447717438
530,31412.59772441715
531,12565.039089766859
532,30515.094932290944
533,13462.541881893065
534,8077.525129135838
535,60132.68707245569
536,86160.26804411561
537,14360.044674019267
538,129240.40206617344
539,1795.0055842524084
540,70005.21778584394
541,29617.592140164743
542,29617.592140164743
543,54747.67031969847
544,8975.02792126204
545,11667.536297640654
546,11667.536297640656
547,18847.55863465029
548,28720.08934803854
549,12565.039089766859
550,38592.62006142678
551,49362.65356694123
552,15257.547466145472
553,22437.569803155107
554,11667.536297640654
555,59235.18428032948
556,17950.055842524085
557,14360.044674019267
558,3590.011168504817
559,316818.48562055
560,12565.039089766859
561,48465.15077481503
562,33207.60330866956
563,28720.08934803854
564,55645.17311182466
565,7180.022337009634
566,62825.1954488343
567,61927.692656708095
568,190270.5919307553
569,8077.525129135838
570,32310.100516543356
571,15257.547466145472
572,8975.02792126204
573,13462.541881893063
574,9872.530713388247
575,16155.050258271676
576,15257.547466145472
577,9872.530713388245
578,157062.98862208577
579,6282.519544883429
580,30515.094932290947
581,101417.81551026108
582,8975.02792126204
583,391311.21736702457
584,27822.586555912334
585,58337.68148820328
586,6282.519544883429
587,6282.519544883429
588,58337.681488203285
589,62825.195448834296
590,24232.575387407516
591,5385.016752757225
592,14360.044674019267
593,15257.547466145472
594,34105.10610079576
595,16155.050258271676
596,8975.02792126204
597,20642.5642189027
598,4487.51396063102
599,29617.592140164743
600,17052.55305039788
601,21540.067011028903
602,25130.07817953372
603,7180.022337009634
604,23335.07259528131
605,101417.81551026109
606,152575.47466145473
607,3590.011168504817
608,6282.519544883429
609,362591.1280189861
610,23335.07259528131
611,15257.547466145472
612,155267.98303783333
613,68210.21220159152
614,7180.022337009634
615,70005.21778584394
616,43977.63681418401
617,14360.044674019267
618,42182.6312299316
619,116675.36297640656
620,27822.586555912334
621,16155.050258271676
622,107700.33505514452
623,3590.011168504817
624,218990.68127879384
625,33207.60330866956
626,24232.575387407516
627,3590.011168504817
628,12565.039089766859
629,8077.525129135838
630,131035.40765042583
631,33207.60330866956
632,26925.08376378613
633,35900.11168504817
634,43080.134022057806
635,46670.14519056262
636,116675.36297640656
637,6282.519544883429
638,6282.519544883429
639,45772.642398436416
640,52055.16194331985
641,24232.575387407516
642,12565.039089766859
643,6282.519544883429
644,3590.011168504817
645,33207.60330866956
646,18847.55863465029
647,8077.525129135837
648,5385.016752757225
649,76287.73733072737
650,26027.580971659925
651,20642.5642189027
652,17052.55305039788
653,53850.16752757226
654,52952.66473544606
655,8975.027921262043
656,9872.530713388245
657,15257.547466145472
658,30515.094932290947
659,88852.77642049422
660,50260.15635906744
661,21540.067011028903
662,16155.050258271676
663,235145.73153706553
664,8975.02792126204
665,53850.16752757226
666,13462.541881893063
667,8077.525129135837
668,14360.044674019267
669,17950.055842524085
670,54747.67031969846
671,11667.536297640654
672,78082.74291497977
673,100520.31271813488
674,29617.592140164743
675,75390.23453860117
676,67312.70940946531
677,77185.24012285357
678,30515.094932290947
679,70902.72057797013
680,76287.73733072737
681,8975.027921262043
682,148087.9607008237
683,102315.3183023873
684,2548907.929638428
685,7180.022337009634
686,69107.71499371773
687,14360.044674019267
688,8975.02792126204
689,38592.62006142678
690,126547.89368979482
691,40387.625645679196
692,101417.81551026109
693,3590.011168504817
694,8975.027921262043
695,88852.77642049422
696,251300.78179533719
697,23335.07259528131
698,3590.011168504817
699,64620.20103308671
700,26027.580971659925
701,48465.15077481503
702,23335.07259528131
703,8975.027921262043
704,31412.59772441715
705,51157.65915119364
706,46670.14519056262
707,7180.022337009634
708,56542.67590395087
709,34105.10610079576
710,121162.87693703758
711,6282.519544883429
712,1795.0055842524084
713,7180.022337009634
714,36797.61447717438
715,52055.16194331984
716,1754617.9586067332
717,14360.044674019267
718,26027.580971659925
719,14360.044674019267
720,787109.9486946812
721,52055.16194331985
722,35900.11168504817
723,9872.530713388245
724,26925.08376378613
725,32310.100516543356
726,2692.5083763786124
727,54747.67031969845
728,11667.536297640654
729,27822.586555912334
730,12565.039089766859
731,60132.68707245569
732,4487.51396063102
733,362591.1280189862
734,57440.17869607707
735,6282.519544883429
736,170525.5305039788
737,332076.03308669536
738,42182.6312299316
739,6282.519544883429
740,6282.519544883429
741,9872.530713388247
742,27822.586555912334
743,9872.530713388247
744,21540.067011028903
745,51157.65915119364
746,17950.055842524085
747,27822.586555912334
748,35002.60889292197
749,66415.20661733912
750,47567.647982688824
751,8077.525129135837
752,9872.530713388245
753,43977.63681418401
754,21540.067011028903
755,18847.55863465029
756,102315.31830238728
757,7180.022337009633
758,27822.586555912334
759,19745.061426776494
760,3590.011168504817
761,15257.547466145472
762,40387.625645679196
763,32310.100516543356
764,66415.2066173391
765,110392.84343152313
766,40387.625645679196
767,84365.26245986321
768,12565.039089766859
769,25130.07817953372
770,35002.60889292197
771,57440.17869607707
772,52952.66473544606
773,32310.100516543356
774,7180.022337009634
775,24232.575387407516
776,8077.525129135837
777,14360.044674019267
778,26925.08376378613
779,12565.039089766859
780,6282.519544883429
781,9872.530713388245
782,8975.027921262043
783,74492.73174647496
784,17052.55305039788
785,39490.12285355299
786,56542.67590395087
787,21540.067011028903
788,8975.027921262043
789,52055.16194331985
790,35002.60889292197
791,55645.17311182467
792,22437.569803155107
793,9872.530713388247
794,119367.87135278517
795,11667.536297640654
796,11667.536297640656
797,56542.67590395087
798,31412.59772441715
799,23335.07259528131
800,15257.547466145472
801,42182.631229931605
802,502601.5635906736
803,17052.55305039788
804,17950.055842524085
805,7180.022337009634
806,17052.55305039788
807,130137.90485829962
808,82570.2568756108
809,6282.519544883429
810,12565.039089766859
811,17052.55305039788
812,306048.45211503556
813,16155.050258271676
814,8975.02792126204
815,98725.30713388248
816,7180.022337009633
817,29617.59214016474
818,11667.536297640654
819,11667.536297640656
820,24232.575387407516
821,17950.055842524085
822,3590.011168504817
823,11667.536297640654
824,82570.2568756108
825,14360.044674019267
826,30515.094932290947
827,11667.536297640656
828,8975.027921262043
829,63722.698240960504
830,71800.22337009634
831,89750.27921262043
832,29617.592140164743
833,6282.519544883429
834,8975.027921262043
835,15257.547466145472
836,16155.050258271676
837,9872.530713388245
838,7180.022337009633
839,71800.22337009634
840,25130.07817953372
841,35900.11168504817
842,140907.9383638141
843,5385.016752757225
844,17950.055842524085
845,7180.022337009634
846,35002.60889292197
847,62825.195448834296
848,70902.72057797013
849,51157.65915119364
850,8077.525129135837
851,74492.73174647495
852,16155.050258271676
853,30515.094932290947
854,105905.32947089212
855,61927.692656708095
856,38592.62006142678
857,14360.044674019267
858,17950.055842524085
859,15257.547466145472
860,8975.027921262043
861,19745.061426776494
862,42182.631229931605
863,17052.55305039788
864,17052.55305039788
865,95135.29596537765
866,7180.022337009634
867,73595.22895434876
868,10770.03350551445
869,20642.5642189027
870,20642.5642189027
871,17950.055842524085
872,5385.016752757225
873,140907.9383638141
874,95135.29596537765
875,33207.60330866956
876,10770.03350551445
877,15257.547466145472
878,37695.11726930058
879,5385.016752757225
880,34105.10610079576
881,128342.8992740472
882,69107.71499371773
883,26925.08376378613
884,27822.586555912334
885,9872.530713388245
886,12565.039089766859
887,12565.039089766859
888,41285.1284378054
889,446956.390478849
890,26925.08376378613
891,5385.016752757225
892,31412.59772441715
893,87955.27362836803
894,8975.027921262043
895,32310.100516543356
896,8975.02792126204
897,61927.692656708095
898,49362.65356694124
899,30515.094932290947

In [18]:
wbe.raster_summary_stats(subbasin_raster)

'Number of non-nodata grid cells: 285038\nNumber of nodata grid cells: 288002\nImage minimum: 1\nImage maximum: 4390\nImage range: 4389\nImage total: 638527144\nImage average: 2240.147432973849\nImage variance: 1641185.6734550372\nImage standard deviation: 1281.0876915555145'

In [ ]:
print(subbasin_raster.configs.maximum)
print(subbasin_raster.configs.mimum)
subbasin_areau

In [10]:
type(farm_area)

tuple

In [16]:
strs = farm_area[1].split("\n")
strs
areas = {}
for str in strs:
    if 'Class' in str or len(str) <= 0:
        continue
    id_area_array = str.split(",")
    areas[int(id_area_array[0])] = float(id_area_array[1])

print(list(areas.keys())[0])
print(list(areas.keys())[-1])

1
4390

In [14]:
type(areas.keys)

builtin_function_or_method

In [19]:
prc_avg_raster = wbe.read_raster(r"C:\Work\imWEBs\Interface\BRC_TIFFs\PRC_Acc_Avg.tif")
subbasin_raster = wbe.read_raster(r"C:\Work\imWEBs\Interface\BRC_TIFFs\subbasin.tif")
stats = wbe.zonal_statistics(prc_avg_raster,subbasin_raster,stat_type="mean")

lines = stats[1].split("\n")
num = 0
stats_dic = []
for line in lines:
    num += 1
    if num < 6:
        continue

    value_strs = line.split("|")

    for v in value_strs:
        stats_dic.append({"ID": int(v[1]),
                          "mean": float(v[2])})
    print(value_strs)

    break

(<Raster at 0x21f35a7ac30>,

In [31]:
print(stats[1])

Extract Raster Statistics Summary Report:
Input data raster: PRC_Acc_Avg
Feature definition raster: subbasin
| Feature ID | Mean | Median | Minimum | Maximum | Range | Std. Dev. | Total |
|------------|-----:|-------:|--------:|--------:|------:|----------:|------:|
| 0 | 0.4500 | 0.4347 | 0.4005 | 0.6493 | 0.2488 | 0.0462 | 395.5851 |
| 1 | 0.4367 | 0.4289 | 0.4000 | 0.6229 | 0.2228 | 0.0378 | 590.8673 |
| 2 | 0.4472 | 0.4372 | 0.4002 | 0.6281 | 0.2279 | 0.0386 | 274.1367 |
| 3 | 0.4204 | 0.4208 | 0.4006 | 0.4499 | 0.0493 | 0.0096 | 51.7076 |
| 4 | 0.4283 | 0.4257 | 0.4000 | 0.4958 | 0.0957 | 0.0172 | 100.2331 |
| 5 | 0.4302 | 0.4263 | 0.4011 | 0.4861 | 0.0850 | 0.0189 | 43.4538 |
| 6 | 0.4903 | 0.4669 | 0.4104 | 0.6293 | 0.2189 | 0.0628 | 48.5431 |
| 7 | 0.4288 | 0.4302 | 0.4057 | 0.4622 | 0.0564 | 0.0133 | 22.2993 |
| 8 | 0.4179 | 0.4176 | 0.4016 | 0.4299 | 0.0283 | 0.0078 | 18.8073 |
| 9 | 0.4532 | 0.4372 | 0.4003 | 0.6243 | 0.2240 | 0.0482 | 58.0157 |
| 10 | 0.4553 | 0.4427 | 0.4049 | 0.5813 | 0.1764 | 0.0399 | 44.6215 |
| 11 | 0.4362 | 0.4360 | 0.4140 | 0.4630 | 0.0490 | 0.0120 | 8.2872 |
| 12 | 0.4292 | 0.4281 | 0.4000 | 0.4901 | 0.0900 | 0.0178 | 41.2026 |
| 13 | 0.4340 | 0.4348 | 0.4091 | 0.4522 | 0.0431 | 0.0102 | 15.6231 |
| 14 | 0.4203 | 0.4150 | 0.4017 | 0.4914 | 0.0897 | 0.0224 | 5.8837 |
| 15 | 0.4343 | 0.4345 | 0.4321 | 0.4371 | 0.0051 | 0.0017 | 3.4741 |
| 16 | 0.4356 | 0.4381 | 0.4164 | 0.4506 | 0.0341 | 0.0103 | 6.0989 |
| 17 | 0.4572 | 0.4310 | 0.4041 | 0.6314 | 0.2274 | 0.0568 | 67.2038 |
| 18 | 0.4293 | 0.4256 | 0.4046 | 0.4667 | 0.0621 | 0.0166 | 15.8828 |
| 19 | 0.4298 | 0.4255 | 0.4007 | 0.4979 | 0.0971 | 0.0353 | 2.5787 |
| 20 | 0.4625 | 0.4700 | 0.4056 | 0.5040 | 0.0983 | 0.0271 | 6.9368 |
| 21 | 0.4286 | 0.4255 | 0.4042 | 0.4547 | 0.0505 | 0.0196 | 3.8572 |
| 22 | 0.4330 | 0.4337 | 0.4069 | 0.4598 | 0.0529 | 0.0130 | 17.3187 |
| 23 | 0.4277 | 0.4274 | 0.4014 | 0.4886 | 0.0872 | 0.0161 | 39.3490 |
| 24 | 0.4326 | 0.4296 | 0.4155 | 0.5101 | 0.0946 | 0.0172 | 13.8434 |
| 25 | 0.4261 | 0.4270 | 0.4009 | 0.4593 | 0.0584 | 0.0120 | 30.6806 |
| 26 | 0.4873 | 0.4762 | 0.4057 | 0.6247 | 0.2190 | 0.0591 | 66.7660 |
| 27 | 0.4242 | 0.4246 | 0.4087 | 0.4456 | 0.0368 | 0.0126 | 2.9695 |
| 28 | 0.4271 | 0.4270 | 0.4002 | 0.4738 | 0.0736 | 0.0148 | 44.8466 |
| 29 | 0.4208 | 0.4217 | 0.4035 | 0.4366 | 0.0331 | 0.0093 | 5.0494 |
| 30 | 0.4362 | 0.4319 | 0.4061 | 0.4581 | 0.0520 | 0.0179 | 3.9256 |
| 31 | 0.4312 | 0.4283 | 0.4007 | 0.4879 | 0.0872 | 0.0150 | 40.1013 |
| 32 | 0.4314 | 0.4315 | 0.4001 | 0.4875 | 0.0874 | 0.0167 | 41.8477 |
| 33 | 0.4283 | 0.4277 | 0.4195 | 0.4431 | 0.0236 | 0.0061 | 4.2833 |
| 34 | 0.4234 | 0.4214 | 0.4061 | 0.4445 | 0.0384 | 0.0104 | 9.7391 |
| 35 | 0.4829 | 0.4613 | 0.4104 | 0.6282 | 0.2177 | 0.0551 | 44.4236 |
| 36 | 0.4158 | 0.4087 | 0.4023 | 0.4327 | 0.0304 | 0.0107 | 7.0680 |
| 37 | 0.4487 | 0.4340 | 0.4016 | 0.6322 | 0.2306 | 0.0487 | 55.1863 |
| 38 | 0.4250 | 0.4274 | 0.4005 | 0.4711 | 0.0706 | 0.0141 | 18.6987 |
| 39 | 0.4549 | 0.4388 | 0.4054 | 0.6100 | 0.2046 | 0.0455 | 109.1852 |
| 40 | 0.4111 | 0.4111 | 0.4099 | 0.4123 | 0.0024 | 0.0017 | 0.8221 |
| 41 | 0.4283 | 0.4262 | 0.4104 | 0.4974 | 0.0870 | 0.0134 | 19.7029 |
| 42 | 0.4219 | 0.4214 | 0.4101 | 0.4469 | 0.0368 | 0.0095 | 5.4848 |
| 43 | 0.4339 | 0.4344 | 0.4087 | 0.4580 | 0.0493 | 0.0175 | 2.1697 |
| 44 | 0.4409 | 0.4376 | 0.4000 | 0.4894 | 0.0893 | 0.0206 | 15.4309 |
| 45 | 0.4225 | 0.4237 | 0.4030 | 0.4395 | 0.0365 | 0.0167 | 1.6899 |
| 46 | 0.4452 | 0.4310 | 0.4014 | 0.6194 | 0.2180 | 0.0454 | 19.5885 |
| 47 | 0.4371 | 0.4303 | 0.4100 | 0.4803 | 0.0703 | 0.0221 | 8.7429 |
| 48 | 0.4348 | 0.4381 | 0.4082 | 0.4576 | 0.0494 | 0.0128 | 9.5662 |
| 49 | 0.4589 | 0.4405 | 0.4075 | 0.6203 | 0.2128 | 0.0559 | 14.2263 |
| 50 | 0.4437 | 0.4418 | 0.4023 | 0.4777 | 0.0754 | 0.0174 | 11.5373 |
| 51 | 0.4197 | 0.4165 | 0.4067 | 0.4356 | 0.0289 | 0.0118 | 2.9381 |
| 52 | 0.4227 | 0.4245 | 0.4085 | 0.4415 | 0.0330 | 0.0085 | 12.6821 |
| 53 | 0.4377 | 0.4356 | 0.4286 | 0.4570 | 0.0285 | 0.0083 | 4.8144 |
| 54 | 0.4317 | 0.4316 | 0.4166 | 0.4435 | 0.0269 | 0.0086 | 7.3382 |
| 55 | 0.5255 | 0.5365 | 0.4168 | 0.6398 | 0.2229 | 0.0759 | 17.3403 |
| 56 | 0.4418 | 0.4286 | 0.4038 | 0.5991 | 0.1954 | 0.0377 | 93.6576 |
| 57 | 0.4238 | 0.4238 | 0.4078 | 0.4348 | 0.0270 | 0.0072 | 5.5091 |
| 58 | 0.4948 | 0.4614 | 0.4087 | 0.6462 | 0.2375 | 0.0707 | 23.2568 |
| 59 | 0.4189 | 0.4206 | 0.4000 | 0.4529 | 0.0529 | 0.0111 | 34.3485 |
| 60 | 0.4692 | 0.4396 | 0.4053 | 0.6325 | 0.2272 | 0.0665 | 32.8453 |
| 61 | 0.4262 | 0.4257 | 0.4014 | 0.4588 | 0.0574 | 0.0122 | 31.1140 |
| 62 | 0.4204 | 0.4202 | 0.4023 | 0.4445 | 0.0422 | 0.0110 | 17.6571 |
| 63 | 0.4625 | 0.4665 | 0.4063 | 0.5303 | 0.1239 | 0.0466 | 6.4745 |
| 64 | 0.4231 | 0.4253 | 0.4064 | 0.4383 | 0.0319 | 0.0102 | 5.9235 |
| 65 | 0.4254 | 0.4137 | 0.4001 | 0.5473 | 0.1472 | 0.0348 | 219.0651 |
| 66 | 0.4275 | 0.4284 | 0.4070 | 0.4512 | 0.0442 | 0.0125 | 8.1231 |
| 67 | 0.4302 | 0.4294 | 0.4102 | 0.4457 | 0.0355 | 0.0100 | 6.0229 |
| 68 | 0.4236 | 0.4227 | 0.4028 | 0.4671 | 0.0642 | 0.0112 | 21.1796 |
| 69 | 0.4137 | 0.4111 | 0.4020 | 0.4314 | 0.0294 | 0.0097 | 3.7230 |
| 70 | 0.4336 | 0.4353 | 0.4168 | 0.4486 | 0.0318 | 0.0106 | 5.6369 |
| 71 | 0.4400 | 0.4269 | 0.4000 | 0.6278 | 0.2277 | 0.0416 | 461.5696 |
| 72 | 0.4291 | 0.4280 | 0.4075 | 0.4462 | 0.0387 | 0.0089 | 9.4411 |
| 73 | 0.4264 | 0.4227 | 0.4036 | 0.4698 | 0.0662 | 0.0142 | 17.0574 |
| 74 | 0.5020 | 0.5061 | 0.4138 | 0.5967 | 0.1829 | 0.0613 | 8.5342 |
| 75 | 0.4255 | 0.4230 | 0.4078 | 0.4632 | 0.0553 | 0.0158 | 11.0637 |
| 76 | 0.4269 | 0.4176 | 0.4050 | 0.5326 | 0.1275 | 0.0316 | 5.9770 |
| 77 | 0.4248 | 0.4192 | 0.4139 | 0.4682 | 0.0543 | 0.0142 | 8.0720 |
| 78 | 0.4567 | 0.4450 | 0.4050 | 0.6435 | 0.2385 | 0.0415 | 159.8400 |
| 79 | 0.4421 | 0.4282 | 0.4012 | 0.6207 | 0.2195 | 0.0441 | 134.8466 |
| 80 | 0.4314 | 0.4298 | 0.4102 | 0.4718 | 0.0617 | 0.0162 | 7.3335 |
| 81 | 0.4317 | 0.4269 | 0.4039 | 0.4882 | 0.0843 | 0.0216 | 6.9064 |
| 82 | 0.4161 | 0.4172 | 0.4110 | 0.4198 | 0.0088 | 0.0035 | 2.9124 |
| 83 | 0.4235 | 0.4241 | 0.4003 | 0.4423 | 0.0420 | 0.0091 | 37.6896 |
| 84 | 0.4189 | 0.4177 | 0.4076 | 0.4292 | 0.0216 | 0.0070 | 2.9321 |
| 85 | 0.4262 | 0.4270 | 0.4018 | 0.4642 | 0.0624 | 0.0110 | 82.2627 |
| 86 | 0.5075 | 0.4985 | 0.4210 | 0.5946 | 0.1736 | 0.0574 | 17.2553 |
| 87 | 0.4303 | 0.4286 | 0.4070 | 0.4505 | 0.0435 | 0.0109 | 18.0731 |
| 88 | 0.4344 | 0.4342 | 0.4138 | 0.4743 | 0.0606 | 0.0163 | 7.3846 |
| 89 | 0.4734 | 0.4465 | 0.4113 | 0.6383 | 0.2270 | 0.0609 | 46.3948 |
| 90 | 0.4712 | 0.4698 | 0.4257 | 0.5496 | 0.1240 | 0.0307 | 6.5965 |
| 91 | 0.4183 | 0.4177 | 0.4114 | 0.4242 | 0.0128 | 0.0039 | 5.8561 |
| 92 | 0.4207 | 0.4195 | 0.4000 | 0.4459 | 0.0459 | 0.0115 | 14.7249 |
| 93 | 0.4208 | 0.4197 | 0.4025 | 0.4413 | 0.0388 | 0.0090 | 25.6709 |
| 94 | 0.4227 | 0.4225 | 0.4003 | 0.4685 | 0.0682 | 0.0127 | 57.9145 |
| 95 | 0.4306 | 0.4278 | 0.4220 | 0.4451 | 0.0231 | 0.0104 | 1.7225 |
| 96 | 0.4290 | 0.4301 | 0.4066 | 0.4476 | 0.0410 | 0.0103 | 6.8634 |
| 97 | 0.4363 | 0.4337 | 0.4025 | 0.4915 | 0.0890 | 0.0182 | 16.5778 |
| 98 | 0.4267 | 0.4296 | 0.4096 | 0.4394 | 0.0298 | 0.0088 | 6.8276 |
| 99 | 0.4306 | 0.4298 | 0.4116 | 0.4540 | 0.0425 | 0.0111 | 16.3632 |
| 100 | 0.4236 | 0.4249 | 0.4032 | 0.4321 | 0.0289 | 0.0084 | 3.8124 |
| 101 | 0.4333 | 0.4324 | 0.4084 | 0.5200 | 0.1116 | 0.0182 | 22.5331 |
| 102 | 0.4300 | 0.4280 | 0.4023 | 0.4763 | 0.0741 | 0.0146 | 34.8318 |
| 103 | 0.4303 | 0.4332 | 0.4142 | 0.4405 | 0.0263 | 0.0113 | 1.7211 |
| 104 | 0.4301 | 0.4310 | 0.4107 | 0.4499 | 0.0392 | 0.0095 | 7.7417 |
| 105 | 0.4337 | 0.4324 | 0.4222 | 0.4507 | 0.0285 | 0.0092 | 3.4700 |
| 106 | 0.4242 | 0.4212 | 0.4000 | 0.4982 | 0.0981 | 0.0193 | 278.6707 |
| 107 | 0.4301 | 0.4318 | 0.4000 | 0.4715 | 0.0714 | 0.0144 | 58.4904 |
| 108 | 0.4144 | 0.4115 | 0.4038 | 0.4245 | 0.0207 | 0.0072 | 4.5585 |
| 109 | 0.4101 | 0.4103 | 0.4043 | 0.4154 | 0.0111 | 0.0035 | 2.8708 |
| 110 | 0.4289 | 0.4204 | 0.4102 | 0.5679 | 0.1576 | 0.0335 | 8.5785 |
| 111 | 0.4250 | 0.4260 | 0.4058 | 0.4524 | 0.0465 | 0.0113 | 9.7749 |
| 112 | 0.4288 | 0.4329 | 0.4098 | 0.4427 | 0.0329 | 0.0130 | 3.0017 |
| 113 | 0.4669 | 0.4538 | 0.4011 | 0.6288 | 0.2277 | 0.0536 | 290.3989 |
| 114 | 0.4314 | 0.4323 | 0.4070 | 0.4553 | 0.0483 | 0.0127 | 15.0988 |
| 115 | 0.4235 | 0.4245 | 0.4035 | 0.4591 | 0.0556 | 0.0116 | 12.7062 |
| 116 | 0.4328 | 0.4296 | 0.4074 | 0.4718 | 0.0645 | 0.0134 | 41.9796 |
| 117 | 0.4295 | 0.4262 | 0.4081 | 0.4526 | 0.0446 | 0.0103 | 10.7376 |
| 118 | 0.4166 | 0.4163 | 0.4040 | 0.4317 | 0.0278 | 0.0080 | 7.4979 |
| 119 | 0.4287 | 0.4273 | 0.4036 | 0.4488 | 0.0452 | 0.0119 | 15.4344 |
| 120 | 0.4356 | 0.4322 | 0.4033 | 0.4973 | 0.0940 | 0.0222 | 35.7165 |
| 121 | 0.4316 | 0.4301 | 0.4088 | 0.4529 | 0.0441 | 0.0124 | 6.9062 |
| 122 | 0.4195 | 0.4182 | 0.4078 | 0.4368 | 0.0290 | 0.0083 | 9.6490 |
| 123 | 0.4146 | 0.4145 | 0.4063 | 0.4233 | 0.0170 | 0.0059 | 4.1463 |
| 124 | 0.4261 | 0.4239 | 0.4062 | 0.4568 | 0.0506 | 0.0118 | 14.4889 |
| 125 | 0.4413 | 0.4407 | 0.4001 | 0.4842 | 0.0841 | 0.0182 | 39.7135 |
| 126 | 0.4393 | 0.4414 | 0.4081 | 0.4731 | 0.0650 | 0.0187 | 7.9082 |
| 127 | 0.4343 | 0.4327 | 0.4071 | 0.4640 | 0.0570 | 0.0156 | 11.2913 |
| 128 | 0.4208 | 0.4207 | 0.4000 | 0.4399 | 0.0398 | 0.0086 | 14.7285 |
| 129 | 0.4301 | 0.4295 | 0.4019 | 0.4859 | 0.0840 | 0.0179 | 33.9777 |
| 130 | 0.4266 | 0.4243 | 0.4124 | 0.4442 | 0.0319 | 0.0088 | 11.5175 |
| 131 | 0.4414 | 0.4426 | 0.4052 | 0.4802 | 0.0750 | 0.0163 | 17.6556 |
| 132 | 0.4295 | 0.4318 | 0.4133 | 0.4396 | 0.0262 | 0.0093 | 3.8653 |
| 133 | 0.4250 | 0.4251 | 0.4041 | 0.4623 | 0.0582 | 0.0105 | 25.9242 |
| 134 | 0.4220 | 0.4220 | 0.4127 | 0.4418 | 0.0291 | 0.0090 | 3.7981 |
| 135 | 0.4252 | 0.4280 | 0.4024 | 0.4370 | 0.0345 | 0.0115 | 4.2518 |
| 136 | 0.4233 | 0.4211 | 0.4000 | 0.4680 | 0.0679 | 0.0149 | 75.3411 |
| 137 | 0.4137 | 0.4109 | 0.4077 | 0.4290 | 0.0213 | 0.0078 | 2.4820 |
| 138 | 0.4251 | 0.4261 | 0.4049 | 0.4466 | 0.0417 | 0.0087 | 7.2271 |
| 139 | 0.4242 | 0.4221 | 0.4098 | 0.4472 | 0.0374 | 0.0110 | 6.7866 |
| 140 | 0.4259 | 0.4236 | 0.4024 | 0.4558 | 0.0534 | 0.0116 | 39.6060 |
| 141 | 0.4303 | 0.4281 | 0.4047 | 0.4652 | 0.0604 | 0.0121 | 21.9465 |
| 142 | 0.4065 | 0.4065 | 0.4025 | 0.4105 | 0.0080 | 0.0056 | 0.8130 |
| 143 | 0.4323 | 0.4317 | 0.4108 | 0.4533 | 0.0426 | 0.0103 | 6.9161 |
| 144 | 0.4241 | 0.4208 | 0.4102 | 0.4478 | 0.0376 | 0.0103 | 6.3612 |
| 145 | 0.4095 | 0.4028 | 0.4000 | 0.4781 | 0.0781 | 0.0141 | 64.2908 |
| 146 | 0.4669 | 0.4331 | 0.4001 | 0.6467 | 0.2466 | 0.0713 | 25.6803 |
| 147 | 0.4286 | 0.4251 | 0.4131 | 0.4539 | 0.0408 | 0.0107 | 11.5718 |
| 148 | 0.4288 | 0.4275 | 0.4035 | 0.4594 | 0.0558 | 0.0122 | 39.8814 |
| 149 | 0.4331 | 0.4367 | 0.4000 | 0.4856 | 0.0855 | 0.0162 | 75.7859 |
| 150 | 0.4312 | 0.4312 | 0.4105 | 0.4541 | 0.0436 | 0.0101 | 15.0903 |
| 151 | 0.4205 | 0.4222 | 0.4040 | 0.4356 | 0.0317 | 0.0109 | 4.6256 |
| 152 | 0.4264 | 0.4238 | 0.4026 | 0.4544 | 0.0518 | 0.0128 | 11.5130 |
| 153 | 0.4463 | 0.4340 | 0.4006 | 0.6031 | 0.2024 | 0.0435 | 51.3228 |
| 154 | 0.4181 | 0.4144 | 0.4032 | 0.4618 | 0.0586 | 0.0143 | 5.8540 |
| 155 | 0.4196 | 0.4213 | 0.4009 | 0.4380 | 0.0372 | 0.0135 | 2.9371 |
| 156 | 0.4259 | 0.4256 | 0.4007 | 0.4529 | 0.0522 | 0.0125 | 35.3511 |
| 157 | 0.4838 | 0.4656 | 0.4060 | 0.6118 | 0.2058 | 0.0618 | 39.1873 |
| 158 | 0.4176 | 0.4173 | 0.4120 | 0.4236 | 0.0116 | 0.0043 | 2.0880 |
| 159 | 0.4191 | 0.4200 | 0.4001 | 0.4418 | 0.0418 | 0.0104 | 29.7570 |
| 160 | 0.4235 | 0.4179 | 0.4002 | 0.4651 | 0.0648 | 0.0197 | 13.9761 |
| 161 | 0.4551 | 0.4355 | 0.4077 | 0.5958 | 0.1881 | 0.0507 | 38.2250 |
| 162 | 0.4254 | 0.4227 | 0.4060 | 0.4601 | 0.0541 | 0.0125 | 8.9325 |
| 163 | 0.4130 | 0.4111 | 0.4040 | 0.4275 | 0.0235 | 0.0064 | 7.0210 |
| 164 | 0.4375 | 0.4355 | 0.4023 | 0.4936 | 0.0914 | 0.0211 | 16.6236 |
| 165 | 0.4070 | 0.4075 | 0.4022 | 0.4114 | 0.0091 | 0.0027 | 4.4769 |
| 166 | 0.4218 | 0.4204 | 0.4036 | 0.4442 | 0.0406 | 0.0132 | 16.0271 |
| 167 | 0.4222 | 0.4230 | 0.4081 | 0.4439 | 0.0358 | 0.0078 | 23.2200 |
| 168 | 0.4344 | 0.4272 | 0.4000 | 0.5961 | 0.1960 | 0.0272 | 134.6792 |
| 169 | 0.4198 | 0.4214 | 0.4002 | 0.4369 | 0.0367 | 0.0096 | 10.9157 |
| 170 | 0.4207 | 0.4191 | 0.4128 | 0.4344 | 0.0216 | 0.0076 | 2.9450 |
| 171 | 0.4233 | 0.4215 | 0.4021 | 0.4498 | 0.0477 | 0.0151 | 3.3861 |
| 172 | 0.4312 | 0.4312 | 0.4013 | 0.4683 | 0.0671 | 0.0136 | 79.3355 |
| 173 | 0.4894 | 0.4471 | 0.4146 | 0.6039 | 0.1893 | 0.0637 | 15.6610 |
| 174 | 0.4307 | 0.4291 | 0.4054 | 0.4538 | 0.0484 | 0.0102 | 12.4903 |
| 175 | 0.4203 | 0.4199 | 0.4021 | 0.4577 | 0.0556 | 0.0098 | 36.1455 |
| 176 | 0.4418 | 0.4432 | 0.4185 | 0.4582 | 0.0398 | 0.0151 | 3.9761 |
| 177 | 0.4323 | 0.4313 | 0.4120 | 0.4709 | 0.0589 | 0.0157 | 7.3493 |
| 178 | 0.4237 | 0.4227 | 0.4039 | 0.4438 | 0.0399 | 0.0143 | 2.9661 |
| 179 | 0.5568 | 0.5644 | 0.5164 | 0.5819 | 0.0655 | 0.0307 | 2.2271 |
| 180 | 0.4396 | 0.4301 | 0.4038 | 0.6308 | 0.2270 | 0.0382 | 101.1035 |
| 181 | 0.4137 | 0.4138 | 0.4000 | 0.4430 | 0.0429 | 0.0086 | 43.0268 |
| 182 | 0.4296 | 0.4299 | 0.4006 | 0.4823 | 0.0817 | 0.0179 | 73.0325 |
| 183 | 0.4550 | 0.0000 | 0.4550 | 0.4550 | 0.0000 | 0.0000 | 0.4550 |
| 184 | 0.4346 | 0.4297 | 0.4200 | 0.4569 | 0.0369 | 0.0102 | 6.5195 |
| 185 | 0.4278 | 0.4268 | 0.4020 | 0.4572 | 0.0552 | 0.0141 | 11.9787 |
| 186 | 0.4341 | 0.4357 | 0.4174 | 0.4489 | 0.0315 | 0.0115 | 3.9073 |
| 187 | 0.4283 | 0.4194 | 0.4040 | 0.4969 | 0.0929 | 0.0252 | 5.5684 |
| 188 | 0.4155 | 0.4149 | 0.4042 | 0.4304 | 0.0261 | 0.0088 | 2.4933 |
| 189 | 0.4538 | 0.4359 | 0.4114 | 0.6137 | 0.2023 | 0.0515 | 12.2525 |
| 190 | 0.4176 | 0.4169 | 0.4013 | 0.4433 | 0.0419 | 0.0100 | 10.8582 |
| 191 | 0.4372 | 0.4402 | 0.4008 | 0.4589 | 0.0581 | 0.0170 | 18.7990 |
| 192 | 0.4181 | 0.4185 | 0.4025 | 0.4278 | 0.0252 | 0.0065 | 8.3617 |
| 193 | 0.4165 | 0.4164 | 0.4102 | 0.4229 | 0.0127 | 0.0064 | 1.2495 |
| 194 | 0.4204 | 0.4194 | 0.4007 | 0.4622 | 0.0615 | 0.0128 | 30.6857 |
| 195 | 0.4103 | 0.4110 | 0.4036 | 0.4153 | 0.0117 | 0.0048 | 2.4619 |
| 196 | 0.4088 | 0.4092 | 0.4042 | 0.4152 | 0.0110 | 0.0039 | 4.4965 |
| 197 | 0.4311 | 0.4319 | 0.4130 | 0.4557 | 0.0428 | 0.0115 | 6.0359 |
| 198 | 0.4196 | 0.4220 | 0.4021 | 0.4368 | 0.0347 | 0.0077 | 33.1482 |
| 199 | 0.4302 | 0.4195 | 0.4054 | 0.5396 | 0.1342 | 0.0284 | 10.7554 |
| 200 | 0.4161 | 0.4162 | 0.4013 | 0.4277 | 0.0264 | 0.0055 | 27.0456 |
| 201 | 0.4232 | 0.4225 | 0.4035 | 0.4465 | 0.0430 | 0.0105 | 8.4646 |
| 202 | 0.4216 | 0.4197 | 0.4119 | 0.4315 | 0.0195 | 0.0078 | 2.5297 |
| 203 | 0.4307 | 0.4269 | 0.4001 | 0.6162 | 0.2162 | 0.0314 | 57.7204 |
| 204 | 0.4176 | 0.4189 | 0.4065 | 0.4234 | 0.0169 | 0.0067 | 2.0881 |
| 205 | 0.4288 | 0.4282 | 0.4038 | 0.4546 | 0.0508 | 0.0112 | 23.5858 |
| 206 | 0.4196 | 0.4164 | 0.4067 | 0.4427 | 0.0361 | 0.0127 | 4.6160 |
| 207 | 0.4200 | 0.4180 | 0.4025 | 0.4421 | 0.0396 | 0.0089 | 16.3808 |
| 208 | 0.4247 | 0.4243 | 0.4042 | 0.4515 | 0.0473 | 0.0103 | 22.5070 |
| 209 | 0.4377 | 0.4260 | 0.4001 | 0.6143 | 0.2142 | 0.0369 | 160.1841 |
| 210 | 0.4319 | 0.4291 | 0.4001 | 0.5007 | 0.1006 | 0.0181 | 45.3450 |
| 211 | 0.4098 | 0.4094 | 0.4000 | 0.4299 | 0.0299 | 0.0069 | 10.6540 |
| 212 | 0.4265 | 0.4277 | 0.4158 | 0.4330 | 0.0172 | 0.0059 | 2.9853 |
| 213 | 0.4194 | 0.4215 | 0.4015 | 0.4295 | 0.0279 | 0.0071 | 7.1291 |
| 214 | 0.4304 | 0.4304 | 0.4083 | 0.4480 | 0.0397 | 0.0113 | 6.4560 |
| 215 | 0.4475 | 0.4292 | 0.4037 | 0.6393 | 0.2356 | 0.0541 | 82.7868 |
| 216 | 0.4141 | 0.4158 | 0.4005 | 0.4250 | 0.0245 | 0.0063 | 4.1410 |
| 217 | 0.4557 | 0.4291 | 0.4095 | 0.5963 | 0.1868 | 0.0600 | 11.8484 |
| 218 | 0.4401 | 0.4411 | 0.4071 | 0.4688 | 0.0617 | 0.0162 | 3.9608 |
| 219 | 0.5017 | 0.4916 | 0.4094 | 0.6524 | 0.2431 | 0.0674 | 25.5850 |
| 220 | 0.4224 | 0.4221 | 0.4087 | 0.4383 | 0.0297 | 0.0094 | 6.3366 |
| 221 | 0.4272 | 0.4228 | 0.4081 | 0.4546 | 0.0466 | 0.0135 | 4.6995 |
| 222 | 0.4209 | 0.4207 | 0.4056 | 0.4451 | 0.0396 | 0.0112 | 7.9977 |
| 223 | 0.4349 | 0.4326 | 0.4000 | 0.5004 | 0.1004 | 0.0220 | 54.3585 |
| 224 | 0.4181 | 0.4169 | 0.4144 | 0.4278 | 0.0133 | 0.0055 | 2.0907 |
| 225 | 0.4254 | 0.4247 | 0.4058 | 0.4630 | 0.0572 | 0.0106 | 28.0754 |
| 226 | 0.4696 | 0.4342 | 0.4067 | 0.6333 | 0.2266 | 0.0692 | 22.0729 |
| 227 | 0.4137 | 0.4115 | 0.4054 | 0.4309 | 0.0255 | 0.0066 | 6.6191 |
| 228 | 0.4180 | 0.4171 | 0.4028 | 0.4561 | 0.0533 | 0.0091 | 26.3332 |
| 229 | 0.4153 | 0.4151 | 0.4009 | 0.4548 | 0.0539 | 0.0078 | 36.5476 |
| 230 | 0.4161 | 0.4161 | 0.4025 | 0.4301 | 0.0276 | 0.0060 | 12.0676 |
| 231 | 0.4430 | 0.4379 | 0.4037 | 0.4956 | 0.0919 | 0.0298 | 7.0878 |
| 232 | 0.4179 | 0.4158 | 0.4018 | 0.4335 | 0.0317 | 0.0083 | 9.1943 |
| 233 | 0.4344 | 0.4330 | 0.4034 | 0.4737 | 0.0703 | 0.0157 | 12.5989 |
| 234 | 0.4680 | 0.4503 | 0.4048 | 0.6405 | 0.2357 | 0.0511 | 77.6875 |
| 235 | 0.4187 | 0.4188 | 0.4029 | 0.4400 | 0.0371 | 0.0060 | 31.8224 |
| 236 | 0.4221 | 0.4220 | 0.4119 | 0.4314 | 0.0195 | 0.0055 | 6.3320 |
| 237 | 0.4723 | 0.4544 | 0.4120 | 0.6323 | 0.2203 | 0.0536 | 24.0881 |
| 238 | 0.4252 | 0.4225 | 0.4021 | 0.4589 | 0.0568 | 0.0132 | 38.6947 |
| 239 | 0.4465 | 0.4429 | 0.4278 | 0.4659 | 0.0381 | 0.0126 | 4.9115 |
| 240 | 0.4261 | 0.4318 | 0.4001 | 0.4699 | 0.0699 | 0.0232 | 16.1937 |
| 241 | 0.4198 | 0.4206 | 0.4024 | 0.4335 | 0.0311 | 0.0086 | 14.6928 |
| 242 | 0.4180 | 0.4176 | 0.4130 | 0.4237 | 0.0107 | 0.0036 | 2.9261 |
| 243 | 0.4093 | 0.4045 | 0.4001 | 0.4738 | 0.0737 | 0.0129 | 67.5326 |
| 244 | 0.4189 | 0.4198 | 0.4069 | 0.4314 | 0.0245 | 0.0092 | 2.9322 |
| 245 | 0.4224 | 0.4220 | 0.4027 | 0.4509 | 0.0482 | 0.0083 | 29.5651 |
| 246 | 0.4258 | 0.4245 | 0.4046 | 0.4543 | 0.0496 | 0.0108 | 33.6349 |
| 247 | 0.4669 | 0.4421 | 0.4070 | 0.6480 | 0.2410 | 0.0609 | 179.2852 |
| 248 | 0.4945 | 0.4857 | 0.4194 | 0.6004 | 0.1810 | 0.0560 | 12.8571 |
| 249 | 0.4247 | 0.4242 | 0.4048 | 0.4402 | 0.0354 | 0.0124 | 23.7825 |
| 250 | 0.4424 | 0.4388 | 0.4070 | 0.4910 | 0.0840 | 0.0213 | 13.2732 |
| 251 | 0.4745 | 0.4554 | 0.4108 | 0.6210 | 0.2102 | 0.0555 | 60.2670 |
| 252 | 0.4247 | 0.4247 | 0.4100 | 0.4386 | 0.0286 | 0.0068 | 5.0960 |
| 253 | 0.4200 | 0.4196 | 0.4000 | 0.4411 | 0.0411 | 0.0105 | 23.0979 |
| 254 | 0.4181 | 0.4183 | 0.4011 | 0.4454 | 0.0443 | 0.0122 | 8.3626 |
| 255 | 0.4222 | 0.4225 | 0.4171 | 0.4266 | 0.0096 | 0.0043 | 1.6887 |
| 256 | 0.4175 | 0.4167 | 0.4010 | 0.4424 | 0.0414 | 0.0088 | 21.2906 |
| 257 | 0.4208 | 0.4218 | 0.4066 | 0.4313 | 0.0247 | 0.0078 | 3.3664 |
| 258 | 0.4386 | 0.4368 | 0.4046 | 0.5070 | 0.1024 | 0.0197 | 32.4580 |
| 259 | 0.4355 | 0.4320 | 0.4086 | 0.4773 | 0.0687 | 0.0181 | 10.8870 |
| 260 | 0.5198 | 0.5120 | 0.4378 | 0.5860 | 0.1482 | 0.0527 | 3.6389 |
| 261 | 0.4310 | 0.4296 | 0.4001 | 0.4803 | 0.0802 | 0.0194 | 26.7211 |
| 262 | 0.4113 | 0.4105 | 0.4007 | 0.4225 | 0.0218 | 0.0059 | 27.5545 |
| 263 | 0.4535 | 0.4527 | 0.4382 | 0.4713 | 0.0331 | 0.0106 | 3.6283 |
| 264 | 0.4423 | 0.4285 | 0.4027 | 0.6351 | 0.2324 | 0.0519 | 14.5949 |
| 265 | 0.4350 | 0.4361 | 0.4086 | 0.4460 | 0.0374 | 0.0087 | 6.5243 |
| 266 | 0.4354 | 0.4333 | 0.4125 | 0.4659 | 0.0535 | 0.0139 | 6.0951 |
| 267 | 0.4284 | 0.4291 | 0.4023 | 0.4586 | 0.0563 | 0.0150 | 8.9964 |
| 268 | 0.4374 | 0.4379 | 0.4057 | 0.4761 | 0.0704 | 0.0156 | 24.4916 |
| 269 | 0.4282 | 0.4279 | 0.4051 | 0.4550 | 0.0500 | 0.0202 | 2.9977 |
| 270 | 0.4168 | 0.4127 | 0.4001 | 0.4542 | 0.0541 | 0.0131 | 20.0043 |
| 271 | 0.4412 | 0.4270 | 0.4087 | 0.5299 | 0.1212 | 0.0371 | 6.1769 |
| 272 | 0.4140 | 0.4140 | 0.4014 | 0.4266 | 0.0252 | 0.0178 | 0.8280 |
| 273 | 0.4287 | 0.4259 | 0.4095 | 0.4629 | 0.0533 | 0.0120 | 20.5798 |
| 274 | 0.4294 | 0.4271 | 0.4036 | 0.4557 | 0.0521 | 0.0119 | 18.0346 |
| 275 | 0.4131 | 0.4157 | 0.4001 | 0.4385 | 0.0385 | 0.0115 | 26.4395 |
| 276 | 0.4103 | 0.4072 | 0.4034 | 0.4223 | 0.0189 | 0.0072 | 4.1026 |

In [39]:

df = pd.read_csv(StringIO(stats[1]), sep ="|",  skiprows=5, index_col=1, names=["first","id","mean","median","min","max","range","stddve","total","last"])
df.index = df.index + 1
df

      first    mean  median     min     max   range  stddve     total  last
id
1       NaN  0.4500  0.4347  0.4005  0.6493  0.2488  0.0462  395.5851   NaN
2       NaN  0.4367  0.4289  0.4000  0.6229  0.2228  0.0378  590.8673   NaN
3       NaN  0.4472  0.4372  0.4002  0.6281  0.2279  0.0386  274.1367   NaN
4       NaN  0.4204  0.4208  0.4006  0.4499  0.0493  0.0096   51.7076   NaN
5       NaN  0.4283  0.4257  0.4000  0.4958  0.0957  0.0172  100.2331   NaN
...     ...     ...     ...     ...     ...     ...     ...       ...   ...
4386    NaN  0.4340  0.4264  0.4033  0.4762  0.0729  0.0231   15.1891   NaN
4387    NaN  0.4487  0.4499  0.4105  0.4715  0.0610  0.0122   15.7029   NaN
4388    NaN  0.4192  0.4194  0.4037  0.4329  0.0292  0.0082    3.7731   NaN
4389    NaN  0.4448  0.4441  0.4246  0.4628  0.0382  0.0103    6.2278   NaN
4390    NaN  0.4271  0.4272  0.4207  0.4357  0.0150  0.0051    3.4168   NaN

[4390 rows x 9 columns]

In [37]:
df["mean"].to_dict()

{0: 0.45,
 1: 0.4367,
 2: 0.4472,
 3: 0.4204,
 4: 0.4283,
 5: 0.4302,
 6: 0.4903,
 7: 0.4288,
 8: 0.4179,
 9: 0.4532,
 10: 0.4553,
 11: 0.4362,
 12: 0.4292,
 13: 0.434,
 14: 0.4203,
 15: 0.4343,
 16: 0.4356,
 17: 0.4572,
 18: 0.4293,
 19: 0.4298,
 20: 0.4625,
 21: 0.4286,
 22: 0.433,
 23: 0.4277,
 24: 0.4326,
 25: 0.4261,
 26: 0.4873,
 27: 0.4242,
 28: 0.4271,
 29: 0.4208,
 30: 0.4362,
 31: 0.4312,
 32: 0.4314,
 33: 0.4283,
 34: 0.4234,
 35: 0.4829,
 36: 0.4158,
 37: 0.4487,
 38: 0.425,
 39: 0.4549,
 40: 0.4111,
 41: 0.4283,
 42: 0.4219,
 43: 0.4339,
 44: 0.4409,
 45: 0.4225,
 46: 0.4452,
 47: 0.4371,
 48: 0.4348,
 49: 0.4589,
 50: 0.4437,
 51: 0.4197,
 52: 0.4227,
 53: 0.4377,
 54: 0.4317,
 55: 0.5255,
 56: 0.4418,
 57: 0.4238,
 58: 0.4948,
 59: 0.4189,
 60: 0.4692,
 61: 0.4262,
 62: 0.4204,
 63: 0.4625,
 64: 0.4231,
 65: 0.4254,
 66: 0.4275,
 67: 0.4302,
 68: 0.4236,
 69: 0.4137,
 70: 0.4336,
 71: 0.44,
 72: 0.4291,
 73: 0.4264,
 74: 0.502,
 75: 0.4255,
 76: 0.4269,
 77: 0.4248,
 78: 0.4567,
 79: 0.4421,
 80: 0.4314,
 81: 0.4317,
 82: 0.4161,
 83: 0.4235,
 84: 0.4189,
 85: 0.4262,
 86: 0.5075,
 87: 0.4303,
 88: 0.4344,
 89: 0.4734,
 90: 0.4712,
 91: 0.4183,
 92: 0.4207,
 93: 0.4208,
 94: 0.4227,
 95: 0.4306,
 96: 0.429,
 97: 0.4363,
 98: 0.4267,
 99: 0.4306,
 100: 0.4236,
 101: 0.4333,
 102: 0.43,
 103: 0.4303,
 104: 0.4301,
 105: 0.4337,
 106: 0.4242,
 107: 0.4301,
 108: 0.4144,
 109: 0.4101,
 110: 0.4289,
 111: 0.425,
 112: 0.4288,
 113: 0.4669,
 114: 0.4314,
 115: 0.4235,
 116: 0.4328,
 117: 0.4295,
 118: 0.4166,
 119: 0.4287,
 120: 0.4356,
 121: 0.4316,
 122: 0.4195,
 123: 0.4146,
 124: 0.4261,
 125: 0.4413,
 126: 0.4393,
 127: 0.4343,
 128: 0.4208,
 129: 0.4301,
 130: 0.4266,
 131: 0.4414,
 132: 0.4295,
 133: 0.425,
 134: 0.422,
 135: 0.4252,
 136: 0.4233,
 137: 0.4137,
 138: 0.4251,
 139: 0.4242,
 140: 0.4259,
 141: 0.4303,
 142: 0.4065,
 143: 0.4323,
 144: 0.4241,
 145: 0.4095,
 146: 0.4669,
 147: 0.4286,
 148: 0.4288,
 149: 0.4331,
 150: 0.4312,
 151: 0.4205,
 152: 0.4264,
 153: 0.4463,
 154: 0.4181,
 155: 0.4196,
 156: 0.4259,
 157: 0.4838,
 158: 0.4176,
 159: 0.4191,
 160: 0.4235,
 161: 0.4551,
 162: 0.4254,
 163: 0.413,
 164: 0.4375,
 165: 0.407,
 166: 0.4218,
 167: 0.4222,
 168: 0.4344,
 169: 0.4198,
 170: 0.4207,
 171: 0.4233,
 172: 0.4312,
 173: 0.4894,
 174: 0.4307,
 175: 0.4203,
 176: 0.4418,
 177: 0.4323,
 178: 0.4237,
 179: 0.5568,
 180: 0.4396,
 181: 0.4137,
 182: 0.4296,
 183: 0.455,
 184: 0.4346,
 185: 0.4278,
 186: 0.4341,
 187: 0.4283,
 188: 0.4155,
 189: 0.4538,
 190: 0.4176,
 191: 0.4372,
 192: 0.4181,
 193: 0.4165,
 194: 0.4204,
 195: 0.4103,
 196: 0.4088,
 197: 0.4311,
 198: 0.4196,
 199: 0.4302,
 200: 0.4161,
 201: 0.4232,
 202: 0.4216,
 203: 0.4307,
 204: 0.4176,
 205: 0.4288,
 206: 0.4196,
 207: 0.42,
 208: 0.4247,
 209: 0.4377,
 210: 0.4319,
 211: 0.4098,
 212: 0.4265,
 213: 0.4194,
 214: 0.4304,
 215: 0.4475,
 216: 0.4141,
 217: 0.4557,
 218: 0.4401,
 219: 0.5017,
 220: 0.4224,
 221: 0.4272,
 222: 0.4209,
 223: 0.4349,
 224: 0.4181,
 225: 0.4254,
 226: 0.4696,
 227: 0.4137,
 228: 0.418,
 229: 0.4153,
 230: 0.4161,
 231: 0.443,
 232: 0.4179,
 233: 0.4344,
 234: 0.468,
 235: 0.4187,
 236: 0.4221,
 237: 0.4723,
 238: 0.4252,
 239: 0.4465,
 240: 0.4261,
 241: 0.4198,
 242: 0.418,
 243: 0.4093,
 244: 0.4189,
 245: 0.4224,
 246: 0.4258,
 247: 0.4669,
 248: 0.4945,
 249: 0.4247,
 250: 0.4424,
 251: 0.4745,
 252: 0.4247,
 253: 0.42,
 254: 0.4181,
 255: 0.4222,
 256: 0.4175,
 257: 0.4208,
 258: 0.4386,
 259: 0.4355,
 260: 0.5198,
 261: 0.431,
 262: 0.4113,
 263: 0.4535,
 264: 0.4423,
 265: 0.435,
 266: 0.4354,
 267: 0.4284,
 268: 0.4374,
 269: 0.4282,
 270: 0.4168,
 271: 0.4412,
 272: 0.414,
 273: 0.4287,
 274: 0.4294,
 275: 0.4131,
 276: 0.4103,
 277: 0.4332,
 278: 0.4635,
 279: 0.4372,
 280: 0.4442,
 281: 0.4349,
 282: 0.423,
 283: 0.4289,
 284: 0.4248,
 285: 0.4255,
 286: 0.435,
 287: 0.4327,
 288: 0.4277,
 289: 0.4279,
 290: 0.4223,
 291: 0.407,
 292: 0.4202,
 293: 0.4174,
 294: 0.4309,
 295: 0.4459,
 296: 0.419,
 297: 0.4251,
 298: 0.4236,
 299: 0.421,
 300: 0.4184,
 301: 0.4164,
 302: 0.4419,
 303: 0.4238,
 304: 0.4275,
 305: 0.4329,
 306: 0.4466,
 307: 0.4185,
 308: 0.4136,
 309: 0.4404,
 310: 0.5037,
 311: 0.4435,
 312: 0.4345,
 313: 0.4209,
 314: 0.4298,
 315: 0.4451,
 316: 0.4197,
 317: 0.4253,
 318: 0.4625,
 319: 0.4362,
 320: 0.4243,
 321: 0.4183,
 322: 0.4381,
 323: 0.4337,
 324: 0.4321,
 325: 0.4109,
 326: 0.4247,
 327: 0.4298,
 328: 0.4306,
 329: 0.4143,
 330: 0.427,
 331: 0.4308,
 332: 0.4571,
 333: 0.4376,
 334: 0.4553,
 335: 0.4376,
 336: 0.429,
 337: 0.4457,
 338: 0.4334,
 339: 0.4252,
 340: 0.4169,
 341: 0.4358,
 342: 0.4328,
 343: 0.4542,
 344: 0.4142,
 345: 0.4315,
 346: 0.4278,
 347: 0.4253,
 348: 0.4462,
 349: 0.4301,
 350: 0.4887,
 351: 0.4784,
 352: 0.4258,
 353: 0.4268,
 354: 0.4337,
 355: 0.4308,
 356: 0.4326,
 357: 0.4222,
 358: 0.4289,
 359: 0.428,
 360: 0.4214,
 361: 0.4213,
 362: 0.4176,
 363: 0.44,
 364: 0.4268,
 365: 0.4317,
 366: 0.4412,
 367: 0.4404,
 368: 0.4205,
 369: 0.4179,
 370: 0.4261,
 371: 0.4416,
 372: 0.43,
 373: 0.4291,
 374: 0.4116,
 375: 0.4191,
 376: 0.4427,
 377: 0.4387,
 378: 0.4558,
 379: 0.4889,
 380: 0.4276,
 381: 0.4294,
 382: 0.4513,
 383: 0.4171,
 384: 0.4315,
 385: 0.4326,
 386: 0.4254,
 387: 0.432,
 388: 0.453,
 389: 0.4317,
 390: 0.4293,
 391: 0.4224,
 392: 0.4152,
 393: 0.4266,
 394: 0.4427,
 395: 0.4293,
 396: 0.4181,
 397: 0.4258,
 398: 0.42,
 399: 0.4411,
 400: 0.4181,
 401: 0.4196,
 402: 0.4305,
 403: 0.4373,
 404: 0.4409,
 405: 0.4258,
 406: 0.4366,
 407: 0.4093,
 408: 0.4239,
 409: 0.431,
 410: 0.417,
 411: 0.4373,
 412: 0.4441,
 413: 0.4443,
 414: 0.4405,
 415: 0.4156,
 416: 0.4407,
 417: 0.4214,
 418: 0.4323,
 419: 0.4312,
 420: 0.4204,
 421: 0.4359,
 422: 0.4537,
 423: 0.4335,
 424: 0.4265,
 425: 0.4177,
 426: 0.4285,
 427: 0.4399,
 428: 0.4189,
 429: 0.4319,
 430: 0.44,
 431: 0.45,
 432: 0.4168,
 433: 0.4288,
 434: 0.4287,
 435: 0.4187,
 436: 0.4151,
 437: 0.4299,
 438: 0.4242,
 439: 0.4305,
 440: 0.4314,
 441: 0.4293,
 442: 0.4244,
 443: 0.4672,
 444: 0.4278,
 445: 0.4262,
 446: 0.4329,
 447: 0.4412,
 448: 0.439,
 449: 0.4812,
 450: 0.4236,
 451: 0.4163,
 452: 0.4403,
 453: 0.4311,
 454: 0.4192,
 455: 0.4148,
 456: 0.4228,
 457: 0.4278,
 458: 0.4281,
 459: 0.4446,
 460: 0.4185,
 461: 0.4171,
 462: 0.4321,
 463: 0.4351,
 464: 0.4254,
 465: 0.412,
 466: 0.429,
 467: 0.4621,
 468: 0.4204,
 469: 0.4267,
 470: 0.4219,
 471: 0.4173,
 472: 0.4342,
 473: 0.426,
 474: 0.432,
 475: 0.4208,
 476: 0.4312,
 477: 0.4406,
 478: 0.4872,
 479: 0.4426,
 480: 0.4303,
 481: 0.4281,
 482: 0.4337,
 483: 0.4282,
 484: 0.4085,
 485: 0.4468,
 486: 0.4376,
 487: 0.4357,
 488: 0.4238,
 489: 0.4119,
 490: 0.4256,
 491: 0.4312,
 492: 0.4256,
 493: 0.4307,
 494: 0.4317,
 495: 0.4162,
 496: 0.4341,
 497: 0.4538,
 498: 0.4391,
 499: 0.4357,
 500: 0.4309,
 501: 0.4319,
 502: 0.4202,
 503: 0.4362,
 504: 0.4208,
 505: 0.4364,
 506: 0.4436,
 507: 0.4242,
 508: 0.4258,
 509: 0.4212,
 510: 0.4378,
 511: 0.4254,
 512: 0.4321,
 513: 0.4269,
 514: 0.4311,
 515: 0.4256,
 516: 0.4525,
 517: 0.4565,
 518: 0.4359,
 519: 0.4264,
 520: 0.4257,
 521: 0.4612,
 522: 0.4294,
 523: 0.4211,
 524: 0.4364,
 525: 0.4321,
 526: 0.4187,
 527: 0.4435,
 528: 0.4351,
 529: 0.4309,
 530: 0.4315,
 531: 0.4282,
 532: 0.4258,
 533: 0.4167,
 534: 0.4349,
 535: 0.4314,
 536: 0.4287,
 537: 0.4338,
 538: 0.4387,
 539: 0.4437,
 540: 0.4218,
 541: 0.4317,
 542: 0.4266,
 543: 0.427,
 544: 0.4667,
 545: 0.4383,
 546: 0.4589,
 547: 0.4427,
 548: 0.4366,
 549: 0.4305,
 550: 0.4303,
 551: 0.433,
 552: 0.4353,
 553: 0.4209,
 554: 0.4852,
 555: 0.4351,
 556: 0.4247,
 557: 0.4097,
 558: 0.4488,
 559: 0.4262,
 560: 0.4303,
 561: 0.4623,
 562: 0.4239,
 563: 0.4286,
 564: 0.4444,
 565: 0.4281,
 566: 0.4355,
 567: 0.4323,
 568: 0.4275,
 569: 0.4357,
 570: 0.4287,
 571: 0.4186,
 572: 0.4263,
 573: 0.4251,
 574: 0.4325,
 575: 0.4248,
 576: 0.4278,
 577: 0.442,
 578: 0.4652,
 579: 0.4211,
 580: 0.4637,
 581: 0.4247,
 582: 0.4223,
 583: 0.4328,
 584: 0.455,
 585: 0.4129,
 586: 0.4326,
 587: 0.429,
 588: 0.4354,
 589: 0.4369,
 590: 0.4459,
 591: 0.4399,
 592: 0.4043,
 593: 0.4201,
 594: 0.4342,
 595: 0.4246,
 596: 0.4465,
 597: 0.4578,
 598: 0.4329,
 599: 0.4155,
 600: 0.4199,
 601: 0.4346,
 602: 0.422,
 603: 0.4337,
 604: 0.4607,
 605: 0.4349,
 606: 0.4274,
 607: 0.4148,
 608: 0.4335,
 609: 0.423,
 610: 0.4281,
 611: 0.4285,
 612: 0.4889,
 613: 0.4154,
 614: 0.446,
 615: 0.4516,
 616: 0.4315,
 617: 0.4232,
 618: 0.4269,
 619: 0.4645,
 620: 0.4334,
 621: 0.4318,
 622: 0.4148,
 623: 0.461,
 624: 0.4246,
 625: 0.4195,
 626: 0.4226,
 627: 0.4398,
 628: 0.4234,
 629: 0.4189,
 630: 0.429,
 631: 0.4249,
 632: 0.4095,
 633: 0.423,
 634: 0.446,
 635: 0.4471,
 636: 0.4553,
 637: 0.4172,
 638: 0.4266,
 639: 0.4202,
 640: 0.4265,
 641: 0.4321,
 642: 0.421,
 643: 0.4259,
 644: 0.4333,
 645: 0.4266,
 646: 0.4184,
 647: 0.4104,
 648: 0.429,
 649: 0.436,
 650: 0.4435,
 651: 0.4351,
 652: 0.4259,
 653: 0.4259,
 654: 0.4163,
 655: 0.4157,
 656: 0.4306,
 657: 0.4268,
 658: 0.4296,
 659: 0.4389,
 660: 0.4326,
 661: 0.4215,
 662: 0.446,
 663: 0.4432,
 664: 0.4319,
 665: 0.4315,
 666: 0.4332,
 667: 0.4271,
 668: 0.428,
 669: 0.4295,
 670: 0.4255,
 671: 0.4426,
 672: 0.4263,
 673: 0.4467,
 674: 0.4354,
 675: 0.4398,
 676: 0.4363,
 677: 0.4394,
 678: 0.4735,
 679: 0.4359,
 680: 0.4173,
 681: 0.4364,
 682: 0.4686,
 683: 0.4576,
 684: 0.4434,
 685: 0.4409,
 686: 0.4238,
 687: 0.4141,
 688: 0.4236,
 689: 0.4566,
 690: 0.4284,
 691: 0.4264,
 692: 0.4187,
 693: 0.4222,
 694: 0.4366,
 695: 0.439,
 696: 0.4277,
 697: 0.4095,
 698: 0.4374,
 699: 0.4552,
 700: 0.4719,
 701: 0.427,
 702: 0.4342,
 703: 0.4764,
 704: 0.4435,
 705: 0.4228,
 706: 0.4144,
 707: 0.4196,
 708: 0.4392,
 709: 0.458,
 710: 0.4407,
 711: 0.4373,
 712: 0.4473,
 713: 0.4253,
 714: 0.4794,
 715: 0.446,
 716: 0.4473,
 717: 0.4186,
 718: 0.4283,
 719: 0.457,
 720: 0.4275,
 721: 0.4393,
 722: 0.4267,
 723: 0.4341,
 724: 0.4373,
 725: 0.4144,
 726: 0.429,
 727: 0.4383,
 728: 0.434,
 729: 0.4371,
 730: 0.4413,
 731: 0.4385,
 732: 0.454,
 733: 0.4313,
 734: 0.4413,
 735: 0.4328,
 736: 0.4538,
 737: 0.4395,
 738: 0.429,
 739: 0.4248,
 740: 0.4179,
 741: 0.4331,
 742: 0.4314,
 743: 0.431,
 744: 0.4386,
 745: 0.4301,
 746: 0.4324,
 747: 0.4235,
 748: 0.4278,
 749: 0.4184,
 750: 0.4413,
 751: 0.4242,
 752: 0.4144,
 753: 0.4194,
 754: 0.4244,
 755: 0.4338,
 756: 0.4259,
 757: 0.4683,
 758: 0.4248,
 759: 0.4034,
 760: 0.438,
 761: 0.4449,
 762: 0.431,
 763: 0.4246,
 764: 0.4525,
 765: 0.4405,
 766: 0.4255,
 767: 0.4218,
 768: 0.4304,
 769: 0.4203,
 770: 0.4325,
 771: 0.4284,
 772: 0.4283,
 773: 0.4286,
 774: 0.4259,
 775: 0.4243,
 776: 0.4265,
 777: 0.4284,
 778: 0.4282,
 779: 0.4509,
 780: 0.417,
 781: 0.4404,
 782: 0.4509,
 783: 0.4318,
 784: 0.4318,
 785: 0.4299,
 786: 0.4129,
 787: 0.4378,
 788: 0.4226,
 789: 0.4268,
 790: 0.4304,
 791: 0.4596,
 792: 0.4392,
 793: 0.4295,
 794: 0.4231,
 795: 0.416,
 796: 0.4364,
 797: 0.4435,
 798: 0.4741,
 799: 0.4395,
 800: 0.4202,
 801: 0.4478,
 802: 0.4356,
 803: 0.4262,
 804: 0.4184,
 805: 0.4258,
 806: 0.427,
 807: 0.4232,
 808: 0.426,
 809: 0.4167,
 810: 0.4366,
 811: 0.4299,
 812: 0.4375,
 813: 0.4329,
 814: 0.4282,
 815: 0.4175,
 816: 0.4518,
 817: 0.4455,
 818: 0.424,
 819: 0.4418,
 820: 0.4243,
 821: 0.4787,
 822: 0.4333,
 823: 0.4851,
 824: 0.4743,
 825: 0.4269,
 826: 0.4527,
 827: 0.4214,
 828: 0.4325,
 829: 0.4398,
 830: 0.4612,
 831: 0.4237,
 832: 0.4265,
 833: 0.4194,
 834: 0.4314,
 835: 0.4467,
 836: 0.445,
 837: 0.4225,
 838: 0.4276,
 839: 0.4346,
 840: 0.4399,
 841: 0.4292,
 842: 0.4213,
 843: 0.4259,
 844: 0.4288,
 845: 0.4429,
 846: 0.4333,
 847: 0.4575,
 848: 0.4207,
 849: 0.4282,
 850: 0.4471,
 851: 0.4404,
 852: 0.4355,
 853: 0.4302,
 854: 0.4217,
 855: 0.422,
 856: 0.4288,
 857: 0.4413,
 858: 0.4367,
 859: 0.4286,
 860: 0.4259,
 861: 0.4317,
 862: 0.4329,
 863: 0.4276,
 864: 0.4351,
 865: 0.4265,
 866: 0.4345,
 867: 0.4333,
 868: 0.4207,
 869: 0.4502,
 870: 0.4347,
 871: 0.4246,
 872: 0.4551,
 873: 0.4351,
 874: 0.4383,
 875: 0.4281,
 876: 0.4168,
 877: 0.4255,
 878: 0.4291,
 879: 0.4312,
 880: 0.4353,
 881: 0.4209,
 882: 0.4226,
 883: 0.4312,
 884: 0.437,
 885: 0.4201,
 886: 0.4336,
 887: 0.4287,
 888: 0.4317,
 889: 0.4404,
 890: 0.4204,
 891: 0.4378,
 892: 0.4299,
 893: 0.4376,
 894: 0.4374,
 895: 0.4321,
 896: 0.4393,
 897: 0.4309,
 898: 0.4197,
 899: 0.4675,
 900: 0.4264,
 901: 0.4206,
 902: 0.4288,
 903: 0.4234,
 904: 0.4353,
 905: 0.4121,
 906: 0.4525,
 907: 0.4112,
 908: 0.4526,
 909: 0.4243,
 910: 0.4299,
 911: 0.4257,
 912: 0.4325,
 913: 0.4308,
 914: 0.4275,
 915: 0.4165,
 916: 0.4367,
 917: 0.4477,
 918: 0.4344,
 919: 0.4268,
 920: 0.4261,
 921: 0.4297,
 922: 0.4242,
 923: 0.4286,
 924: 0.4417,
 925: 0.4257,
 926: 0.4859,
 927: 0.4353,
 928: 0.4396,
 929: 0.4145,
 930: 0.4273,
 931: 0.4427,
 932: 0.4262,
 933: 0.4279,
 934: 0.4294,
 935: 0.4231,
 936: 0.4174,
 937: 0.4257,
 938: 0.4382,
 939: 0.4367,
 940: 0.4193,
 941: 0.4208,
 942: 0.4243,
 943: 0.4232,
 944: 0.4295,
 945: 0.4228,
 946: 0.4271,
 947: 0.4248,
 948: 0.4348,
 949: 0.4207,
 950: 0.4149,
 951: 0.4562,
 952: 0.4225,
 953: 0.4265,
 954: 0.4291,
 955: 0.4316,
 956: 0.4221,
 957: 0.4217,
 958: 0.4175,
 959: 0.4303,
 960: 0.425,
 961: 0.5085,
 962: 0.4369,
 963: 0.4161,
 964: 0.4164,
 965: 0.4199,
 966: 0.4297,
 967: 0.4431,
 968: 0.4318,
 969: 0.4323,
 970: 0.4279,
 971: 0.427,
 972: 0.4196,
 973: 0.427,
 974: 0.4193,
 975: 0.4185,
 976: 0.432,
 977: 0.4296,
 978: 0.4212,
 979: 0.4306,
 980: 0.4234,
 981: 0.4322,
 982: 0.4423,
 983: 0.419,
 984: 0.4152,
 985: 0.4361,
 986: 0.4159,
 987: 0.4254,
 988: 0.447,
 989: 0.4156,
 990: 0.4187,
 991: 0.4252,
 992: 0.4274,
 993: 0.4272,
 994: 0.4258,
 995: 0.4263,
 996: 0.4219,
 997: 0.4319,
 998: 0.4287,
 999: 0.4385,
 ...}

In [24]:
import geopandas as gpd

subbasin_raster = wbe.read_raster(r"C:\Work\imWEBs\Interface\BRC_TIFFs\subbasin.tif")
field_raster = wbe.read_raster(r"C:\Work\imWEBs\Interface\BRC_TIFFs\field.tif")
field_shp = r"C:\Work\imWEBs\Interface\BRC_TIFFs\field.shp"
subbasin_shp = r"C:\Work\imWEBs\Interface\BRC_TIFFs\subbasin.shp"
wbe.write_vector(wbe.raster_to_vector_polygons(subbasin_raster), subbasin_shp)
wbe.write_vector(wbe.raster_to_vector_polygons(field_raster), field_shp)

#read shapefile and restructure the columns
field_shp_df = gpd.read_file(field_shp)
subbasin_shp_df = gpd.read_file(subbasin_shp)

#identify
field_subbasin_df = gpd.overlay(subbasin_shp_df, field_shp_df, how='identity')

c:\Users\hawkl\AppData\Local\Programs\Python\Python312\Lib\site-packages\geopandas\geodataframe.py:1816: FutureWarning: `unary_union` returned None due to all-None GeoSeries. In future, `unary_union` will return 'GEOMETRYCOLLECTION EMPTY' instead.
  merged_geom = block.unary_union
C:\Users\hawkl\AppData\Local\Temp\ipykernel_12540\4072432748.py:15: UserWarning: `keep_geom_type=True` in overlay resulted in 5722 dropped geometries of different geometry types than df1 has. Set `keep_geom_type=False` to retain all geometries
  field_subbasin_df = gpd.overlay(subbasin_shp_df, field_shp_df, how='identity')

In [25]:
field_subbasin_df

,FID_1,VALUE_1,FID_2,VALUE_2,geometry
0,1.0,1.0,1.0,10.0,"MULTIPOLYGON (((408915.905 5576331.270, 408945..."
1,1.0,1.0,2.0,604.0,"POLYGON ((408945.850 5576930.693, 408975.796 5..."
2,1.0,1.0,3.0,605.0,"POLYGON ((408885.959 5576331.270, 408915.905 5..."
3,1.0,1.0,7.0,2.0,"POLYGON ((408885.959 5575821.761, 408885.959 5..."
4,1.0,1.0,8.0,33.0,"POLYGON ((408706.286 5575911.674, 408676.340 5..."
...,...,...,...,...,...
10024,4426.0,4384.0,NaN,NaN,"MULTIPOLYGON (((413916.812 5546719.770, 413886..."
10025,4428.0,4386.0,NaN,NaN,"MULTIPOLYGON (((413287.956 5546959.540, 413287..."
10026,4430.0,4388.0,NaN,NaN,"POLYGON ((413377.792 5546869.626, 413407.738 5..."
10027,4431.0,4389.0,NaN,NaN,"MULTIPOLYGON (((413826.976 5546839.655, 413826..."
10028,4432.0,4390.0,NaN,NaN,"POLYGON ((414156.377 5546839.655, 414156.377 5..."

In [28]:
class PairList:
    def __init__(self):
        self.data = {}

    def contains(self, id1, id2):
        return (id1, id2) in self.data

    def setValue(self, id1, id2, value):
        self.data[(id1, id2)] = value

    def getValue(self, id1, id2):
        return self.data.get((id1, id2), 0)

    def add(self, id1, id2, value):
        self.data[(id1, id2)] = value


def get_overlap_relation_pair_list(spatial1_ras:Raster, spatial2_ras:Raster):
    pl = PairList()

    rows = spatial1_ras.configs.rows
    cols = spatial1_ras.configs.columns

    cell_area = spatial1_ras.configs.resolution_x * spatial1_ras.configs.resolution_y

    for col in range(cols):
        for row in range(rows):
            id1 = int(spatial1_ras[row, col])
            id2 = int(spatial2_ras[row, col])

            if id1 > 0 and id2 > 0:
                if pl.contains(id1, id2):
                    pl.setValue(id1, id2, pl.getValue(id1, id2) + cell_area)
                else:
                    pl.add(id1, id2, cell_area)

    return pl

pl = get_overlap_relation_pair_list(field_raster, subbasin_raster)
print(pl.data)

{(305, 1494): 83467.75966773694, (305, 1690): 3590.011168504817, (663, 1494): 897.5027921262042, (163, 1494): 63722.69824096039, (23, 1494): 210913.1561496585, (23, 1690): 1795.0055842524084, (329, 1494): 48465.150774814974, (141, 1494): 12565.03908976686, (141, 1505): 73595.22895434865, (64, 684): 588761.831634788, (23, 1683): 2692.5083763786124, (163, 1612): 2692.5083763786124, (163, 1683): 897.5027921262042, (141, 1513): 62825.19544883419, (163, 1626): 59235.184280329384, (212, 1513): 30515.094932290947, (163, 1593): 1795.0055842524084, (23, 1679): 32310.100516543356, (329, 1841): 2692.5083763786124, (144, 1494): 4487.513960631021, (141, 1593): 5385.016752757226, (144, 1900): 10770.033505514451, (144, 1944): 17950.055842524085, (64, 303): 89750.2792126204, (141, 1575): 21540.067011028903, (163, 1679): 18847.55863465029, (23, 1735): 32310.100516543356, (23, 1841): 3590.011168504817, (163, 1627): 2692.5083763786124, (144, 1896): 5385.016752757226, (144, 1897): 88852.77642049419, (144, 1964): 34105.10610079576, (115, 303): 427211.32905207464, (64, 1116): 27822.586555912334, (64, 1197): 9872.530713388247, (144, 2000): 6282.51954488343, (64, 1190): 17052.55305039788, (64, 1138): 9872.530713388247, (212, 684): 182193.06680161983, (141, 1557): 14360.04467401927, (144, 1995): 5385.016752757226, (141, 684): 143600.44674019289, (163, 1597): 37695.117269300565, (163, 1659): 3590.011168504817, (163, 1674): 35002.60889292196, (101, 684): 227068.20640793024, (43, 684): 461316.43515287054, (141, 1597): 2692.5083763786124, (163, 1649): 14360.04467401927, (163, 1670): 6282.51954488343, (23, 1674): 15257.547466145474, (141, 1526): 42182.63122993157, (23, 1791): 8975.027921262043, (212, 1500): 18847.55863465029, (141, 1500): 2692.5083763786124, (23, 1586): 428108.83184420085, (144, 1982): 19745.061426776494, (71, 303): 52952.66473544598, (71, 684): 43977.63681418397, (141, 1598): 2692.5083763786124, (23, 1741): 6282.51954488343, (250, 1926): 2692.5083763786124, (102, 684): 343743.5693843373, (163, 1598): 10770.033505514451, (328, 1897): 6282.51954488343, (328, 1888): 72697.72616222245, (106, 303): 392208.7201591525, (71, 635): 36797.614477174364, (101, 851): 57440.17869607698, (101, 925): 33207.60330866956, (23, 1721): 8077.525129135839, (23, 1876): 13462.541881893065, (144, 2004): 12565.03908976686, (43, 925): 38592.620061426765, (163, 684): 69107.71499371761, (328, 1494): 897.5027921262042, (122, 1926): 245915.7650425806, (115, 366): 42182.63122993157, (101, 766): 4487.513960631021, (102, 1373): 67312.7094094652, (212, 1514): 8975.027921262043, (141, 1514): 26027.580971659925, (328, 1876): 897.5027921262042, (144, 1965): 77185.24012285349, (122, 2004): 8077.525129135839, (71, 700): 21540.067011028903, (163, 1586): 27822.586555912334, (328, 1880): 5385.016752757226, (106, 545): 9872.530713388247, (101, 785): 13462.541881893065, (43, 1000): 62825.19544883419, (43, 1056): 99622.80992600869, (102, 1409): 2692.5083763786124, (122, 2015): 33207.60330866956, (422, 1926): 24232.575387407516, (71, 627): 897.5027921262042, (71, 616): 29617.592140164743, (101, 817): 8975.027921262043, (43, 1230): 93340.29038112523, (102, 1405): 21540.067011028903, (71, 704): 16155.050258271678, (295, 684): 21540.067011028903, (122, 1965): 9872.530713388247, (71, 766): 8077.525129135839, (43, 1251): 8077.525129135839, (151, 684): 37695.117269300565, (151, 1600): 3590.011168504817, (23, 1853): 82570.25687561074, (122, 2043): 18847.55863465029, (101, 906): 2692.5083763786124, (102, 1339): 10770.033505514451, (151, 1576): 29617.592140164743, (295, 1600): 6282.51954488343, (295, 1628): 21540.067011028903, (71, 701): 26925.08376378613, (101, 895): 26925.08376378613, (102, 1356): 16155.050258271678, (295, 1586): 67312.7094094652, (144, 1888): 37695.117269300565, (71, 615): 34105.10610079576, (101, 818): 897.5027921262042, (101, 919): 26027.580971659925, (43, 1147): 10770.033505514451, (716, 684): 1795.0055842524084, (122, 2008): 27822.586555912334, (122, 2021): 9872.530713388247, (101, 710): 14360.04467401927, (43, 1290): 20642.5642189027, (23, 1777): 1795.0055842524084, (144, 1976): 1795.0055842524084, (144, 1970): 41285.12843780537, (71, 710): 52055.16194331978, (101, 797): 17052.55305039788, (43, 1106): 39490.122853552966, (102, 1340): 8975.027921262043, (122, 1970): 18847.55863465029, (102, 1383): 4487.513960631021, (568, 684): 8975.027921262043, (151, 1479): 183988.07238587225, (151, 1580): 5385.016752757226, (23, 1731): 11667.536297640656, (23, 1703): 100520.3127181349, (254, 303): 98725.30713388248, (43, 1327): 1795.0055842524084, (102, 1327): 897.5027921262042, (102, 1341): 48465.150774814974, (151, 1586): 24232.575387407516, (23, 1845): 7180.022337009635, (106, 546): 9872.530713388247, (101, 841): 16155.050258271678, (101, 876): 1795.0055842524084, (43, 1070): 36797.614477174364, (43, 1258): 4487.513960631021, (102, 1484): 12565.03908976686, (637, 1970): 2692.5083763786124, (71, 604): 13462.541881893065, (101, 926): 37695.117269300565, (101, 950): 1795.0055842524084, (43, 1206): 17052.55305039788, (43, 1317): 9872.530713388247, (23, 1691): 44875.13960631017, (23, 1888): 1795.0055842524084, (122, 2060): 10770.033505514451, (71, 651): 17052.55305039788, (101, 884): 19745.061426776494, (43, 1291): 2692.5083763786124, (715, 1484): 1795.0055842524084, (568, 1484): 897.5027921262042, (151, 1484): 7180.022337009635, (383, 1888): 33207.60330866956, (731, 1970): 897.5027921262042, (122, 2142): 11667.536297640656, (250, 2142): 8975.027921262043, (43, 1122): 7180.022337009635, (43, 1296): 8077.525129135839, (102, 1362): 4487.513960631021, (102, 1442): 3590.011168504817, (102, 1470): 2692.5083763786124, (176, 1484): 3590.011168504817, (122, 2050): 8077.525129135839, (106, 547): 18847.55863465029, (43, 1123): 17052.55305039788, (102, 1317): 3590.011168504817, (23, 1817): 12565.03908976686, (144, 1945): 897.5027921262042, (122, 2134): 2692.5083763786124, (250, 2174): 34105.10610079576, (106, 604): 897.5027921262042, (71, 674): 26925.08376378613, (101, 868): 897.5027921262042, (399, 1070): 897.5027921262042, (43, 1158): 2692.5083763786124, (134, 1158): 181295.56400949362, (176, 1362): 8077.525129135839, (176, 1341): 1795.0055842524084, (176, 684): 28720.08934803854, (176, 1429): 12565.03908976686, (176, 1442): 16155.050258271678, (176, 1470): 11667.536297640656, (176, 1479): 43977.63681418397, (349, 1817): 8975.027921262043, (106, 579): 6282.51954488343, (71, 597): 8975.027921262043, (71, 715): 35900.11168504816, (101, 842): 9872.530713388247, (399, 1057): 16155.050258271678, (134, 1123): 22437.569803155107, (134, 1296): 8077.525129135839, (23, 1779): 33207.60330866956, (383, 1945): 10770.033505514451, (106, 597): 3590.011168504817, (71, 605): 23335.07259528131, (71, 711): 3590.011168504817, (333, 710): 1795.0055842524084, (333, 797): 12565.03908976686, (399, 984): 9872.530713388247, (134, 1070): 2692.5083763786124, (134, 1083): 72697.72616222245, (134, 1206): 3590.011168504817, (176, 1317): 9872.530713388247, (176, 1158): 145395.4523244453, (106, 486): 61927.692656707986, (333, 841): 1795.0055842524084, (101, 940): 19745.061426776494, (43, 1083): 897.5027921262042, (134, 1317): 8077.525129135839, (176, 1471): 8975.027921262043, (23, 1742): 12565.03908976686, (23, 1736): 35900.11168504816, (349, 1779): 16155.050258271678, (23, 1848): 5385.016752757226, (106, 555): 23335.07259528131, (333, 789): 5385.016752757226, (333, 842): 35002.60889292196, (399, 926): 28720.08934803854, (134, 1057): 19745.061426776494, (134, 1311): 2692.5083763786124, (176, 1344): 14360.04467401927, (23, 1639): 22437.569803155107, (23, 1778): 4487.513960631021, (349, 1769): 42182.63122993157, (23, 1769): 6282.51954488343, (349, 1853): 897.5027921262042, (250, 2175): 7180.022337009635, (71, 679): 44875.13960631017, (333, 852): 8975.027921262043, (399, 1025): 1795.0055842524084, (23, 1479): 897.5027921262042, (349, 1881): 4487.513960631021, (106, 605): 897.5027921262042, (71, 753): 5385.016752757226, (134, 1025): 26027.580971659925, (383, 1881): 897.5027921262042, (383, 1925): 897.5027921262042, (383, 1926): 897.5027921262042, (431, 1926): 26027.580971659925, (536, 1926): 12565.03908976686, (489, 1926): 19745.061426776494, (322, 2122): 3590.011168504817, (322, 1926): 88852.77642049419, (538, 1926): 6282.51954488343, (46, 2175): 23335.07259528131, (134, 926): 26925.08376378613, (134, 1094): 12565.03908976686, (134, 1292): 2692.5083763786124, (151, 1501): 13462.541881893065, (224, 1881): 17950.055842524085, (431, 1881): 2692.5083763786124, (431, 1925): 5385.016752757226, (540, 3305): 1795.0055842524084, (425, 555): 8077.525129135839, (555, 926): 7180.022337009635, (151, 1535): 5385.016752757226, (23, 1594): 11667.536297640656, (224, 1926): 71800.22337009624, (149, 1926): 292585.9102331434, (46, 2217): 29617.592140164743, (46, 2239): 8077.525129135839, (784, 3434): 1795.0055842524084, (425, 486): 12565.03908976686, (151, 1534): 2692.5083763786124, (151, 1568): 4487.513960631021, (151, 1594): 2692.5083763786124, (120, 1769): 127445.39648192114, (561, 3434): 3590.011168504817, (40, 3539): 93340.29038112523, (134, 1017): 13462.541881893065, (176, 1357): 4487.513960631021, (176, 1480): 2692.5083763786124, (176, 1501): 897.5027921262042, (591, 1736): 4487.513960631021, (591, 1761): 3590.011168504817, (120, 1761): 23335.07259528131, (120, 1779): 4487.513960631021, (120, 1809): 4487.513960631021, (46, 1926): 27822.586555912334, (230, 3305): 38592.620061426765, (425, 606): 1795.0055842524084, (624, 605): 1795.0055842524084, (627, 842): 1795.0055842524084, (555, 911): 2692.5083763786124, (134, 1117): 1795.0055842524084, (140, 1515): 14360.04467401927, (140, 1534): 7180.022337009635, (140, 1535): 48465.150774814974, (140, 1568): 2692.5083763786124, (140, 1569): 26925.08376378613, (140, 1594): 8975.027921262043, (341, 1594): 58337.68148820318, (341, 1586): 897.5027921262042, (341, 1703): 2692.5083763786124, (341, 1714): 8975.027921262043, (591, 1714): 897.5027921262042, (5, 3305): 79877.74849923211, (425, 303): 2692.5083763786124, (425, 504): 3590.011168504817, (425, 548): 897.5027921262042, (624, 606): 897.5027921262042, (71, 725): 897.5027921262042, (134, 1282): 897.5027921262042, (12, 1158): 32310.100516543356, (84, 1158): 46670.14519056257, (84, 1357): 29617.592140164743, (84, 1454): 24232.575387407516, (84, 1480): 25130.07817953372, (140, 1501): 5385.016752757226, (140, 1527): 11667.536297640656, (46, 2189): 407466.26762529806, (46, 2209): 19745.061426776494, (46, 2232): 23335.07259528131, (46, 2257): 21540.067011028903, (40, 3551): 70005.21778584382, (660, 786): 1795.0055842524084, (660, 842): 1795.0055842524084, (12, 842): 8077.525129135839, (12, 885): 7180.022337009635, (12, 911): 78980.2457071059, (12, 926): 7180.022337009635, (12, 1017): 15257.547466145474, (12, 1026): 240530.74828982336, (12, 1282): 2692.5083763786124, (84, 1312): 897.5027921262042, (84, 1342): 5385.016752757226, (120, 1714): 86160.26804411557, (224, 1966): 6282.51954488343, (40, 3510): 4487.513960631021, (114, 303): 17052.55305039788, (114, 504): 5385.016752757226, (114, 517): 37695.117269300565, (114, 548): 22437.569803155107, (114, 555): 3590.011168504817, (114, 606): 1795.0055842524084, (138, 606): 105905.32947089215, (138, 605): 897.5027921262042, (625, 605): 1795.0055842524084, (625, 660): 3590.011168504817, (12, 660): 12565.03908976686, (12, 679): 3590.011168504817, (493, 679): 897.5027921262042, (493, 660): 4487.513960631021, (493, 725): 11667.536297640656, (12, 786): 35900.11168504816, (12, 1001): 20642.5642189027, (12, 1030): 18847.55863465029, (12, 1191): 13462.541881893065, (87, 1594): 28720.08934803854, (87, 1714): 15257.547466145474, (149, 2009): 897.5027921262042, (419, 3510): 897.5027921262042, (114, 539): 1795.0055842524084, (138, 660): 13462.541881893065, (12, 725): 1795.0055842524084, (12, 767): 52952.66473544598, (12, 1047): 16155.050258271678, (84, 1374): 18847.55863465029, (140, 1488): 53850.16752757218, (224, 1912): 6282.51954488343, (149, 1984): 4487.513960631021, (46, 2269): 2692.5083763786124, (114, 466): 897.5027921262042, (114, 460): 46670.14519056257, (493, 705): 3590.011168504817, (493, 767): 1795.0055842524084, (12, 886): 7180.022337009635, (84, 1488): 8975.027921262043, (140, 1538): 87955.27362836798, (46, 2251): 2692.5083763786124, (46, 2282): 35900.11168504816, (114, 540): 44875.13960631017, (12, 705): 35002.60889292196, (12, 853): 24232.575387407516, (84, 1394): 5385.016752757226, (140, 1516): 17052.55305039788, (224, 1984): 7180.022337009635, (149, 2030): 52952.66473544598, (230, 3329): 9872.530713388247, (5, 3356): 9872.530713388247, (12, 834): 1795.0055842524084, (12, 944): 29617.592140164743, (12, 1002): 91545.28479687282, (12, 1163): 3590.011168504817, (12, 1312): 1795.0055842524084, (84, 1351): 126547.89368979493, (84, 1448): 80775.25129135832, (440, 1594): 17052.55305039788, (87, 1715): 4487.513960631021, (224, 1769): 5385.016752757226, (149, 2076): 9872.530713388247, (5, 3401): 14360.04467401927, (12, 991): 2692.5083763786124, (84, 1328): 14360.04467401927, (87, 1732): 23335.07259528131, (224, 1919): 38592.620061426765, (46, 2221): 6282.51954488343, (40, 3434): 13462.541881893065, (114, 497): 14360.04467401927, (138, 705): 897.5027921262042, (12, 824): 81672.75408348453, (12, 927): 31412.59772441715, (12, 1328): 2692.5083763786124, (46, 2247): 15257.547466145474, (5, 3329): 31412.59772441715, (40, 3600): 7180.022337009635, (114, 438): 4487.513960631021, (224, 1913): 7180.022337009635, (224, 1971): 8077.525129135839, (47, 2076): 26925.08376378613, (149, 2032): 12565.03908976686, (46, 2294): 57440.17869607698, (40, 3511): 20642.5642189027, (87, 1650): 25130.07817953372, (87, 1722): 17950.055842524085, (120, 1854): 35002.60889292196, (149, 2001): 4487.513960631021, (46, 2323): 1795.0055842524084, (5, 3383): 469393.9602820064, (114, 428): 8975.027921262043, (114, 467): 26027.580971659925, (12, 690): 46670.14519056257, (12, 962): 42182.63122993157, (12, 1071): 52055.16194331978, (140, 1506): 34105.10610079576, (140, 1570): 7180.022337009635, (440, 1629): 4487.513960631021, (120, 1732): 897.5027921262042, (120, 1821): 6282.51954488343, (149, 2005): 6282.51954488343, (149, 2018): 8975.027921262043, (47, 2030): 17052.55305039788, (47, 2105): 1795.0055842524084, (47, 2032): 168730.5249197267, (46, 2283): 17950.055842524085, (138, 690): 41285.12843780537, (12, 758): 22437.569803155107, (140, 1587): 8975.027921262043, (87, 1697): 7180.022337009635, (120, 1828): 44875.13960631017, (224, 1882): 14360.04467401927, (149, 1971): 3590.011168504817, (117, 1926): 17052.55305039788, (117, 2189): 291688.4074410172, (46, 2332): 18847.55863465029, (46, 2329): 1795.0055842524084, (97, 2424): 189373.0891386295, (114, 412): 9872.530713388247, (114, 407): 88852.77642049419, (12, 783): 50260.156359067376, (12, 896): 8975.027921262043, (84, 1302): 17950.055842524085, (84, 1345): 40387.62564567917, (140, 1448): 1795.0055842524084, (87, 1629): 2692.5083763786124, (87, 1698): 35002.60889292196, (120, 1798): 17950.055842524085, (730, 1971): 897.5027921262042, (5, 3373): 6282.51954488343, (87, 1640): 18847.55863465029, (730, 1882): 897.5027921262042, (47, 1977): 9872.530713388247, (47, 1978): 71800.22337009624, (47, 2018): 8077.525129135839, (97, 2482): 54747.67031969838, (114, 564): 22437.569803155107, (12, 928): 32310.100516543356, (12, 1050): 6282.51954488343, (84, 1410): 35900.11168504816, (84, 1465): 26027.580971659925, (246, 1570): 1795.0055842524084, (246, 1587): 15257.547466145474, (87, 1762): 11667.536297640656, (47, 1882): 27822.586555912334, (47, 1926): 1795.0055842524084, (46, 2349): 17052.55305039788, (230, 3265): 52055.16194331978, (40, 3383): 106802.83226301835, (114, 448): 26027.580971659925, (12, 897): 56542.67590395078, (12, 1031): 32310.100516543356, (415, 1026): 3590.011168504817, (84, 1378): 47567.64798268877, (87, 1588): 8077.525129135839, (87, 1660): 49362.653566941175, (120, 1785): 29617.592140164743, (46, 2377): 13462.541881893065, (105, 2482): 142702.94394806668, (40, 3530): 7180.022337009635, (114, 608): 897.5027921262042, (138, 608): 1795.0055842524084, (12, 825): 12565.03908976686, (12, 859): 10770.033505514451, (84, 1352): 897.5027921262042, (47, 2135): 10770.033505514451, (46, 2313): 61030.189864581786, (5, 3374): 15257.547466145474, (114, 505): 2692.5083763786124, (138, 564): 13462.541881893065, (12, 972): 21540.067011028903, (12, 992): 18847.55863465029, (246, 1538): 4487.513960631021, (120, 1762): 897.5027921262042, (120, 1818): 23335.07259528131, (47, 2117): 92442.78758899902, (97, 2189): 66415.20661733899, (17, 2677): 108597.83784727077, (40, 3547): 19745.061426776494, (114, 478): 3590.011168504817, (84, 1430): 9872.530713388247, (84, 1476): 8975.027921262043, (140, 1481): 34105.10610079576, (140, 1550): 2692.5083763786124, (246, 1588): 17052.55305039788, (87, 1630): 8077.525129135839, (87, 1631): 17052.55305039788, (87, 1671): 1795.0055842524084, (87, 1747): 29617.592140164743, (548, 1882): 7180.022337009635, (149, 2117): 4487.513960631021, (117, 2176): 57440.17869607698, (117, 2210): 29617.592140164743, (17, 2482): 30515.094932290947, (5, 3379): 11667.536297640656, (40, 3595): 8077.525129135839, (469, 1026): 1795.0055842524084, (469, 1164): 13462.541881893065, (415, 1164): 23335.07259528131, (84, 1330): 35002.60889292196, (84, 1449): 10770.033505514451, (140, 1476): 11667.536297640656, (246, 1550): 19745.061426776494, (87, 1704): 61927.692656707986, (120, 1822): 5385.016752757226, (548, 1854): 897.5027921262042, (117, 2218): 18847.55863465029, (46, 2350): 897.5027921262042, (17, 2686): 335666.0442552014, (138, 636): 55645.17311182458, (12, 1018): 24232.575387407516, (548, 1822): 897.5027921262042, (47, 1985): 4487.513960631021, (47, 2022): 45772.64239843637, (97, 2529): 8975.027921262043, (17, 2867): 897.5027921262042, (17, 2868): 15257.547466145474, (40, 3564): 8975.027921262043, (138, 628): 8975.027921262043, (12, 790): 26925.08376378613, (12, 843): 3590.011168504817, (12, 1139): 5385.016752757226, (84, 1411): 10770.033505514451, (120, 1810): 9872.530713388247, (313, 1822): 77185.24012285349, (47, 1927): 6282.51954488343, (46, 2360): 5385.016752757226, (97, 2461): 3590.011168504817, (105, 2553): 10770.033505514451, (12, 860): 8975.027921262043, (12, 887): 11667.536297640656, (12, 1051): 12565.03908976686, (140, 1465): 897.5027921262042, (120, 1792): 21540.067011028903, (47, 1959): 3590.011168504817, (149, 2159): 5385.016752757226, (105, 2610): 6282.51954488343, (5, 3324): 30515.094932290947, (114, 565): 1795.0055842524084, (114, 598): 897.5027921262042, (114, 585): 8077.525129135839, (430, 1293): 16155.050258271678, (84, 1370): 21540.067011028903, (84, 1431): 5385.016752757226, (142, 1431): 38592.620061426765, (142, 1465): 2692.5083763786124, (246, 1507): 36797.614477174364, (47, 1920): 4487.513960631021, (47, 2002): 2692.5083763786124, (47, 2106): 35002.60889292196, (47, 2159): 10770.033505514451, (46, 2387): 1795.0055842524084, (40, 3587): 17052.55305039788, (138, 642): 8975.027921262043, (12, 718): 6282.51954488343, (12, 869): 10770.033505514451, (12, 985): 4487.513960631021, (610, 1164): 3590.011168504817, (84, 1395): 7180.022337009635, (142, 1481): 2692.5083763786124, (140, 1507): 9872.530713388247, (246, 1571): 23335.07259528131, (87, 1684): 8077.525129135839, (165, 1920): 27822.586555912334, (47, 1986): 8077.525129135839, (47, 2033): 45772.64239843637, (117, 2222): 41285.12843780537, (97, 2402): 13462.541881893065, (749, 2424): 1795.0055842524084, (105, 2424): 70902.72057797003, (105, 2550): 29617.592140164743, (105, 2598): 30515.094932290947, (5, 3265): 82570.25687561074, (40, 3548): 9872.530713388247, (40, 3565): 24232.575387407516, (40, 3578): 23335.07259528131, (114, 518): 8077.525129135839, (138, 585): 2692.5083763786124, (138, 637): 1795.0055842524084, (138, 718): 9872.530713388247, (12, 754): 4487.513960631021, (12, 826): 24232.575387407516, (12, 915): 22437.569803155107, (12, 1100): 6282.51954488343, (12, 716): 61030.189864581786, (145, 1139): 897.5027921262042, (610, 716